{
  "name": "W2_Churn",
  "compatibilityLevel": 1601,
  "model": {
    "culture": "en-US",
    "sourceQueryCulture": "en-US",
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "tables": [
      {
        "name": "Customers",
        "columns": [
          {
            "name": "gender",
            "dataType": "string",
            "sourceColumn": "gender",
            "summarizeBy": "none"
          },
          {
            "name": "SeniorCitizen",
            "dataType": "int64",
            "sourceColumn": "SeniorCitizen",
            "summarizeBy": "none"
          },
          {
            "name": "Partner",
            "dataType": "string",
            "sourceColumn": "Partner",
            "summarizeBy": "none"
          },
          {
            "name": "Dependents",
            "dataType": "string",
            "sourceColumn": "Dependents",
            "summarizeBy": "none"
          },
          {
            "name": "tenure",
            "dataType": "int64",
            "sourceColumn": "tenure",
            "summarizeBy": "none"
          },
          {
            "name": "PhoneService",
            "dataType": "string",
            "sourceColumn": "PhoneService",
            "summarizeBy": "none"
          },
          {
            "name": "MultipleLines",
            "dataType": "string",
            "sourceColumn": "MultipleLines",
            "summarizeBy": "none"
          },
          {
            "name": "InternetService",
            "dataType": "string",
            "sourceColumn": "InternetService",
            "summarizeBy": "none"
          },
          {
            "name": "OnlineSecurity",
            "dataType": "string",
            "sourceColumn": "OnlineSecurity",
            "summarizeBy": "none"
          },
          {
            "name": "OnlineBackup",
            "dataType": "string",
            "sourceColumn": "OnlineBackup",
            "summarizeBy": "none"
          },
          {
            "name": "DeviceProtection",
            "dataType": "string",
            "sourceColumn": "DeviceProtection",
            "summarizeBy": "none"
          },
          {
            "name": "TechSupport",
            "dataType": "string",
            "sourceColumn": "TechSupport",
            "summarizeBy": "none"
          },
          {
            "name": "StreamingTV",
            "dataType": "string",
            "sourceColumn": "StreamingTV",
            "summarizeBy": "none"
          },
          {
            "name": "StreamingMovies",
            "dataType": "string",
            "sourceColumn": "StreamingMovies",
            "summarizeBy": "none"
          },
          {
            "name": "Contract",
            "dataType": "string",
            "sourceColumn": "Contract",
            "summarizeBy": "none"
          },
          {
            "name": "PaperlessBilling",
            "dataType": "string",
            "sourceColumn": "PaperlessBilling",
            "summarizeBy": "none"
          },
          {
            "name": "PaymentMethod",
            "dataType": "string",
            "sourceColumn": "PaymentMethod",
            "summarizeBy": "none"
          },
          {
            "name": "MonthlyCharges",
            "dataType": "double",
            "sourceColumn": "MonthlyCharges",
            "summarizeBy": "none"
          },
          {
            "name": "Churn",
            "dataType": "string",
            "sourceColumn": "Churn",
            "summarizeBy": "none"
          },
          {
            "name": "service_count",
            "dataType": "int64",
            "sourceColumn": "service_count",
            "summarizeBy": "none"
          },
          {
            "name": "tenure_band",
            "dataType": "string",
            "sourceColumn": "tenure_band",
            "summarizeBy": "none",
            "sortByColumn": "tenure_band_order"
          },
          {
            "name": "fee_quartile",
            "dataType": "string",
            "sourceColumn": "fee_quartile",
            "summarizeBy": "none"
          },
          {
            "name": "has_internet",
            "dataType": "string",
            "sourceColumn": "has_internet",
            "summarizeBy": "none"
          },
          {
            "name": "fee_level",
            "dataType": "string",
            "sourceColumn": "fee_level",
            "summarizeBy": "none"
          },
          {
            "name": "service_level",
            "dataType": "string",
            "sourceColumn": "service_level",
            "summarizeBy": "none"
          },
          {
            "name": "manual_payment",
            "dataType": "string",
            "sourceColumn": "manual_payment",
            "summarizeBy": "none"
          },
          {
            "name": "risk_rule",
            "dataType": "string",
            "sourceColumn": "risk_rule",
            "summarizeBy": "none"
          },
          {
            "name": "combination",
            "dataType": "string",
            "sourceColumn": "combination",
            "summarizeBy": "none"
          },
          {
            "name": "tenure_band_order",
            "dataType": "int64",
            "sourceColumn": "tenure_band_order",
            "summarizeBy": "none",
            "isHidden": true
          }
        ],
        "measures": [
          {
            "name": "Customer count",
            "expression": "COALESCE(COUNTROWS('Customers'), 0)",
            "formatString": "#,0"
          },
          {
            "name": "Churned customers",
            "expression": "COALESCE(CALCULATE(COUNTROWS('Customers'), KEEPFILTERS('Customers'[Churn] = \"Yes\")), 0)",
            "formatString": "#,0"
          },
          {
            "name": "Observed churn rate",
            "expression": "DIVIDE([Churned customers], [Customer count])",
            "formatString": "0.00%"
          },
          {
            "name": "Average monthly charge",
            "expression": "AVERAGE('Customers'[MonthlyCharges])",
            "formatString": "0.00"
          },
          {
            "name": "Average tenure",
            "expression": "AVERAGE('Customers'[tenure])",
            "formatString": "0.0"
          },
          {
            "name": "Internet customers",
            "expression": "CALCULATE([Customer count], KEEPFILTERS('Customers'[InternetService] <> \"No\"))",
            "formatString": "#,0"
          },
          {
            "name": "Internet churned",
            "expression": "CALCULATE([Churned customers], KEEPFILTERS('Customers'[InternetService] <> \"No\"))",
            "formatString": "#,0"
          },
          {
            "name": "Internet churn rate",
            "expression": "DIVIDE([Internet churned], [Internet customers])",
            "formatString": "0.00%"
          },
          {
            "name": "Small group note",
            "expression": "IF([Customer count] < 30, \"n < 30: interpret cautiously\", \"\")"
          },
          {
            "name": "Internet average monthly charge",
            "expression": "CALCULATE(AVERAGE('Customers'[MonthlyCharges]), KEEPFILTERS('Customers'[InternetService] <> \"No\"))",
            "formatString": "0.00"
          }
        ],
        "partitions": [
          {
            "name": "Customers",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Rows = Json.Document(Binary.Decompress(Binary.FromText(\"3L1LrzQ5kiX2Vwq1koDsC9Ld6Y+lXgMtZjSQNBuhoUWpOru7MD1Vg+pqDfTvdePhfLk96Ua/HjmLmMwvsyuDQdJoduzYOX//97//d7/+lz/8y6+//8X98vv/69d//f0vv//f/vL7X/zr//v++N1//ee//PnX3/3rr3/9f//0x+9/7ff/8//579//Uvbv1x//4S9//ts//93f/vJ3/+XxF/Ff/V/+5dc//u2vf/nzn/74uz/+869//M+//2XYvtYQ/5t/736Z//vvf+9/9/H/5N//5b/97h9/ffyH3d8Nv/vDP/zD3/3lz48//w9/+PO//eFfvv/i//i3f/n1d//4L3/4p3/69R8e/5Z33//vezn/9y9///0vvVcWv9k4FV/7tZjsD8Al/cfvH+D/+/UPf42r+8Of/uXXf9iXEOav7b2E4XsJw/TLtD4XMcgX8R//9s+//vV3f/y3f/3bX/7Lr399/CP/XMj3F4bXMaDLUG9KtZrxuSHPfzRkO6JYTLUjnt6RKXBn7bA99RLr/fkf//Dn//y7v/31D3/+13/8/lX/uz/82/ev+oe//emP3wuZhq/xfRLYvRr/bs6W9z/s/yvYdvm4XdmVQjbs3/3p//n+H/jLf339z0Gb1XCXFve1vP+py3ZujP8n/+uf/umfdZfJZVsHrWottwRbFrKD4pVt29e8H8rHvs2/+OG5tglaW7lvxB1z7rFt35HneDJf539gl1cfxezvkdX9T3/99R/+9Lff/fEPf/2H8miu25dPYcQPvwyTdP/os/mIJP57FwdsF71TXEHREQXC5HekX7JIH7dQEeqha/c6oL5aWvq+g+qIHj/FZ9S76Wv/b01FbDl9SP3jkAIPwfN/dG55ChQR8/t589nzNq2/LKPwRWBC5vtdmIqFZd/cj/Rb3fzGTVt8sX1x1U6+2K/1DPA752foy//uT3/+269//fOvf8uu3LV/+p/+21+Ko4DGJ7/GX80Vv5rf/0/bzoEDf7f0U4Vzj0x91PH1Ofc1hpQcpJMuuMDcEl8PzYSkQJvwndG9o8Sl9m6MucJkvFZPrnUIxTLKpSLra4zH4eu9m8EwHPs8HB9enFdEJrcTW1j+Kb+Tfvwa3qucbffR+9dCJyxrCOXDc5uARldrg3umknsUSz8YG8XINxp6ytI5Xjx/IqgYVp8H8mbPj5v9DCvGByIPYvDJ90XgzqEConqDk0f0yIfwtR+8Ic8jz6Yj7l3B1alkily++O6SIJ39qbzWcV8ue4XSM3syjXyszhevrM++pQzwIUoe8frGrJazARicey3NIQmE/5BARd3q7VFbXJR65Yfijr+bqNp0z6rlAIbIo7wQCsHzVBgorX/QLLQz+ED4rlp61GHuCTUSdVhKT6kK82xY/w4LUO59GpjLVweF9RF6s7j6WZ9xfz9bY9o9DUgsq6JHdPeWcjliEEuP0Y05RmeGfzyC+wH/yJMO0dOl2MvnnwIPl4uJR89WRfqiSwU/Ho+moH5ggsp3tvET9cPrV1yAmwftkOA8ltF/nmJ1O9gBPI/d8r7CUYs3UpLnHz9bHoNtjliFdZrvff0cFGuUNTJ0SAW+zFjDj9mVU64RSBe9x17y16GBTia/fXTlOScgdVL2nig8wmeNpw9P4Yjnc3gG3z0BFmdz5DE4RF+P/nB4bOLeEaoXGWLsdapCSLoq+HDXzwoepOCiVgFGbDFlNQ9Sj3oWBRkpjFG5iVi6M29gs/VMFcv0WqdZG3nZZaFxd5n2etMXoWqENk6JslC0hkTPYJJV3fsCocNzSldN23Vv+BslAngyR2h9QalLuCRGh7Z5LmtreDQ1R/FAPB2nH9Fp+wpQF/lcYuepLvIraJZ/S5aJcKxkbtx3PBk61b/OA/VvvksLtB8/nySwQP7S1o4UAPkoVWIeuXOAJIjyk7AkSlwojgIYfNUlGXoWnneKXR4cg+UcpXk/5hNPclEkwa90AN02QYcVLzzFi1unryw2MRunO5NEQ1UfYiUA6negHQBi5on8xjP5jZYh13L8VpeaD/myNDsE5G0epzcGAsSBEQ4thLMkYtVkHC+e3CPy7ah73ULGpuJdnGLVbPwwOn8EhvMKcBrZmEG8/Jp+35Dxq5g8VJXTeIqQ6nkiBnVK1UjOk90Y021VW1OQ4ZCwXOKcSO9gU9H0ncJlJ9WSW/x63UZ0gTxDSvEYMKusQ2hMwQUxlOepHtLwslqauWYNkqpkqaSg8u2XfVXveAE4CWluqusIhJvwNeXtd+YingPHq7eCDKjgCc3/dfkevunixzfDgAPjanJbdUBndhfpYuGwSgi7WL8m8Iyehi64577GZ25TK4oZc8NUsFhTlDaiUqDvLQ27UqmgNiH0bvnq0xvaueh4ASnoNjegW9AdcPBjazMRgsCTsxPebk1KSEB3K0L5EIRq2UgIxPnYD+t+t6mJEDhPrFP859/TQ1m+D/blHcT9yL51enXr8pmoXuQvUZi+prSBmj60jKyIAh5qvIO8hc9/A8glnquLqQQNLKszCZSICY2FUEFFGVqWyNSZOIQAiStH5MN7gp/YwNAhziKwoHWPIupmjgA0Rx+8EW2h0hlQHThKXGqJOHngF6NOfQhWf3DQNtwv86Gb6D7LfRTcd1nugyCUVRdIQn5ny9PDoVgzDEVTkgpGsIHx0PdlIl4OcEVC4NXZAq/uxYAkKAEfMMqBBbfvMz01HWndOEdV5ZFtavIZQpJ5ivvt/U6NVVd7PAR6HNXK11nVLLc5GJrf77viG7pHPZDgKJlfPRwWfZUwTxBJTpc815oNz0Koihk5WhVInAMpDhCcA8kuvzPcrw4oh/fwGFNcWsWzYahf8Gqo6aU5i+52PPC9S0hkMFCpQxRw4hfru8iZodf33DR1DgYf0VIFa7+tCJiKpppVnulzMju8S1MAF/LzMVde9Q5hLziug9he1TyRaOKXl8ozgZORzTn0aCEjOAU75QDe4ZaqPrhIsRq566wYm4aL+gxyEu2dpkYgnszvGt93amLlRQP4vLA8B7o81i/2Mey/QjWzxaw/UTY/V7tBe/bzwUyVQP5M2SwVhVC9dFTPbAQuvcER4S7+WBIR2GgGw15UfjwUCjaGs3cO5ljkr/l6+/MvQI0aFRPa6qf817u/Zg4ER/mttccoACWgOcjn0d64DEGbAQGp/jgWIl7lyppzfZffIwiHqLJ9sfQCsS6q6zZEBG7QAua8Nk61h/jMEZm+ypBFuK5J+2eTu3psiPWFIVVIAckQJDGy8iiu05dLSY2KpyOQ90HRgbkqz9TAh/ZhfsB/rhUH4fujhFSTgLFArlQFcjrXaVTMcXiPF8zDofCPvGx8qafFikOl76hWncvWU88kC+Ub5NX+PMfmS0fpBm7I7za5geQZHV5X+vn17dVJKBL6vX4rTRbq93DfPwlFyMPi3KMJcdzWr+7ziB8+H34YAGsZCW8T+AHgxZv/WEBDZYu00SuCztisvFs/QFxs2MIeG9RcQAHfkWTez7Oo6qKeW416eSigWbun9hklCD7gLJ0wECfzZMPbfe3/deOMt6A4gymFvoTmirAqak07zlbfQWH53F3w4bCbIkr6VIib2DVrHZ28j0KiKrpn9JDxmKBfQ7zDg1BO/E6CwTMQDTjsFrCgbYq6QabTZo4R6Vo+JAPFy/CtkWfU0gNIv1QQww0yTA/NPucnsPdC26wvMCW/F6D5ZSSXxm8tzrdYIhR7wfgofIuVdYNy43wx62RaNpCZzyic9DiHmsxfeZ1sxl1GmAQ5bDkpEjskATokPUCzfdq5fZPyeNLUbJrXRx1NfUxByo11K3AhAyL9HkxQCYGRzcaZbEABSIy+4OlqUgO+q8gcTu+ouweusQmTeKCyQ/4sGBnvYGyQFDxvWmrTswlVp7R/3+/5OajGR+pfVT3+HXbUxbw35kAHrWxpNOkUDFZkHUORIVYoabA1AgHbS/c890I8bkmHv/B3Onv2kQkMdZ3UkoGkGTdn1jFlK3Y6J27FHoLLm79GPN18ixAWx0ef6fVKyJRPzOAXvU5esNO8rkU5ZEZrRhRK4pcVvFHg66S8q2tqq5mOOoKilem71gDbbY64iuU4Rmz50uHAzw0OfisUCHsEh/wOLUIK+EkoN8yxS2RYkrJAbq082EmhLyDOfwZ4Ai1+M7C9hSN+IC3ccPRr/doTypL5baGsQOlkCJT962OqKL2zCQXPHlFlrKIYJwqTpHPHdMxEmoy8Jt4nFEk8UBFJZb55XMo0pXGZPEr2FMoewVD484+KXMJnCHktdZ1I0aBJQGVpGj2F4xqDsQxCo8TIblqVsAhTxnm5xrww3FQemifhz11/KrArop1AZK9PJXTh0sPQE44oOaNXGBGta4TTSyMiQWV60sgU9G0jGiDIY448gItPo4YFhH6+5HbkXNXMGw1QpYKOve0L00pTxs5BcbHINAVKHPi7JUeE1ym3b1NJe8v82zC7pZq+fcfwy+Xrw1jMQ105QSYf1xBialTPwLUyoE6Z3YzQCf/580HzkMrXWQ+d4IcBqXAM/Jywam0KSRG5Q4kDpGSg+gV8gLO/FJNmSkEZO9SgIJWAfjHQKPBhXfxTDKVOSZ271B8/ybR4aToThQYtMIksTnz25rWDWIN76/4jbTc18YdcGRAcXnzuF2zWX1cyT3QFvAryzZAnFA8R551aeslYX/4o4pw7cTqPZLvrvEu5qrN4xuSQM6K45yso7SOkt9C+cY5wiEoAxAJvp2aqXa5Bagj1YNB7grSEuttgqdew0KlgjBuvNJocgUSgm3KsWR+vXF2lg48XmGlAIm9w2gRXA8BK5iQ0ONqlGN55YNtTXls9WbfZdU19GNoCoKw6BEmGr0OACzTimIE4NQvzjm4belDvcAGccD7/Y3puKLE47JkfIiuq2zC7hUdYw7bNxWvctZZ75n6g4x5f82jguWWEtRUESRk/TufovMzflODBPkoZPNGRy5h+mvn+Smlw7ppJPXbsshQNXusoQN2dZ+J6wHaU2ZwoJmSgr13DhXYXuaLlAoDaYU0HXDM1zZcgIDq3h1jtBBgzH8VFvo8qSTll9f55+fNmC/kH8MnQiAKuZbKuYsLKJgNxUcyTTlCK8Z1EXs+9TDTDO4fI5UkvkwpVMDL9WH1sIAVD2+BdDQBPpgM7xAlXiwgaSGlYTKVL+5VDJ+OHAAe0SGXOXu7OmEo/120t8cRxfmrkmmkHbAupQ7Iv25TEVUyZqWTKmFJ96xK1oGnLXjB59U0lp3PJE7WTsRaM9Qi2EKldW0Fk70JUrzA2Ed5lsrDEZL5/Gfv6ejil1F0w3wEy+xW5vsmtGLZSalHOnqZKNs6+3oBgAGQ+U4DkgrqhUWoPYqoi4/Zpnb76BK+9JwRBLa8Ei3Hm4fO55z+jTKSb3UPY4gI0EEnHUC87wr6soAlG1AUYLF/Xt0AynpG3z2DoVvidFe2XoWYodbl5g8PihyIyQolQ8Pssu7drQ7i8DQFS0lSbVC9RmrqOEaIwm5IBrfKw23XHNAD5qfxWaFN0gHNg/4+qG3Xixcen3OYdrDe21ModTqFnpB40EjLH5Tnb4nd03RyjerHHsYnmue0RUeJTm488L0NxmR2aJUqXT+m1ULVQOXx8JadarieJ5FFy0T0Xm7FXc+TChxwRSrBwvPx8AJmMlnEvjx5zLGjVYADNsPA0zequgJ/SFNWn09EHLgXIDlJPK+xT3vrwPkJFlu6hsICwODgKlqhTSh5iF+s6peS9Yr9jeJRgKg+hqm66HXBI1IDCxyOhYZX7nOpjKIXu3zMBOPDAsjJggIUK+vg4nissmixZtm8ZOrGfisTOnkp+oLZtKF42My1eh9r9vK60rNkJVjbaDVzWPTu5hCUdv/NkyB2i8695LaTDjJ2eKREHUkWMu4manvWSfO56ikFizywNMWHva7Zq+XBnCFEUqXxnDYR0EoOSm1o0gONBKHfPygztjA/m8cWqNmJZSNhsywLdXAggmdUILiOOQPCJ8C3EPjUP/oCczN5eGQaSQczapjnCQ7rml5R52d6tVD4SQHshxMS9e3vhBXndNGFn6cWNKFcDvziv8W+K/vA4/+Byn7RuEtSlRZqpdh+ysHWG+1iah0qr3PeMqos+0ziEeD3XJazx5JtnHDTyeTK1en6IUcopxUGt2qQgsaIcrYRWAeRaNVhN6lLZZ5CYddcr8lc8rRZOLru6B50aWh14O5uzEFK9yaxopceYXQpCtowVj80qvi+HVdmKJcuLS0JVHchGYHD9TagbTRd04sAZ5tvnKNhRO2vdKVX/ST8POpYABgYilT8o6juIanjqzjAUlPuT9dkw+uhNtpFRZFcGAf8G1tPp+MP+vgxQh1UezsP7kdcqJwnccghnlBFinwqQFGY5qy80auzsAjzYS0hfWEqmpR5z6Lo+zWtsb2typAJ4cOQsPr4WsmjAmyJxFldt7SiQxaYP4FSJQpEu82SSSTkPjY1nUaCvh4uZB53E5JklPkShHJRG22gIEsa3DZyNEyd1G79a+1v8MhvhdDD082usAuYU8ebBBkz3HJj+8c6qgyug0OsGU4YNONt3+OkUILIHW4z2fnPpR2PABEUJWr3NUyEpY/A2sxM76W/aaOqMAvmw5bzkQkREuCLcoQJTEfFtEzxKpGBEJLs0ca5htNKz7dB6h/KfQk4sDH1oyZn8JPA03VQtQtWf6TtVADx57Ygmh+qsCFx7Ottk2qqW/EFujQ96NYja2vaOkYqBKVmRpSqGJ+Jcu/kMHkCFK1aTIHcmnYbXK33/t2kffzKliUHSNkUYhqYnD9vV+riEae/zGcrmFXOFR2s1Cl3H0xoCdgDezDS6bkSz2Uf0EexhqqD1OqOBjx4tizaHXNJQQ2nj3BV93V1Op426S22JJ+nyatpdpsckJRGwJZWeXqLghrk0d9ZaJoLgU4cmZdt+9NTEZkGsw5HIwGMGFD4iWVk7GMKszDMkF+5inQ96rqt5MkBFaRObyP5eurTJRSh5MCtXESj5VYq0Jr1i1YJ1zIftDBOmPRtEIAXvjjtyh9JHFGu/K6Cc5n2VevvMspJ0pQKajW1xFEFLW5FOUSELFIxZ6AohHHX3ATYtsJgylaHurWsU323vp5h/9lwkrXdY1wvaNAenkSXcvS9VuOQ9btwlhJMCqtTDLuIUU2/TzjKZeitkPM6uLjPJM3pO30tDzLQFdtNIWqdc2WMEYe8zWI4pA4JlpcQu79IDlhrK5a3p+VMb43GFEylZqTdDP/ylht84pXVOyvsn61jiFcgUqJ1seSWqDMaPe2N9ti2tCJIH+Ma3GxFVXdi1uwkR/5jfJo3VURnb1NwbOrFFNOYHwpA4TIar6py7kJMrTPUiDrNg6VjcdJKE7esUru1XDN48/lc/gQ/MpKLDdCGdobhErGhT/co3JTRbJqw7WiY0DrpHUEJzQEuJLFtW4u49TEODAP+eYMaZSNLUWg7A0ZG9Tc5Q52JRlkc8+1EX1REozrulsN61S7HJyG5o9Q5E4MWBFa0mrVaajkjlnMF7Ji8YQoSEjRhyu1YAPmUSdD31M8VeSPMAlmi+Ow7tlVcNbyXpqzwijMxTVHzQWtwJbNCJu8Yy96m3TbmLIeStJiun4FwyAKpoGetjk1cgJA1wXV/wjDA27rSoXdmBzO8z6IG0Plb766GDeFWz4sQ+AQfP73Qcb7YgRy3o+b9615RbcgaGkHsUdVPySme5ole29eyhwzxFGQ/PJqFqP0V8hFA2PSt9F4GFbSEhu7blQoZ/2vj+pg8FyWzO5RasfY1JK0w0EMkPIvYCThMyn3eS6AOxYdIarBNqkI+w/xc7TDgfuwzs7VK8GdheLe0uCtJng23Zd2rprTkEpXgOFb7Axz2r5V37MOjnL5+tTaWc1j67MUI55jFRxoMhEN/nmLNY9iXfdE1U/m1QuVzUy6JXlIRmRj6kqygP5HCDAr3jH2K0+k6D14NhsHDZaMMnzaxLEhhf+EH3tMFMP9fn/lrVMF9nbd3n5yLLG8DYxouxPhI8MDE/e2V8nZkXyxh5NE6VmeOIlcujnVXzd8/OceuMChsm+CRN63pkRa32rtJ10dU0cBi1deJ7zSUuPEZc+Jo5ggGd9iAeJI0YyDzlsgWaWkOgqVRXiODUhzTRazqJW0j9shzxFqgykKoTBxPe47oE8fBwz+Trit5LI7cqubUwNOmefdFZ7xt+/BTzQmeXC07YKbZx0vojP8OrrhsPui5r9qiZlR+cYVLdiLlNakOzIYY4ktaJCwElACfgK80rudNT+peheflWkmKkHRx6l5ZSNd/wya+HF0rEvOG6kg8Jkog+rB08mNLYzKUDmMErU+MgbyRVU2Coa+GWaThrXTge8KattwlH+sas39rqrjNS2QM1QAYf+ZZEY91iBWYJyOwWeCjAXrv7dZ5A2deo5uDKpjPwYXV2vvb8OzOXen/dbYy1S8r+ZfmxdNaF2DOtRwg6r/RJPBOFPKOKcaFksHOtEtly05CsEHHbriNRl+djLPtNYg0++YTosyJ6ncXuGnwlwUlT1J4o1seyW30FHqaB++DKXdta2/xX1gQwFor0tTVRDrnUWorNR5RS7hkS4GKs3VPELtwc1RKiQJ9UBytF2s3lyvQqjDKEqSixe0uPPz+hGhTHVZ4fdONwWkG9NxMGD9KHn4UTqOTd0szBzVheYDEHR08Ri1m8yDK1UfJhrZQJSJmqYwFrLWUsFFwY6XMApLBDjrzbNYP9wcqgIFj0rzcWV44vHePJOfb8Yc+en4MMnTaoPcawb5zW8Z7r4lOPt+dHikG0qylH+T6bcwZRmzLrMi0wJJEO0CpuWISQWiQd9GB5A5bb/FaMtL3fcgsKe9kWoC03s9cHeazr3INL72NDVV3CsI2rY4QoindFFdMc20eEF3j62aKJ/8J+jCz4AdljDzzJowNfz0+YzY6kT9kfqzxiQxw8NAb3XW6dqgdwqQsnrsK8S8Izlrp0+7wXetOoQYTTteVDPwHUChLsmVRAART1YDmQ9e06k99vUzPziU3vSbBnvk57ZozDlt2mEaFMcUQVn+C3jQiS1DTbFFNErRypwn1apFPQrlxC2Z0srZfwjGDX62WYZeuTPeIUnrDEuSft8D1vc0nM388jtIRbZa1AjjC4ryy/7yvKke7odNOWjDwjrljJisJI1pPBS+YrEuJhVzvqIRRApsJCBKfp8docKBRgRZuEw7q750nXaPpvMaBe0n5Mh0KhFnjyaExJhcBSIx7hC2eJG68TDz+Oh7KJ28VtySUIbMU63dEgK4e+CCM3ODV9fsjb4/MAp92nH3znPTL79iqqIf0gOgQz7Z5pb/f0mpGFXpTliti7brC0guZRYcbEwKEQfV10JvdckyaSUoqGlMPwx8ezaH8IlSvBfdRlBpOP9F7DOOnffQKUOFcNBwuTHvKI0pbcQ+sAtODJq8caYcU1JFaeyuu+y1sfs0jLzaNm8GfpHTxcRwVmFmI2botKHIhlJYWIlUzX7hxdwI/uWcDHg1lWHWfwCZ+XHWAgFfhxEO9E/e4Byfmyn01LllRhdAw84TftyknQ/bOO59oSbWIJBLprTOWq657QqRFwGU0Cw1EDRHcEX0w8pUNvb4jDX1o9Hln3Ge9aLPc85ZzZZZIW69R7BvhoMvUi8DToE42lIF3YSv14Qg1ARmZHrrMaVN/mr5wAq5jrJEdJPDCwmj3N0Iwx/hq3popha8YNBA8yNUtyUwRV8nL5rTB7tX26gLNQt1aUB15Bk1hj+2i0BVmcO6h1HknCXH5GfyrGEfyw4xSXuNvkWNKnNlkyXOcnTLU7DSyFrzmvR7pNLKVvOLCyrTBSmv6eHvkdU4/U0JDSO6r9+6pEdFyuQ6xSRKkNGY418eg9QsHxpx9ZpBHeO/Jxxpc5NxeUCjKGhCXUwVcv2otd7KvHXT4U6SDgjoP+KjTYqbC4V81tPC+6Shnp+KlPGx8kry1X9bY8ng4Yzy2ICmZMExDmn3vzvIBjqaKR10GGx6bWuXgUzLx8HSDgV5xMKebCLow9kd9LBEUXTSIKVXBjgAteq0miSHBwZnLOTBWzpogZuCQzUWbhtMzVCt01A6KTaGaPSVQ0JTb+irvEzVaSNjiFeULuSqq/glSMmk30LlqL2WdjpMOD/2wIYQMp++YmuaWwhdTRBLwBmrqqEHiz80DkkOLmGEZVImAjcn9QA1tlqbIEhyevk1CdDy5CkM2rpOmjgp16DJ5T9iSaWAZD1EjiM025Fn2/GeoEW6jnfc4l4lvYkRl73YK68XhoHTfViK2klN7FIj+Xa+4ncOnJ9Dd1XZS+lunH6iA4DT6WNGWg8S6DaqgOROzOBl0G5ZEONAhyfCr7dWA53QNpL8UiBVJl5qBIPKbBFhLxHCQyslpAinKU2dNlTKmrWiqVRyarWruYoVK7r4u3FUzx5lTWGGV4GLaVfcPhUztELkM9O4bo4tjf1ERBQWv3qZnRfw6nyAduWj2LewjVkZNX0GovnGoQcKNeFrAMEwQgqttVmAv3asqD+O2My+fh9abi9IeQy+3YUcr2fiWCAFZGYbc5+7yYydW+K8tNI6xKe7JNqVwx/AWGCUeFiUNwqP9S0/vYQu47YJlku5e6CZRkvwISO/cIBwsNJDUW/rpdNL4/mZ+GBIpcxL4TQe238lNBpuKWP1VRwgjx91PY0uqT1psVrQmxNM7QkgpOuM0x0ETSYSpGhbtn4xmeKswqTx2MJU0JO23l3k7lozW6kWq95dgvkXkz8k0ntU0hLk05KUj3sq2jOPcuMlSctrV2Wk7bq+WIiKVyxcEyxqE46/ECT4/8LWTuRp1YBCClZ4V6SarCYmDZd64t524Ts7nJmkIaua+oYw7NqbPd7A+lLct1jILyplwtD8xjgLosZAwDF9g0OLQvUpmgMCM1jMB1uOl5F6WqA9gy7DcwqdVVOHMg5lKntaezdUnH59MuMtLL7UOcQ7y4zAI9Pvs83fTYMz2FkMNdF0n3+vQ3YgbR2URncvtCR+7st+i9yelg7dQbCuP1SMJqdbexFrBYHR9B6jWF40PB4QIWJJKV8+kq9KHMS0KsHbWaItx9PAjgpNvIE1ktS6sAyxeZVVY4UZ4Sr8WzL02nZY3FVMdWCyKd+eEA4f58KhsIDQqT2Y/WiY6Pi5CFfYDiUjI+RLE7xGPREwRQOMaI5uXU+3aSnQflw1O0MuMLUslCKM6jrTk4BYrcVfNUoq/UTLI4k0oOM3eD68h+SEe0ZIFpKrSD7aQEn8QlRF/p+V+b73k4FC/k4FqtQhTY/89LH0wXMjLLI6I39KPSVDZQrglSGLTNDoE6DTlkTLwCcOEoYUGHkihswRl/dTYIwKzW87Oi0QIx2g+xwAjFw3ZWQe11LFHgcyIhIDABIRfI4UA+4kDmbA3H0Llqr0l9pOEshPyEzE+f3ETKJ+N1UEUFVGvxmyZVjVVDIYkk9FXtU9fHkS81mVtQ1+PTB7oWG3/t0LjiQiTDdHf8wJ+BU8gF8BjM21dE7/pOEGW/eo2o3SbN0zRch1Dwhq9jBMpYAmfP+5ZGUws02catGWVFL1RvlLzJhxSWS9QfN/oCI3Ywan1oJ2XKOykdIaxieFIE7UgT/UP0yyWg6AdZlSrGBxlSgmZ7Q2Qq3FrIzFEo19Zf2CFJVfZthyZmkzJirf4ZkF9p3AU5SLah/qbXmdZ4e7AUL7nOBZrVYEXQmLBNUV6zm4Eg9ITxhx27089/qPEyiS7THagAkB1p9mXHcvZFHLcUD/R3SXHBwD4kmgtVfD9/myX5/GOaLd3pyxj76F2WFyfYPV5CTxMugMtzUwhasvt+KzgS/dSAyusy0aFACHjxCczWqytB2IruBb/knEufLARCeWB6vlEinHIqPuqDx6/My8w0bCFQTG7RD8iymPQH16MCLOnQEKHKST9f2xJJmyirJ4hzyvCkJ1d0DDSkDzqw1Cq5iCec5NbxmQZ04YZmtpVAnaFRpJy4dnWCiJZCccLXVjbNpTFO2M90On7zO7yddB1UygJdNgbgIWsGbTGMnOwQSnEVSw89kv1/U4sVXpe+r+qItrt7Dgl5dHizzTfC9AmXkY1cjK6SL7dmSU+PktTciEKjCS0RkeGCBjhoYYRl9nqL6mssq5rrtCc4fDh0Zwq1o9RwE5J0alm1CaIZqghqVOUAS8AuFXKflEFiSenqpIVXBF6BxGmE7GLpPFyNGLyzn8AyzHXUAXgC6P1fom8Yla/K66inl4NtffjaLnB663XoFUvjLtnzT+kKfz8q15FSX6u8Pyv1NnjPtHL15iFCCVMZmq88ZkffkFjuMt9usAHpWi6A8mavPmJb6iF1bcJezqjrppuOn7rxprVTy13QhBS2ZcAMT76PY+LTWBp8v0tvAW+CBkvAUyrn/a7TV3ZKrUUjSBqUVHIefmgVbUMX24ajIX90BytZgbTXZ0s/jb1+67qXH4HfPePbJ5yHRVb8/GPNUsNQjElTJbBaQZfoHV3SEJuSLFPXlli2klkqOIXsos4JZMptjy+YgU1PvaDkan4awra3Zo1o9z6zCIQbc8SLh5fG6tM4pcNvcRj98TCWfQHQtwuv9w9pCluFTM3tDoFekMBQ6F4liJB2kFGJetMOBnamFY5I8HHgS4/xyRKMtYeGJsgHJIopOOC6uUSJJeJ9u73noW2lkxgJhUQ+0xx3zzOuoQ1fIAQLlaFBceblYMwxoA9rEor2v5g4TyKijynwKRv159GEbYtg9aRN8gVqKXieP1qOTj3/V4kZzTlqNczGRhKI40120clMmEk+FPVolLwxrkc9dB2rkrsaPZKNimnykCilYC61Adba2WKCMHWEb6X+Pq5T0eYzLE29y2Q3Ibbfhu8i9qk8pEvirRnX3XtTQoBdyus2PrCC00J5Y8IONEGD6et9Etbb4KWU9Z/XvWgzVSvKFLVY/nG3ZtL0NWR71rGZlAMJCoBEGFbAnm2ewdhpTHmoMfJbqN98qZvYSb4823myqUI9MMokaItil9Z5HjjkFXe+Binktg3KW+zdHF8XSxKjh0xdSl08xVU+gS51xTqhaxz4GIVsWms18phEbd5DFnKiqMMjmR+Q+Q+1kfh1DPtzajyx5Gl79VqhWsslVjMZ3iB2rDAth7M4Fz8CNcIfV5ohGWIY7U1cg0MMnwg1oh1L6f7VSf4Asbylnz5F4KTFKPcsz9hlcS+RMfmij5qik9rDKbjBJxlJs3Q2B3mMBGMCz3fHPnUo2mxAA6cWyzY1RH7IBKftMopUrPZarYBsILFDoSXhp1gYA98HVoZkVkc35n69hHQhjTnjgT/8ArqkWWBqS+agIfWU4qrgvfov61QBgBZ8RJ7V4mRcTUL5yF0rgRiieMiFEoivcMPrWVM19OFpoMrnpXEfBXUJpXJU0d9vkz7whFzo9TEfJSs6g9KCFankVDZDWy45YU3gpBsuw/2nC5nrNPhcy+BCadgPabtLs/DOYmsp3VHWn9m/LIe4tsIQwQjh8hT4WrsEaNEQ+fvh3VKI8Ni6TtMia21cTGUGt8Kjlid37zhrCZTVytRUdyrXLfJnTe3D3hkc4WDRwdqUKqWSjK51LeVZBsEITYAjjzSI1L0PawnVrc0qKfT4GzHP/ty4cghYyc9XpKQhzjzZ56ScRc7sgB0jYyVSVtCyVz/G0r9aMmXc86GeFRT4OOAkYvWrcLh/oMGRifDCb7T3HDr3notfStgK0mR11G2eS1VKDRmBz12JiWQ/pnPATtzAOIG2uzeFNPxmS5R+RmYKLR/L2lCV7Gm44Et5u23dIBxpvzg2PrDUVpY38fus5p6xllIHkJpk/KKzarZPUI8wvXZ3Wa+97GYqm+0E7ipYpu8E1DxdQvGS2d8UtxO+REtbr0+tA3Qi5zpcAl3K5fZOvrnoOWsweXV2GX0YL8fnb3oJdGMuY3fEDcF5R+DA3+znYzKhAbEA7UIaiGds1OsKnsJOXCLnWSdDuToSMqJQdT2EyiOaR3ReCw+MzpojH1vO0VEkk1YUl3b5r6er7kbFxCScWgF5wRIRGUulLP9ugWL8KWvjH5D8NqTdMUQqiKoUw8/AqoUKTMflTNue2pipHnpMFeGZQJ0kCosYWktkUthStCBacPq2d32BRWXsMOaPbyc8KU9r0ZADnmwES3z+G7it8pYTMRQymDKvP1RXKJCuhuClJfN1HNbfvjqh+u7ARiyEd8iAhFRf6ndwjvxp0+3b7XRxWSgo3lIPoXbbluR2O9l2K/YBG7TIIoUJ4eQPib7I81hhKHZOoi45iQKxtx6dluYwYjLFMn512rKc1AWltVLvXmSZKl7l0J1XifWV9tdS5e2VFi9vhU5RdcU2qrxnaWAFyOdn1Qe9TX6goG9uMbHqzSgqXIIX6HLDhz79tArcJmytEtM8uE3a1Hs6tUfil3iQ8/sF3Xqc9fcrg41i63L8w0rlYh3OIfqmfWgN5UCGlE6MfcoDs0/5QrCMy4yj14znQWSJxhijvC0H99WonlIOGaBSn7F5uhhEOyi+71oIc1hObL6pYAj8wTY75egHdhgX95W9AHYqATX+UZw9OgWCM4Js/8SL26bCH97qonkPdanjt/yUmT/oMldi2ra4AeLL8Cm/1+ti1T/XvphOzVKtGzp4bYi4ACxqSSrjPdQsoemN1lEzXaxbtzgGPNgsbKfyUsf7Q043Eg3cBcEglcYf/Fv1NB0FXaZkVwa8PBpmv7WfzXEugxjKRHLUej3yincekaHM0yBy7gsHgsj3PNusKRjgO2vxuGH9pCYiUHYeDkcBNOJsHsfhpgNIx0MW08Q+eRfHLaJgapoP5/dDdMgkm0VWzppJ44hDW3O2OKfKaQaP3P3uLqBjO3V2dZTo5JMjPdQxxxVPR9hBBXyXmvl7lFIUmnkTxauWSb4W/TJD6/dijumkK6O4qpgC1JA21hiihgT5vh+1S5VyuP+a89aKhuRPazt4yi5zTsGHmmbAPutcCdilMBXQpNW63nPtyLomaKPw7BUBgYDVzKEY4DRiwxAeoIHPyglcSzH/5yIxdeBfw/P2DOlLzzfNYxW01MKm4aopej8Xv5uF5ive256KeV5bzSAqQN0UyaNrHJ+0B7oUOUjzWCMCXH2oZrUmpMVrcRaoA19nzep+msS6fo1odbdGGohTna17dFNMaTZUvUpZ6YN1DGFDNl1dx2Tyc7GDxtQpun/IKISeX5vfEcFgnL+D25a+dGggGIub9NMSM0TPImgtbwuOn1hOTj0XSQ5OpUf0irn80t1L0B+Fs2IqN2YGQiNXzHpWEuSeZl9346oaPG+m0iMADXm99M9/XIyhK2x98DEdgim2AfeRLNLEVfWcpHcmHSWIKdeQ8YUqd7lXnkeXtt95fwAzIYtMDzUfmZReR4e7rNGZiq5c1nmCp5U0q5luIe1NEY1nhBhvxXwTO+6aoWFr4TWhMXlXj1nHb8ZalivXxRXaoSg9FNFWVnh47M5Jaytxdk5cuQGh/veXdgukNjZy59jdpEZdl4JNZcyZh+ah47eVyoArji2tb5LjJ4ZqNXmqAIkSetd8RZHMj13sOMGLNbmllFrT3NzphUEQoCk6IIZqBo1eqlCZiiJayWYSrGsNhTevmURNTkYFhc/vP/AAPLU+Tg1eSNFb7vlLqQvDF6vpuZTDG07+eA1PeHG6hiC6Q8g7LmcIh8gFsR2RciSwJrAQIEIfvItAnEjYr6l+6Tv+DTh+ocN+qZqHBqMeDkOZKoGtFDc4MJJuuFRnRApGQYMiHkFHbfBtTKNr4uedwXNJgU9UKzNqA/bvZZbp1qS7huI4w2hPRSN14zId61tkO8vpxcjrWWr8LuR+oXbjd7DZUrYeql+hu4w4qJ9MImfrIghqWCQk4qbJF0sgHTEM4GzyhVYWE1tF1T+kAAOgznsqoSb2wKsVP9EL/fwUy0YiT61inDx8NXcIdEZZRatVpgAkvde0q8cE7mI3s8IsYaqGT6UtArncgYOVME2i1nHUO/u29PAwXAO3XsRHOhh+oI1Vxmf0IqphG7D0H8AWFriRbdLaIKd3BY/gzz8/igs+hP7ELzhIT+VgE47kZf+StMgL85fPT4Sh2x8lzCavztufnLf/RiwNrMaPanf2ol8nFJiGMwhNsMoySWM43XlYWTH75nVf6zb3Wd7ML7tL3XSKS5EIdZBvOvjbVB58RnVJd6lxv3YD4v97oTXzf4dDO1D/wVk7RUM6W7EAep83xHjlFOFilzBDwaZGTVvk2GFw4fZlHW3fAExpwpVW1eRXQLyOVPqbDecaCgLliAQ/0Wyg4MGQJELTRZNKzWrFCMDERhk9lika4JqNIHs6fHym7WY5q9vRdrPY/QWIo3f4rSQknGHa+VKdO4N50Fvvebakj8RbICYGGXtEj4U+bXqBlLeaTy98XJ8BCvQC88Q1dhN6zSxuXa+Fr9O2TWVQFQ8FK3S6lhXmP1qsDeA/Zt/yUwefVihf6CnvMP6GiBF5Y6OPjTHY3Ei/miGJ8/AwDtjJMCjZwETCAeGhpQY41J4gB/U6ef+bH/GjiFF/G8L8zQP51TDElj0NjCTlvCFM1ZNjEY6D1cJNw5vO8+hKyyNlpXyqjtx9bHrUkSBf0hjeQOGo7thaen1kw1rqvaIIytGgxR8O5DnsxtMncur1IvXcMrC9vMho5eIig4shYckTccNxHd68OdxUQ1DVxt6K4aDOEhXgj3czNEfMcxhC65DfyedLLceofb5Cokk6u14oEeqH4aaHQT2HNiGzdvZGhDnQFwZF0IUBLHHDcNoSCcCyL5Wr5h9XqBxTF+BWsFj+XmhbcqA9N1433ZXxogDEhumHoqHs6EMfyoM/TqBA7Umg4qDwdaxS0DBPgpmSBPFhd7cLEk3ZmjTn/dCH9Yn1QmKzzLLkSS9FfPE7D6unYSroltVSkFE7BzTR08CUoWKyqylLFYoit50hwy+FrY97Sm9MIHWgTg8CC/DsbSqjonx1Mg8pqiLDV3aUvPcHZfiCaCakEmGbpxlSHyP0cRGz+ZgWG0EgVVLsIXlqq5SYX4+5deuW4mIv69aUn3rg5twswWHD0jDlqrJXGZjhIvXaIg88BQXD+/w58HSd11inpA+6yzhGWooWvhNoLiGPhkCGVfvSU/nMmOcz1gqLxETYPZEuWYfRxWGbaxpNtVsY6X6W/aVKazMUPtWmBISX7jCm+DfdtO8kHuSuxLmua6fzBZ02pOMk1CexqAXB0/Izi7fq/twUJEC4NtCuQbYj/T4fHlP7ebeJ1WHJokVfd65JoMNYIBZQQaieDEFR3ZrlBVdObVlk+wdWcyV2UL4RYhPXOsfjt2yK+JVankjg4toqAABDBc8PhX/U3EeIcHd+QA9jLalCHMfsLzU3bR53u5GBXZq2z350xkoPsNAOHVyqGJUbYxRRY47tQ5IDr6OiKEOwULJOOWxguTRHITs3TSukL2Xo/1LGHwYlkmhB9YpJktzbjZ4Qz6BfpCgXHFrZt5GqpzKCsvFL4j1TF1Q+J3y5CMfbyl0n+tLb0hIBBYa0ZyrtTAHOzOgvzJ2QZs8oqsm8sjVZG1XIjY0RV0ZJw+cMqhcFSbkPfwCHE3xKJGJ2xjiGo4WkP6X6AoKxR4YvOzlnP4+8bCwKjsuidzI5WJjqB+YuZ6Cy8V2pFwqTqSkXHb2GePEqJgV683g4lJ2Kucep8KC1FI423PFQAHGhWXRGajqgdV4CX0CqpGJO+prcdK1ztLy6gnnNKdG5hte8xoy7I7EZqJF5/Qd1IUljbnNrtSzraOFVJWtxSUAe5HrRAxwSwbCUADYwl6iTnVIld5XtqknOuqZVmncpGTn0myIFrHDlkOJ279HYF8R30/RXTr5vdtg5r7B2CdIWSv8oa3KfjP2GroaKCwDPJHyNUMFiOjpWnOhR3WsVhHVYPAsEjWy0s7Bovt3z8srwUI879ZwNd6hK723nS5iEfu6tO4cMtomKfU1KD5KXVwBRPhnfSBrsSNJgj9k6F+7oF2rzcVxAbffAS4Qcobv4ReE5d6Q6yf5Yjjg8jH7f9Z99n5z0SBNMD+iBKOBwLokYaWx744mdu6kWmASTrDRK+pPseNMW8BLrzsESvnq0cpGGULY6if8smpcpUIZli9Qn41LNk4n081Hmu0XgPlJtBkpz3SHg0XnvD+fdkTGZLW1UzKhJkQb68Qku7/51whlAjiM/akJDZHI/Hp94vT3NTSB8mOqGYAuDX1pmja7w9TY2hj761aR3tlEFlgqvdBgaO6GAUKwtiikTIxce57zGywXMmRZ8gUSyxOkeReMdbYRhJqVJqgQlc3NYUeurv6bAYiRO7EEZ2PjVaD8HcDH82wCgFWvqG2v1Julumotik9zQ6H3rbxCsmPKhv4423ngV0MMteZpA6TV78WYy0J5xsWMW+MgNQFUgs9QA9aCRZO52z4r3iQA922cIpCuhpYoaUFEuoShNOotxPx/Km+ols56zQ1sn5EyQmjW7fwj98oHyzbX7KgvmyUlhkXKIgZWLpEJxxc2cd8bOwOZOclILp0hRVS1iVWSF4rPrNUDjQee2fHHo2uAUF8mcmAUuPtYpE+uIpZ7JOAh2p2/qPjEyPfrapzBBprENo0rC0hx8ocSZdMnjMJDN8T5rXgDMapWCB18hYKVPXSIwbkAa1xnKDShNHN37fNNCipezMI9Z2G1+OSGPee3WM4AZq21NA/IS0eS2vVWvpq/K7KaJJq68EAEXrqlCqnBoWoQcBk5+IyT+weWGMH3P/vMF0SpEtyBM61b2Te1o/JCZXFqOufUV0Ap0X/t/pQOFSXaF9cgt92rNM2IM2X/I+KbNbrbY3i6vtb2Meg7eX3lROoY9IBVmvybOroh7RU3LsugyVSDSWrCMzOKRzzhUwLM03fNsa+RcXT5L0lPHuGhVKTT86h9YHsmnYpbZcIod4Pakb+mVcNLrD2nm+Bxd5cpizcR7BDvcn5J0MVhOJQsmJ6LKTjhm2NMoQaGt48fEuO7m6suLVt73cKBv+yHD6zhVy0scgJGOPAvV/OQa1zRyTRQhUPUmO6Gua+q2UH7ABbbI2zNPiUtS0X4ECBUxAajs7B0Wp+tfziCSbkIeZnxNRlG6qUFKgNs2uVwCyEhQBJ9u6ZBpAuXvYC7IjcikZDGEFP45nsrD2dSIOy/XsdFw1k+7O9IPTSZVRT2q64yEDW3wWMaiSWVKz3esJ5LRVlXBYoLAso6bZNn7xUm6ySZO2wc+qTjUU1o8DF/7fe2uLf5Cktj3Col8aXEa4aHJtQorKaBuUMVfoLVA5h+C5OqReLh0lc2yK9bVmIU6oQ+NnEKho2SnOMiPOYyTZGXC60ZBuWmgzjia5MAGHPUHYo3wSmF0AwBr1h2HUstDMRAHoQ2lo4Q3nce3m+bxkT4fRvwxjFTQu5MFTCQTOeQjz38Pf+VSl9dWyMTTbi5Si3sCceMSrXlvBhjnWc8tpPOs+1MV36Ug1fHvP/z9qmchUUzyiIO3GRfqXRAlQpMTTipHiip1MLOjKnWcOB5yOS5Fj4jHTP2B/Za2Aq3/4JQOWRp0IOc4yaxzYyLqdU9pbGjMQogkld6l1e9UJHtJJTYTcGB0/fnIpE+oKn/XPj0w+Ff8KBT9mLQNbg8THWfBUxAUKpa1V0Xb/CzUX4+JoTHojjnXJV/6potTBAy8OuISmVC4OVjbCpHcBs0Cjw+1itia7aDR6Nvz3UIertd/a7tpOOQG38YccFNY5AgSNbzDMpU0YB4aVZ7z8rU3nIr3zhPa/OWqdGYY8t5DKDu+9GyCiunigeyahW7YuKtyBJ1znoOtIygwV5Ki04odSPgowlvG1MdhP5Rlo97AC4MWuSVzUR0CwNw779aYSll3jkAQIAspUj0KYX2EXb+HUsPe+TZtS9NIlaHnKbayGVEbt+6+xK9WS3Jrja91LgJjYixPtkfTgTNrCWRUDf2fu35TBPWN1+gd1RF8XsBPkd4DyphQzK91yILAlHFKPxKLzkIfCpbn6GB7dN4wVdYVKQUs0w3/pPKWJslCOgoqfEA9x2HqYQXl/mv0Oe7mX6WVdsFBMQXWt86xMW0k6+JyLhzChxBOnGGf2sds6ZJlUf6Fz73jcU16mfI8y/u4i8FyQPW9QjRbFrzWh3ykBYtZ11xXybSpBPALijXWKj1yUQd1sjwjFKXTeBptszlBItempc6yFRIIlr7MDhKli7tSq3ydzpqhbRthr6bTV48qcWhG2XGvqIcOR4bGKKOjawSRT/mre4c+5TVwfZtESOE9FHKc8EoVfi9E1eCgrD0f6/Y15fgxM0imLhNLnKZsAbTle2RIpma5w9f+yw4sUN7c5EX2dLrphZBwVNvbhVKxdnCM1p25Bjz/anPJh8K09eUhp15VGdz6CAAs8KmYgjYSs3QIeyN9w9CSVCKPNrJ/O/QaE2arDfQ5FxzcwA9w1qOR+SEU5b0C/5G9bpT+d3mtBQRE+EBQEv4eKhUNygxYwj8/GSqbWOHTDXTE1j03MZXw9wCOUdC0uYCshmdAVmx0K+7hngEJW866YCWEaMDR1SELxobxyh1HjPL1QSwzJPo23TifM5ktb5wjh6cEsx7Vh3AiZz/olzSFRogaIKjctYn+d/0+/Ej5flPJCI0hWyYY0fetLHoJKkeYNtgjzcR0Z3+pJ46pxWlahJHZa94hZOeN/Ye4NtLqf2sWDrtzRVN0Fw6/yYM9ixCMDtHUseoaYsIjTYmVMvtYt0Kyj1T2VCRWdJPI37QhytqWdgY8QNAUwoOx158MhpRw43S1W0cVDnVXuv57cU46joUnkulVVjmsn9hGXDp82J+0K5Tx5eOs4vXRe7due3l7/RG92uQgwEu13UlgtDyw24gUHwy9eg3tQulqTC7Ghbu2m0To+nShVvB7X6h6E4YE5KTKCRQQbx88exLxyGbj/SdG2QLzSsPvtMH954seFabv0mWh6e38K8WHN+aRmiOEbo4zk7FOIrIjgr0AgRMXaz0jgRNW5GkWS3+I8kGw7GllHTHvESkCvAhTXauUMOlllomEhegC9fDe1N5A7rW5NY6DKcA9EJOf+HMPnng4TFG0h3GHL60V7J2v+w5FbBqKi97Lx3j8mvN+URcdZN6dotfwzRa+9t/UyI5lH7vB1ASFKYFqXXghO6XdU4u5ykg5WJ0ua2YCVQW+zKoScgXdyIaUDciFZW+pwowZXp2mdh23XDHDTnfKvfN9oYvkbZ4c0aEoU/2uXvLPn4qU0IRuc3YuBLlVSAwctck6B5US4MUIXsyfPwLc6PmcNxKvMQ1TNtpORYRt3TvM9p02T1LqQilqeZohjj9YS+wMXDdT+UoYb5ppyx3ft0hEvw7meD6L6W80qs9N+VpWQWs1NAWj0tjZmM4xBTTFRPSCU4+Cy+QK0CE6mXQ3+JBRORveQJpy05g8WMuTG4qIBra8VbL5x08pzvPgROxlheWo2c4EAoum13+NNfwRLFPBXpgx31ZTiUYs6uRfWuhwxSddc9JWNgwxsKtVun0jtJq2Ip7Ssp2iXFM5oXu6qAAthNPFo6AKCVCnmPJ08erNdnJNO0znCyzmNwXTjSl36M5XT7dYgRLUfy+NxutYEHOs5I3e6Bw8lPRcG0lW18Vh/Lj7yHk2ndFAwm/29aZN8dSA2ygvC5LDnC0WspNNPtwkFEFCmhQmVG3vPAayJSKcIlMvGXCXU/fb+C4fpMqK+C64yroKmCStRBBLLaQvc/DBFWRkmwgXceLHZvO5bhmzvhZMmhiPmsfmndSd1EdnPoJ3llIFnp1/bJFnI7JK7FmNKUNZqoJXUZ0no0eUnnzksSh90vwQL1ibd1KNSuVxZ9QTSNjygBJ/9lBtIIitPPbAmcrosQf9iR2m2DGqn0Q6iWj36aPDDY6mKPOjNUZUdZtAptuNla1dJvuodiYYcizM4p/JPObAKlG8pD91rNV5v4kX8Y/jxgT+vJLRlZfGe2BjzRC/QAsG14umZMLgUuXcu7ElB81JCwLKtBOx3rtSHcDgWnZiwOSTt7zy230LtNczVRuaXMpKFnaqpVkTk+GvhaStBoSTtTEwj2SqfiFOPLVIcM58zTm3dvA+bJGcXWwKL2spQ8mxzrkRV5IVofg4PeegKHx7qGxp7EUtJtN54ztIlp6N109ACUfuHmSVhEMGumI6zLnarI1kgMclA/yGrQUGBZDLRfXNQjHFQWu3aw0FHNkivOk0h/DNzCkO/U3A+NwfyRbJ1P86GB9QX83jEdmWw4EF3d1dhlJxxtBe4rBvxeJ40gac9ROYAjVSmZE1VSRpvrHqkXHY5+dZpQedTPCcy3j20noAAvJNE30x5F11Y/qoPEiOx21+Og0gMkSjk37MNmDAQmO51xwdR9gjQxMctZ26gZqtwCM+tTDKgSfkuZthaGREPzpNiNFJ3Y5sdRwSA3EQcsoPfOAazurqmt0hOSIFKe/PyrfQW3h44aqk0k2FxdBVuvA1ge02kVlB/xumSP/rHZk/IR2Q1DAPtbNLxX6fP5gwPpx7ykI+fmE2KIjI+mQXCeROAleLiwuUtN8Cpb3gyrQAN2TjmWIf37RQlGjPPwXienT9VRcvnGwmbVY7lqsTa9XCC6NdAMcU4S21Gd+atajIoLSfdu7mbVFS00rTFREWSCFYOJ97MuPwSd3C8mw+SSb02ZylXnJIBqJRUBwj49ycXkKZrL3uIIsBEVCJYIRxjs+dqZbym32LU0rU1qlc3KRLnIw5Y4z+ECXOqBmSr9ermEp6jVo37aEArUbYXnsNd8dETzOUl/Hq+87kgVLiqnwPeV3R6Jz4VIZS4pAtWpH5S4p6PHAx1eA45kddI2tIN3b94bkpqlr1fmXLku9X0kfvIf0Ovy/l89LczD1oP6xZyU6uREespQ6fQErJoIrankhxvFVG7ZIdLCPGVaT9EjHOQro6w+Jetn6DghnQ2zwp0v4nVGF3k819Jd43FZjX4FT+Wj+W9OPxKttNyegxboxpElerrS2VaQLUjLSWJXyaQYEwuXi4KT/dgcVEmYdK0g76U5FxP1oJ8dG5oJOQfc0gUE6jYLWWAYupV1sZwtdAlTFVntxYJcLGJ8rjq1Aoen7eNHgjp+Q6NadDGl4hkvSBgOtq0aI2X4wwqsbfBDOMiHH6eE7CRJy+bln6qh7SEJAP8dHFm+Z1iqBfHveeWplFiwEo0Foi38HlaYN4DUY2T1AsL4mNBogf2OLKDO57MNkoxchDBY2jHJItChG1LKEOxRYJoQ6i/hLKtkg3KKyFG7OGVysYSsWy4B6anphW6XG/zr4btI6nlQkcmtd/R4qlKVBIsyLEiMKDZ+2zHoxQcAmuol9ATH84IWq4wHPshQ0mz4Z/04swPd4qL+rXg3502UFZB/D1ON2EJjvtvXxT5zxCdfFNBWiaS7q8Nj5m7LXbcum6YgpBHrEYiJadbbtNvGIaKmVS243uVJyIlQ5QskPOnYLZ7WBsoURjIElEa9GEGY9YcAalRp+W1Cj6OMdZ6AxOoTHFUOhC51tEVSIUdEa9LEQzxcVh28l02HYfM0cC0k3jkTTT8NvXkFeo9tNklLL2J/xmh0B+rY/WAkUDGmF//oticsaydJwDpjX2L6oY52g/3NmSFIngJ9eF3NwtU9bqsS7IzYIc3YYxCz6Dpl1l1gzIsO6J4MVdgJIn5KUiLh2VXTi423N+9PmgYl9ybCauUMDLV10dNLqvMedwlFBuM7ZWiOwizTv55Hr+KSerLiECbMapYcFVBbKNFlU7co2QcMKauhfd5FS5tLfLcMac3KkvguO95fgk8hJ8n8Yhy0nM5EAPSVyxQwJbR6QGe32KfB1fnPCY1feWycqxIrmBafp7zRh5mGIMKXEiKzlffJTQHb/5LfNv9jcs5aOumyefbvoL0nzR719rTr+WorMqiBK4owb0FjNYpCA0TAvCgzrbt6ubxOALpYrlynJlna/ik2dr+QSBBC6jHtIA0SVjBumXqn0rLObb2EEUIK8WnBGFgYVAPrK9EUosbxpzs1RNR74lqiPp520ugPrn+47ySwtCpabXpXM9fBQIengUfRvfSPoqgjytmxISNVYpbblEG5U8/VYC8Uc84Oqm/caUnRuKSe+teFx9eP2QtxjXeUr+FP1f4vJi1SykD/zxymq+T1ED/3jeffyPF7kXumaW7KfDOAk37WfJfzW36/ZdcuJSbagSJ6x/YmWHeA2xQdxzfhtcZ9OAEFUd4Mi0i80uZ4oqgS/zqWFrsumFVccv84O4ixc0vT5l+p6m1C+9n2OAVMiXisf+hBjzdrkJBgXkI6Dw8RR4sqXbaOylPd4h9cz6ilYX5S7t7NUUocA2RQBDkwbaaqi1zINvWUDOWxTOu6inNN603GbR5/WiQjuFoI8CdY7WhU1JmXbMvfiNBNY3RAxXWNyHeBoGvrHXYn+Hax/wmlZEQJeH8mTBazypgkvbH5/dHv3mee061QbiZVJ9b1V6iZ/OLXGrrE22nKtHOMun+KbFpKAn90gzLxL1TG+hvrsoetVDKSRhMYEDv+p5E05oW48kma9P+hEOa7Q+1zrV0yKXFLFnk0ckQUHAtse+n5YtlQaWrksZEZxnfZrqmkyR6GBk/eKZgOtRAiS4Il3xFpbnxB7wNp7q3u9yiChtQ9e9PKQ0zz9F34wwfs053dG4cUkMp9akQPH03oEMeNAX81CsAOs1jcCYJ+3s5gn4wrd8AmlN8EwG+sKZVPoBMctup2TlYTOhuue1aNV718RIlE40E9WaNcFfuWsD+UoJq4ckKqYlYskGQTFV1EEy31j/fR3Nq+xoQkRpTMQgUOS8ZJr2mkqecnlzI3Hsg+plOWrALkyTS6AL6zNunUsrA2WHDA5uLj8WV3TQoZN4GisF92x2xMKwlAKpP9hH8jsR2DGunhbPxGgqjQAhhZb4aD6GUne6Si80H3oqJxLOP6yq/ktxyrtNeaVlCpIcZLwqmofayqMpZmbjB7ZmP5mWAyLBxl5DuGiWh5i1dCduUQ8+Qhye0UEOVHhpipuUNsGGEIKteuGoeW/dTzvV/KSGCP3Owhv549mCdaA5CyszZhJAtyFi6BfEz+wV/BQWGU2Hn68n4ZV4BJyZC1IHbnGrL6TPjbU5CCxznj/kZFTNxJDz4hRnQZBM4hbmZJpln0zGCqdnMonZAElxF2lIfP4bIBC89yUMpf32iIghjCTpGn2xX/8XgsbRGkWEvJZrzZ3Pw01Oyxh5gRocKpGzXrYS67bKIb0/wCOF77OW9cIfRrwMcBicb9bMx3X5K4uj28RjlaN04Y9zKePbkByFRKzF5bbFZq0eqCuc10+GNAhpofH89y5g3eZPjwUISg+pDxkiaqnv5nEjlufnJGQi6WoMqm+85ZRSQzSjUO0GJ36qckOQMeuAmmXacbYOSnaEjA7EzsBxGTl2ERzo4XSy+0Too27HL3rLR+ZIuUyh96KB/w+mXD6GGiFim426G5CksYYqcH6W/YG8YZvRE2wrB5COmOcYs3yVYHDQsvfGkJNlNB5ACh4GiLs7KI7De5h/Mtd4dYUzqgrmY7aOfpa0p5PdOCRFHLevvH6wCOc+KV5AQnbVRpkMK1GpxVJwgVVuJ7ICCZ89u399BEfiAPY/uz5dsn61JkaBWMd++C6zC+V7unhSJuslJfeCokw4CXG4TAQabLNYYhzsJV43WHBTsEhGW+M4fpgyT808xiFH0AwrzNnSLIcVPFWmD/ePTuy5GNyFtoql5r9gKgLJG1+fEjVIP+xMRlMtSFKB7/lwQQYb2uKRxTciOGVLXnM55wtQDHDA2uAcirrN3OrmIZbJI4feqCXRAfQmrY8xRxHBUgefpoy/dpVPEx1+G99OKlF0SXrVGErfX1OsxzN96lTp3DdRhKinFGpOHHNtqrgV19eq7vNvpjW2Olrlmyj3TgCvhVuiqRF2NgwKuP7J47A4TkWo9dI41VK5ND4qVbOjq1UZssAzQuW4BVvlOW+zMHDQKi2rEQFEkjg23ZkLJEmDAbItDn8kEMTvLpSXQLLUhoiylhHFcgjwoKTxGwG/B59ThLoZm2QbG1QPjfQdpY7FHJMF+3cGHGrLV3tXWT+5aMMwfV3JKIx3aBK4HtCf+rPyoJPtIWQ2Zrd7AHgvBoL0GVj6ULhYbHnxayhxuT96lLy+XcKCpc99hXmAZvf9hcLugWVBrjTCeQ5dhgDgnGthKHSZL3vVb7rj2YBSgtAmJS0orbF8uCUsaMtql+RrrlPYDzeNDo2Kz93V9VNKLXsqwAdRztJNspIlZ0BzKJApUkBvKy3O3imO7mC1tulkXWikKtKpN9V/r1/mEtN8Y6VXf4T1iw30XQpd0vR0gkk9ZoUuCjl59QhmOzTzfT1hZSmTk0sia0FZexw2VcG29W6JVvbqZhtbc9RAKEFwbCYuUbOKIY60q1lMMvAJA7QXHOVF9q8upOiXcZ4QN8DTfbbHrtF1VJMhYPYH9SLhIfYJXN55N0BsPOf5WVf9iAlnHVAV921ev8BiwMCDExhfR0DCTqPrLha/hjkuPt39vGfoNSODiP5997EvFtg0pmX2EyccaRliZLAEaTh7a1HNE+T0BqjydBYIRsC3DbxyYCszgMirYM8Y4UFyBLUyGDCcQIh0hO4DCK+qJAD7cIf6URyRhgm29eosgfUxZpfIzekuAw1Oz2HZIJwpKa7N/OVzfouFkqUHAKU8BPDGFOQjJfKpDTuSbutSS8qqTvdHlKAjcCm1O/0+ChHaZmRxSYIz3tiImZJ7mvX2k/m/ruAPbKk+7UnUgTVZNjD8/Px512iyTIW313Ud1I/58ajec3f4mZwUgp9CBbpFCowbaU26oypEcQzS3wgUxsEVKk77uOXqVKawCMMXIGI9D4k08EqmWLZNnCkVvtCDmpo/CuLmvQOd7DMV8athnmTUMpvWarCKTvr9Rz16zl46HFJeyy6gpR/cu+uD4ZF0O4R9r7UrPdPzlj3amEjqBh1QpvqW01fC2GwBrxjeAGcqP4bKBZbhQ9/0+3gQan0LnRKw/ESsW0xPjU1794FiAomfxGpnNtf6WXS24vLcA3tgzVddB2EeQeK+Gt5ylE/XupacEvursKPztHrKtjP8VIMTFC0Q7J+cN7oO8PYJEgrF/oFN6o07qHjZr13lND3fo4ht2RqAYPJ8r/9c2ZcQpvKa7u2MKM1a5fJYq8xu7oNY3HvyY88kDDfOH4DWovlXZ0hoJohcRzEy9XgsovzLpM0CyYITYj6mGkUUQGUJPVCqLFPpuWOGuL0OJaFONkAQORYpiStXeYnOxZNupNGz0wiQ4ZzhpoOf8sO95V473TLawuxabZib/cLaTG+dEYsVk+RAqLN/r7Mhrwl8Esztr85Q5Iu+ajwR7jv84aCe5lJ8xe71KibGQQEKT7KP4IRK8H6RFLkpjfZN1qN9APsjff+bttsk76TfiqL/iuG+gZKMJpJS4u0HaCU+Mu+6aSubKK+Q1S9/6P0UGc0XaZtnX3Ue73nw5a2jgkJxSevohZLcdBqY92lv+rXOWAXUD0m3tzLEbMBaz7iWKisfyumeR4FV4ZtBVKoHZyttrh/xwyAOqnRIWNf4cMw83tYSUIFi6xVN73kQRD3roZByj5fH4jRAFweMDF3HTAK4PpMyq1pkWSms0IHXwlz0iQ/zHta7Q1wV112Pv2YrF4MAD9HfNvWWtqHOJ3xHjaviO9f4di2FrLHtVBuFwQ4shl4vlUC9gFfme+dmKIe3N10terjolVPnG4D0QAd9enD4Im1SGx6lvGRbgOm7mvEEkf5p/gCo538FSytP4FsX5vmP1GOUUlslTNhEEB6JPFi8dZPr4W38jP6U/PRNSyApwOATd8YeOOHaJW0xCYiwYSqYMoqqR2BiirsoBqh5d7in9V9yLZIpd2nRUAHoWUTnAUZhFkmSmXVxnn/+KKvkXaZWtUy1vAsygYskuMfP5z8U13NLNAE3Nrh5YsIU1zR8CDpWVfbrPr7WCeSBzcWlxEdhZMApj0ss783nFKhI8VykoxZJIN/kg055cPsuK/Xvpx3fTq2GV0smvaaJ2J5zzMW6BmphxNY1JNNp56xyTg9yhdK3PJFxUjtXlXT+mWweto134MHH/OCOU/xis2L6PPsDlYLFUChYGPPYIHppSqNbKeONWMOaifwOPECqBYzorrJusCFbrCYVWof9BbTmJHpI1yIV6gG6XT+fL2h0wLbeKSRpznM8FFCc0j0zj1mCVCCdx2s8XecNM7QYdBnK7Cd4ZMLW1I0UxGo+42yTXa5OKofF5BZLnzfMhacpssdsx/CKVBjsf9uTJCB/mii4r6ZGSKfVgIp2Lv5OO8IlkYJJM4XqxJ4B7A58j/K97TOehghLpYNpx0gmh9JuGqI0ZNc4ZdCVy5V+MZDHyJQJDIqX+Upr25GC6Wdcs1Bv58MmEzjHINKO1JKisn4dukxemZEOu/pRtGdO+Py3CkUuC7glcTLBDgqYScFvJvKyAClBUka3NFz1oEp0OpwycTHlpkFxN6vOJ9t2V019KUW+VTolh+xHDqxMzUbunBoP3iUfaQVNMFxq6tVpyyuUrk51hUOSJ5cFX7QGXh7qe3Z+fR6wPUtV5cKl4nws0VSZCwggnW9ekcIKQYHUHgOLJFkd23WBOPtQag45EaeAhVEbRx3TSg1j2eGOkX/F1Q1HPFNRAQTKczi7ROO4iitV29+omUN8DPGx0B3Y29Wi+o1K1NMivES0hHMRwfhL002TCX6jGPR4Lj+RhJGtGH80dOcA9KHTuhTLYq/c85/hJUFhYmplIA153afVnZSlEMkfJn6J5b55sJLPkQoCEz5+EnkXLu2dpgcnNu1qkfbm5qaVAUWZKGf2AQNbt6nGp0l74InmOWEbyNRsUyFTblW0FcFD7HXMoCNS+llI0uu9YZKyA+5Ua9KnHy5FQctFIRoZT0yEAAqQdxk+dQBHIRR65Jbi1hQE7W/aSVSjR0m1STlldFL55q4CukrDtgXs9fUfbxdoxqMFizQAPlT6oPgnSJkYjgwxsyLQISQjhrw398icWhMn3pCUfrbslHUAsnlU5Oj1bAHxkEc5VHkurfcZaRwX6SDHL13TC+8YtYDsbAiNM9inporX9Psop8+IKIXPmQdExI2nvSleMqKlSRcLp270d3a9A9xOV7o29x0vsIhdXCEOY2wRCw43i9sE+ac2pZq3vLNOznvoICJHd+MucjYaIPDy5FH0B7ZW9rKQDVUKaXh+yAB03wFAL5SywQgpE2g7dcm+D6PLQodVNoBk9/niJCD6IZOTr2tObVSlmATT84huD62Cemf3K3/G7KbFGEm9eYPuz/0SG7oaywQEOivNpKjLq0jiwbeBGz7H+2xMbNm7SMSdbkoKlBf7+4XJzYCt/aFpk6J7n31KY2m67ORnqF7FVbzNDyfHAIaxQHCuChqDyhZLmK3hU2ouqXOonQ1l8yQwUvV6WapTIlN+1q5xcf3U5yE99hT/F2h5OIyDLI973OYQD6q9zuQRuo/ft0nCm817KniicBcqlI1sUh7QdRPqHJHI4vOPaaBl3hBXgLMcI3oMWq0/0lKth64YBD/QYnbcpgCTuO2Bh/Tt/ay8R2IYAsR/txwgNRKy3vEHOD98lkd3zQd0JnHzDyQEo3hunQM5uAVu7XMfCjMB8HxMZKkELkxwAap5MucKwyU7w3TcleWZC3Mamofde/2lXGQjXDL/DMVhgd66Jlt9/ilQ+C17+W6pJlwkqKzJDEU6ZrM3HBCe8iunCcfsxqGsi1f0p7z48ORUtW3LWtTrZvvm2MKi1rX50OemTQqm+bWBEA+R43z+KbRlXkFizmleYk3MKWVu+IbccT3ZYpnZuW3dx1tszaazDJ8gyfbM7+eUNXZN8FPlfFPxJnZgvZEwpe2n5CR3z08V6jMnoBNWOcQzw2m6aK7BlglGzAkgLKwQA1yHoADSOMfuZcovPosmeFCcbnRvaXerrAuhRjgNWs4c6V62UregBmf6xgMr+oSvTpWJDesXSFc+haMxbD0DiAZZzRRiXnkBO+S5lk+5q1xS+bLkij9dH04vkHqR0m12b1SJ9F/4RNUqpEYms3DuDE++GM70IM5B0s7UWRxqHQszEEtfNQSIShddw9k7rFYawDZX5lJm8z2vSXiEomIVkA+QubsaMqd5X/AG5Z+qwc4xl5ywnetkPHK5kIknB2KEJnztY4hWjIpcD/JzVX6Q36uq8Ppr/DTRypRPyrIVMJ2ZV+sr+/VV3Zrd4ta55ecfayyF3nTz0RYcd4LeK53dg/tG3GJsB0cXG7BGqq7vyXrCR7Du6LXYyzM1+Rr2IaMr7MkLG9mg3Lp6E+tsB9izaX9X/KGAbi7JHFJypoXd1FOYGVLpjjaAh4ByygQvLIKD0/FpC+XQku2wGSVsZTdpVonIuR0INxIxQTSms/KS2CkCJNRF2dUVZYlBsuTJMPv8AXtOAwZ/mdhf2YchpS/w1ZF5DS2avV9lawJgrsUPUsk2LoZQiY78qdyiQ565+gzUU0vfN/B2wsQy5UFygpO489QUB8x1Fq8AD+zI62citEC+ZOdCC8qge95BTjyUT7vZe3eN+Qs0FyZgEx1WhpxLFIjzGYhj28X2KJ3oFVMs5ZtZ/MOn4dmeFtfgQkdgm+6YreIzBFdQBjH3I7qAoU/I8/9WcAvCuPOzyytwjtRMXO/9ut2xiJHApV0RJEjbtSUUtrxgK5yACGK9dE5WNkOizEA079lDoLd5GrghDSnftPLQkzJJaal0XZ28hy09+zysypi+2kIh24K4JHAf2OKgvfHTDCJ+2TdcPkW7iJoY9L2fLJCRys5BIMlaU0Exu9xmyFA/ENS0zJCKm75dGpmd7xOytcFxDdpWZeSwdy4hc9+kn9kz9wVFVubPPyc+jbz1Oyftfe78WMhYYsP+XOo4giKLbdHYlFxIGzntMKEEHB45OxTDVLHhQ1QlDun72lbQ6fSyyqhHpEuNBxtI4LcvkJICJvBq6pRQmUiqOCt+5pcph6BIXK2Fu0H0R+mxPXJ1yp3zbtlvcND2j7jBA7x5NH+IMsbh/oYr7m/xS1UwllQNW8GYmyPHQTtbLlPDRiMTQQJAatPDw0Rf4DWpR9v7gZJjm0ILCxHu//xTkH6VK/YYxdwd+kdjLiG7IU6euRO5Tl99ts2xqLF0JNWmRPA77qUGGlrWmfZQmOTqD+U0JYvhS3XG6qFNyomkdb9Wt+PV5pPS7ljQFYZN5TixwcAtvcwl5lfWSmCkPw7Jg7c5oN9RM9OE6ah4mi1kmFKKI+2nHI4rTwoLS95O0aBSgoYiIRluJqcChhPXOZwAjzddOLc8ArhWuHdwD8z2CUC6H9A7gBzCtHnyxQWkrXM+sQSaBNhIzWFp5P4dFlf5hvld8Lq8YoIXgNNhosdnfgMymt/V00WSBEVA8m2PCllGU49niHSxi3Q0U5KwAmceTAmo7IBdYUhVsHbeVWbqiPKP6xxPD+CLoZ+dufK6fD8L3wtK/sPqoOC1JDKOafTyL5kfxGu0VWFAlyisc/u1E6jF4I6OPBvVYnVPguZlq0tfceSnNsHlkdETaLgvT6bTK1nWCokKAGTUa26STdkc7ht16dCYMoUdTh6V+blgLhXHWietRyeyLoqrmXq6xmNS/i2cjuFsYgkx7FMBlG/pRegGlSPtAF4LHHkYnh8CKt6aLW40fBxc7ojICfrfO7WlOC9bSmwLmVmDvFZkGXCbH03UCvdbQQGR/2INEGFKqsDbccNf7JUaEELGPWif+S8FlREEHqCMo/O8l4FKFxuGL4DYa+xJ0ydflimHwDrtfv7a8ANxwoQIOMppFsdWgARKgXL8xKGHWvVy0krqK8iFMe2jwhCs+6gDToNEbU+D4jGFyVIePAM//xuqfEMvnhjJK6kPOYHQ6+qS5VM/YY4CEyECLIpI6iCDt2PAYVG9lHVeh0A1OASX1pqQm80gWxu5v8SQMCI2PSNIVNX62npL1Drz6VzPjI0MqHgmAYtIO7Fhiptn6RjuXo+lxE3gXqFK10r5CV+mAdITIIAk+D7j7cK5+UAIQCQSxeXCVlNQPnjlQq6kp2R2qCpu3sAL+lHnfBiLbPAq04zguPOgPvTlWRjDfn+Hw7KaI99+ylESUZ9TDujFpm7FJScdVTk5d2GnUDicXuLmw4qaHR8udE3c5cqMP6w71aCne0LibgrH6CxBswf4Z2aTbvO7CWssfxmK9Xz++LYzWYsgIQInDLgULqy1Pj2Vp+8/qbzuQgAvcb/jO09zGY+ACoxqWgQc5ffqRxTms39Ju4nh6ZqyQ8ZGQv4uE/KHks/1nreaFdVzKQDad3DanRX5Yhuf9xrjwba3wuJK7ZseA2Fwv0ZgscRg+Na/zbF4WL8tIL2hMwTzCkRCCg5cksgpRkvCCwdtOkjjMZQNrL8/rxWqDao2RQezHiClqbo8fahmS2byaSzo7MkGTJCVp/AxVx72aYt9EkPtml0wFQ/y9XQZOfyRPhhv4NBjMYV4Emii+ynVCApTuEJM65ocZmEJh8hzlX8qCtU5MfO0GmsKFWwwW/sUDRLwZIxtsKN0zvs0lfgQLeQP/Zq6nbYP/atlhoLsN33p5QTQ7ety0pqwzajAOCkf4AFYnuBQtPAY00mo6clqudUGkon3iC6AiVk1MXitTuE4fLea8Cil7vsOX7cf0qacbcsmy21tj44aM0XXRG2S2ra8zAmpm/0YMBwgREnlJxJ0cp7ykqK/UZDWnpqNmsCiHNjk6tkdkuqlnEoYt2EH9i6aesu+Z4AmyVvWR5nCgJJ84FG0kqN+PjNbU3XLIznEVk6+DCl08m/lXFA+c7qYqcxky1HbHkgFME8s9gE/FV7WIb7kXus6IbDXwIgPvH07XH08P3iFioce0+sfmuo8O5gfHb/ZyGpoKfaqAl/i7I+l96+Hse/43YabTv+ouMruAn1PC/JtS2hatmJg10hmhvIDZy1y6/NCZqlAbbGF3Zdp5NNTNWYKpKf7r3fHgy75wSq1z/5zO4TmiTh9gmLcd9Qes6zJUjdAPPd6r+1XibyVx+AqrhB0FsCYlh8ETkDCRYrLqCJ+MP3BKIaKIebaque5MI3e4LDHNnuZSE7zP4Dj+UTIpl4iqhMw5/rTtrUAaWS6NJOT0so1F26aYJW+DnKmVcdD47l8XK1qKGSNAKY52exg2YZzbTvgl5lE1DXifNMMHrqff2ToOdpharVRaCDdHHPnQ6zSImrUBc4oCDpsjaHhMTaghmcbqwvqqTyzoaeMOQI69wr1iMUZIkGWGmDtXgOXI1rTVu9JeFjb89/GwcO50M+6Upa4ToJuE6Q0nPlpT7Kunk3GfXDhV5m605TY5V4l2U6v7bJ4uCWuQKULTquQ6h+LXtt0wmyaFgkCjcfBC0DWtvXSxHd7XiPF0zxrJKHyQSft1PrwrCHP/pkSXgEne6AGzQv4EfriPx+2xDqQpZ9ZX5DytzPqM3bDvVpsHAU5gNCyd21MbATqb6jAHZNyS5EcAKMeCzTHTPHNwYLhaKLWlbfv8vfqAuJ+yrhFxYTqQcYT0yFCjIOubiYLptfDhc4tDSpz8/rv5S/XVORVVk/XPi1NCRPeVNOGBgYqk6KeowlpY2/6zAvbNFv35yrvP7KR4ZDv5X+gjQ3b9rXX/rmJmTIAHuhXGWhfx4bX3VnTMVCKDSiLkrG0QSrP+zlEBafN0Urr9VqUK5pLHRQ7FifppRdJ4Z8MMYw5xPAD2Tqd0Yigw+efAtnaDKpRaB5BuarGK6m+KzCucKMO/SEn4JdjYx+RHCF4ayVNMsU33lJE9SW1LddI1BrKalL3wnrTFkXmJm4nIeNblbzTlFvYUEPA/OarlAOwVviKaQNX04O2jc/65PmPBy4JaXA/PppODCVxxCjJolgezhcdWRU0KpP/IBy4WNkg+FbqC7FsEy0HxP2htMjBHdLAB0N00rLFGPCWoqp10AGpA2jqRW/gYZXSFGKL5HdT8N55QCoTQHuAswlvWDvaM3baPWqu+/kZFOUOdmIVvmqI6fppIxEHjGgU1Fm07jlW/0x8wV1SEl/O2/bRQFWyPNBIvUQ0BSvFOiuNtFQc//b5jNdSbwrY8LIb+Xxj38Hs9PvMTn0w2vKkbe8wqNFqqSzFMVVqGzFuA6Ne8x8RqzEeMkZrl+fnefM4jatnUpLqOUYHjV6pcon2s/pIePdy0HQg4F2fgVSmV3l2U6UsFpZvlLKVhi7oMEiIL8dP+ZjLFOPxxJcEupSyBF+LfrgEh6AqAkFzNI3BqpNJzirx4FUav9jU1jTU4YhjkV6ZMUEcxATBAFJTueHgYIMco1FsetKm2Iufj0GMaONUKB5dxBkexpv+WHISUPQsUnZUZTAyblVQI5HgvTn8tirToqmgDlia+UIOGgDkca9HHA6j9Bjr0nanWsa70k9WApxScxUkqFYzzWtMVSa77sLbUQWxM/QaJFqcsVQTrNlcgW3K6vwhZS01A5QQpjQtJ8Cw6BDSU+AIDPeN9Yfu0d98rCTNOgqeHLAGpRuVKQzwJk9bLqRsJCDAvslTqUNFkAqJrLlcSEjz/N5yJf64kjxnVrc+2AyTUkiLHrnKqX6OZ0clmx9S7uKxaOtujwsG3XqwVonaqcYxl2bgTjBcy7QeeLdOCvDhRVvONFYYz1YKyDKxHgMDVTEKYVEtvop6jEczUWPBGFiRfx5wR4ic7iMSMxs29wqNBuBR1Og8tWZta8F16ZK0UcIjfRALl9UMvQCL7Aiqt4lLYnCI30W+qeUb6bArViIM93oipZjcdw2ZS4R0oGxDmdNN9ZnVFXirLm+7bO2d0zJRTP3+ycam30wtfZ4KfFDmhMpPxCXUvH2BD8RpS/mKllSUHRodd/gNVBMjVjjJPK/kfugPF0idRtVEukhwtrgHOemdP6MDqsNNFaZE1/j73Zgvw/OzzJy0VsOy2OxoaNQkSq8xQ1rlsxdH0yqlFnInj/5zTrEHLglq66WvPKmguuOnZGjWrXntaMo5xMuSjxqeBtPBADU0zSeoUypYwoFaurSgQN2S444liOBouX2eCwPjCLpybg0FMdpE3hzHBJ8FD3lzqaDUUtJtYQfw1NGJ9+XGqN/lQ3Ovi8woczkY0e/aZDdUvEei0uJix6X/ANrjA+9wgmAF8uhC9UKSTus0PQX6ZWnT6GYIZokCiIYIDGi4kC8PF+g5D5hN2+5No6WE0ztGi6bVxBWWfYGkRZXG4ViYSdpx5lA88/nCC14MomJVNUOGXCjaeA7jyGpPharQDxTZNjXutK0R6VSXrALuDCWh8inYExB8/QbaTPUy3SsRDEmdI0OgcPx7jYmuWq5EpgOHYhl6pyI2FFNvTJ4NqIYB21hxKSyf0w+SI1JrMpwyHpijMamaXWoj50dFslAkRMazq9AAcvrms1T/Dgnb4ulO78JOifpJyeSPCtaVR0d/CwPaXIc69QpIKilp2HL7SRi91nEzGkmH1jd9Ldn6LEU6yaRkmtLpls3Atmzfgy8HxioTFwKMrSxz7yJCMw0ZjAFRgDjLnfMYhfj5KTUjpj/laP4cdlGP2baDBVnLwR6OJDxyOmOYYx//ipG47Duyznnw+uTT9fPWTR/3hZvUe5e+6yJETpDdk4HTQ2NmoMOmC4mSi7RX5vgadLMVJWng2YEkqqymIiRUnqk2RgE+4xpBKwvStmD7I/fIUdZLTiTeNmtD8IDHLfiCGH6e7ebzLBKOhwPEHqXiYf1Iv29ZuZAFQe5OD8ZAPK2sRKoOHOJsUC9Jg9ktrni5bK0NaHugj2rWklKrPcqjIotRlcosjoUFn3WN3oWmOk9vnygEoPY8SxpcIbU26sBHzlghsSlYIi8vB5mlZ/t2U/CWCX5+S2hYH+SWG2/gEAH47LfA+r6VqdBiBZGKzHueC3Hc6AoWicoecVOrPWj4LGoYCjbtjr9IrSAVdZGnaEB/P3zN+QW30/c7yG6V2c215jXHFMfGuwY3n17SZVbAYvwScaKw28tZ65H+DMwHXvCbBjBaE6PS5ekpl59+nKnK5ES1lqBu/C6Ix6zU0ph8CogSKLwmaFjBpT9SEJM6q0OMweZddwbg9pSJnjIIYzu4+NxvqG8MPpZgBq8LurDUlehKH8seFo0MtxQ8JI5mQCSrz89n0BzXm7qUyBuzWzHF0NcYsDzqA9sXaEg9KMXPZNur5n7JGu1Ydb2IQpemuAYtCmIG6U2jlydf01oOTmAqfbjd9BFdHaymcnrb9iEUYr5/Xm5/v/lXeytKw0u9PzWzz+2YWVQIsz34GWQG9jXlpYXi8a44ICHSHOuyXphRaqZRXkf+QyoJ6km78rinRFxkFniIg4LKYl53Trkt64IbwdNweg9LlEIf27AvrluLFHi26D4i+BSTVRM8WBg6YB7FxDDYIr3n/VVSeQfX1t5pcKGPv5OKkQOeDvlQxfPUP//pyPRlkZNR92Xf/HwYsH0fwo84F9A7+ChTGg5D4/BTPcwgyGlrkAgJdvOCGNWc7GJnXDPwYHOClVY11vdLFc2GtAuU9W8Q/FPqCUjkX68/LfUBxyII2ZkBQn23+NVmfpQAO4ttmPVDsHJnIBgrVjqIHVgRIT8kLgHno9KA6NqWTdFJBpuczMoiXz9/njSZCzDDWHmGHfmwdzwHGgdMnw8fX1d5eCi8o4FPmamEucP453NFKKv2GYduqg2jOA5+3e9Qv+MAyuoo4MZDOapM07dSPcXI4fhdmhLkg9sa5soZG6FVu1wqVQAg0TdtVygPXVkNdLcEwH6+PhYhry5yXxwfAbs/JORS5yKziugZcMsZCa5aBE+F9EDM0/7+GuplvGnPqF7GLCsYD4vU9CWWFAA7NHYg2jOYbR7A2sOe5Z+CgZaldHBQrYum8FKDruf0tqWH8QFqxgK/OI82amkEF3VCT6SyxAclgceU4hrPSAgcIE2ksaj+6Xt15kaXHkhE4xf9DRR0fiu0gS/sJd1UfEsQ/oaCRHWVLKbMieJMkJgzAxtnEiY4DtXogJCnTTMhND1EkbReZiGABpIO1Dz8gYrx8JjC7zNG4DgHnkrN8Y43925RL/1cZw+JqC27fOUdir7jnTkqowhRh0VKg9Qa1SLV+kecvJnAX1KCPsqj1BRSqtkt4JbTEOzpUwdeYItczlbSDL8Jgi+i/16Pu982Kh3YTzlzraM1QwUu4kweaXHIxdg10Rsm/qa2CCLBudJrfZsoFME1SAPx1ufjnraibIDGSjr1N02ihZ3FzLfrsiyaqksRyId8f8kkbY4e5lfbJGrkYJvf4s3HoQu7HqonXBJrG89WIBJ7uealGOLrKcFQLKtB8iP7Uy1csoWCmWWouF2MCfCyLZ8Wr8YWul6rqRYvCkbBnc8/qNlaRKyaQrPumUyEXebc3ms2DMQ1NAmpfnicncuFt4+DbSplt6mQgy3oOc04h3eH3kkxjnkFEAVdNeuyKB1Cpz2F+b8tPodb1vgc2M6CmgiO0qkCW5frsXig6vOFyKAKhecG4CkuyMJIgRmgbQsi7WpQycBpXPrO3mGro7I4bUYwFwazig6sbOQZCSSeD/7HjLzp5j38S7MJO7OW3ov5SbT0fCC370yQnOa96eXYVNUSOrirG6aGxehy2lofdg3l+XqvH06Y/EKWsrbiO3lsoO2ZT92bEPl8/Ztcz8+Jmo5GMIcs+gkg/23OtQEM3ZmP6urlib7pJBYth1wpAvTUZIk/yzwTZ4DPVsSIzNa/9QOLSKLjKdQB16Bpc5pEsDUode/ZImrKW6NvcPxU1OHbGrGZyRibeZsaotjMgu0ggTDImvHpUA5ceqnu2Hmk0+VlHHFwgZpOVxQnsp7MP+BoxfIGroHDviXcSVye4O5+3a7TEhlkqgOHQMmWrBVyMu8MkcEwfUaQ3mxL6rFs1s25DpTcvs0hl2fTaHQJfJzpMIkLCcuzNqZSndZCT00RSxR+7KCdfVAcSwPMIYxfIL/H4LVDWRzP/xrRYqFeuvqEkmI3ffrCHvE1y08oSSJGtq11Cx9Dp7m7tGX/z3mAKp3XHCtwFu+QmmvK9ALh6C7cFU934OFg8qT8pAK/o51K0BwPiVtUjAYHOeydT3eFdwJl+xRBH+AclJ0OxRkXlKKYD8NHjaPj8imIlGWnEbk8tmpLC/4u4UaIS+pdev651K6UNHz8qFHKCuJZC4JvX4v7Vwz6FAIi/eB2n+4HnIpkyJiieiDlYZWm1ZTaA84AEK1LWxSBpul0o9xc9bbOKxUEuudfavLnbd4Zgh2cEjzSU37u3E1fSN2EQ67ro6BXyu4yUWMtaMsaK6r0pVU3xdRCzadZyvpkHr0m6+/BKFq9zZ3Ra91sOlbDU9iatqmA701tQ3F6WTVg1ovY87ImiRvGLE7N7MEl4yuNEG5mmFwXhSlOSXpZC5fyqOIRDM5rO6krFXsy6XJiC4X7mvVAHV6OzTftocp9V6u35hJVitdLQ6VYLWAeoR8X1ff7I3llH0sjhnb4y4ZRli2ZXpo3fl5erDIR+dtcBMa5bHCNOMQJg5dA5iGCky+BKH0idKrPPMkuZqBrtdlwXVjQgX52X11oBPuUB87lhBVZ6KRYnxp/JyM7CDubl030zs28nDYAkewfvLbsunztmFR/inHKIT8ZB9v2Jn6nITvIGEc4+UC9W6pOqUPUiLp4h5dl0031xDS8qoraeZ2IY7h/1wZ677+vVJvmZXvHZgD11+CilUARkagattiQ1xr6ceYLNVBUwL62Kr8E7rDA+ayNnhfG9yQs+I6fVOTDiRRx6Px61yDWRwAEHrizSUWpRKXwv2hsYmi3BE+6JdQSrJ3MfeaSRGioaZKgMfj5KknJ0seZZlcvbpcuVdN7uBlqCgoLvBETFU9UGfaS61WaIkWw8UlW+ElxWniVEpx2TVimrZEttzaNZEd17fQwx1uaM146O4t2TqimIhedmQWmkuItZ4Ga4rWeGHPwnttEcP+oTayiS5R/stQW8jD5M33X0TXeO91TsKVc3LSP4HGmxzNZgYY3kCwFTlW447hgNZpFslK73pc7J5WNPTxzykTzYR0MPnw2ozd1Hp2+Lm1iBj/kZ0LnWo2xq4YeeC9aIrrQ5AN+Lw/PH4H3J+meq/UVDcTmkEpvGnP18AsmH+eRqxPIWggOM2AF66BK6KzlFL1P9Iiq9AiiMqx7ftlgnIZP4qOlzm354orJl2FqJdO2IFmp1J9PFsPiHvWQkBp/WOCZrG6vhKnZnobYmz4UqMa0w2v9tbwLZo9g/FH2dMIj57kA0XViDfdvqQIIQnfPMSAFvqY3ty57r3i2h+zo6nq4aatC2MXK2dzXtLFG/cx39geakm/MXnuzsgHxPk7ZC4mXCdIyUbn+9F18/6NgLE0BVUUpnxmo5UHRvKVeXzNe3HXQ7evXZBsMolyj3K45tHIjBPKXaCOQB43UW0VBEUmNwBr4cw5TJHilUCSIBOZNDcnGmqAWr82gGFNu0tBjYGYLweMoCiLhuxbv0KB8H0ucXKuNIFT4By7bGmJotJpJeZNpMZlD82sGTKRsETcxXBRFXfcaoU0ZBAZs1liUJSXLr/kIwnBX+o5hhb7xz+dsjKa9K2wfezIk8kfknj8Vo0S1QoCcxe9EGYsa4YuVl8X0tf8PdwAXwY4vaaWCZLDcosAEPdPGNGPBMpzD34L5a+Zg2r9keyXF0gxLWtPQeJx3IU1nW88oOsZtpwbk2ITrAFfQi1uQcw8+5S1jAKgCzfIpZx+JGEPIGYIdnS1KBT6erNRSz5P6NmuziEmLSFGK/MpEtqGKmrfED+nfLHsuSl1vCHYPncN8/uOB3zX1rKLA8NFkfc9/gx4ed/k6VVwKQaFPYWv8yOL5A7rMBSZq5rIFMGHypX1qRTJc01BItfYEhNs7/FJyDsQw5cXJdR70E/mQHfP646ecs+NDbDXNtvA0qER3vEZmEQLP46Y8EbeFOxGXEKAgN7V29TmAa/Eye4bGQok3I4Vm/gc607Axop09TcNoK428pMBuWdo3eU0x5Drl1iML5PDlJBiZbYoq1F76Mao5q8OLrOFLdIiGEdyvn3+CWEvMvvPUYPNCRj4H45c8ZVu/9v/MFc3C9KAKQZFT+ejqYtgyAv49UTDtV+ozz3eGDtjnojA4IOAIkw+ZhjobYG0mk5h3pHqnL2nG4Dq4NC9Q9WDC3YL4SM/PetLnNqebk8OYIkexU/dHpK1wm59LnBsN4SrxxSbi2yGpPfDeQK/2AUxlBfmelJkN3Z1PsaiiFJWymu2a0vv5g9V9J6vuYEjZQYmJmwTRsXgQ0s4PMgrfORzOIUKL55M6RmdxwO0WDle2YWGzwwBUO9oN2Mi/ayRnSMtzo6fcmbJlcp8R6I6KWZfSeffscP99mkeRRKEuSU8HLl1UP3louriUf0sk+JoaFldLXGLUM56B9z6zmQGrvg858+Tj/iOCO7yjOP0mKloHoWi4lDecfjoU8sOCbFaP8sm30adKp6fQGkJN1W9kC2Q1wrrpCtajgs35qnsrtIrKarI/EMxVfmdqmaGZVTHypOkQRC7qPKI3jQScwTprBHZJk4FSTGKR6YpkYOr5L8qbBQHRnxRsmOB+kZ7iUmdqMMWWVMaxt2orZAiPcaZ8cTh+2zu8nbzE6nxRwph+qpuOTiptrn/IA2Bu1pN/fWrg5iHJZ10k1ZAhDDohXr6geP0x2R+eogiqsUPsTjkltH0EWYcF9jAmWoahY+w7OgKMnf3plDzVup0ELZoLQcL9tdYwTiB3h/q1LpCwoCOHshv3/FOQKz+1loW0Bg4wQRi/ntIigMpI+LJ3P5f2ocYf3FXz4S1WLRO8cardW8aIXJilkRCzJr2xQAZZr+X4KYdmy0hJrkd80Xy8aMcBu1oljF+R8vzN286NGFlEVu0NTlEIhEKYwuiBZsVD7LTa+d6AEp8ZYuDBr32rRI9DW6ZGReIGn1SYNEOV6hyIBMg5JfTImzYeSOgogI1QdUrDJeWzj3oPtv7cDhyzT48kOC5EPfqHTJwp1+d4eXtK/CGWnDN05m51iV/HhZASv6SshZQe22Ao9CCEKR4Er0veBfEI6YE8I/lNwQ1NYyAza7gujn+A8Q4XVb9/ui39dH0IEwS4i+XkNBwqH1NwS9T0CEYlo88yWVCeX7Y2sPTQoxrrmOOhisSPknf3WauBHNMClognMNQKqSGMqKptqzqzs2TRia2ggW1Ow3Eh0iBsvVhoKO75+ZEpQOke1o8NXLyU6qYUGbUwLGjaQ/LAhSxF65AKWbQQsnpdKIA3wdLqNvOzmBYMhy2IohSyVVPxevYj5xVvp0fXgwQhHZaw+CilXmIlgnJE0O7Fhy3K4XREgej4qejrrD6ikEG7NJkZJSoU3yIaCNb+7Bo3BEm2qSbxOhk/lmDs0B3K8BKyjGmAjarAIck5I/rF5jigVsL+9naTSqiU9FT9eSqdwR6vqCjezQOFOHr3SmAkpEe/FSZyeiUrkVhGnrkLUlqLx34KheWk3fAPzeY0p7GRU6o/SmT74CMPCcTYHHm4VaHB7qgQflBuA9Ux7ObbwNUoKSL1MdHM1G+uF1uZ6Uxf8/huwDHsaOpx16EDPer0IEhBdY8lPwo4FNzcDpy66Jf3XQJN6dSbGrm/GjL4OP214OGSFEE6wYdQLXRXmTr5xOlUSEh1bzik32miAiMS9Uk8kiPMgeWymaAKJdN+f1SSQXT9lstAXdeVMs2B+VPi56uT4OyrdpgSoOLlVHpfGsVLcmTgefum298FJmBeZ5WeQzg1M6Vjo9En7W61eAdD4CTrwFDmlEqzFZUFz9Y8BcRz6I6ytinr4/2JiXXKKXRbUiQ2bk88cW+sPQG6Pxwve/EhphZN675nWj6YrHeKi+q2PUJpiSpb6Tn3D7XWzSGYYQO6dXCajuRgVPN7hBZ2+sp5xFM6XTpoaXXBUS9SjubHdWk9lgVTCgMG6E9trGlF72VJdYHawl3AM0b6S690uVzcybk72gVoA2mYyiSoYQhv/hANXRo4uSoRKmCFT0GeXnGE4Hp20AeR+CGIVFgVkSJMuRu7IZfZkT3acFezWh1n/2dEIKSTYFbg3FaM8qn0kdhAS+teoo8/+qFsC+67d5GT9vEmI/AYXBoBQWkJe2KtzsxoWyuP8/WhC3weACRkOlzBlumlp4xodN2fWv2GCGpWIixqZm5hQs5iGUB+xLkIUYXq6q43KJ2Bv8pwAo9TcNe4ecYTRi6bw4EGMKSsHHiB+rdlG2Pn2r6vexw5Kqow5VE9rF6ByY1f+0vWzUIXMIuUDRzDhaecS+u+OqFVlJIB254ElwZnCM8/BX0w97vRwwcTYcDfv7Jk7/R3nTT+SGIM+VWA9RGbLlb0mrUYhzufKwK66PnFpX3AkGhEvqHQQFLi+1n2CXb+cdkIyV6Yu2qDak74FULPYDmEGwbiuUfD8GeGCNhB9c/gR8p7fsDRoPO2YWr1zT17MIjnkErYdCXz5mO+bSR746kBv1dMv+mDqIDYhszuqPdsa2kZ4ah3hMIckBIdekam+Nire150u/lYmBfDrTgFDzzkyqx2nuPraKmc7V6+qQCtEEhg+oid+2Qe6ezSWtLm+aakEQnm/313R+jnMh6LACuA/GDbIifbsM8/Xo2bjCt3xJHCuymVWbOZbfUIoYw2jhMPJgHxAI5SSPQlGZJh39FJCzDIFAVxyC/cFCBVlqyZW8dlzi1hSr+XTI+RC/sIljFGmrw/rK/9NfOcKokWpaFeai7LWtav/fp5nivfolpTc+Wzqw4ROqhA9vxgEPzZf4HTz6ddCMgirI5aPJeIisyUitaWjzbYCeH5vKf40WUmVVJcXGjmPx84Xq3MT4BMa0vT/uqkRODji3cyvdDrGz79kiTy3UB//h8M2thElhPwEE/6prWBKFEl5Z/aPGsZY4PWek7pyTcj5pRGd9yZO15majjjBybYag7JbX43Da4y7zlvv18OTGtIWAV86gWXC4Db1ujcMeZTvWcBemhyPS0OyGSaoAdi46axmFqT91O42RVcbmBoSkWp9VXJWiH8Z0Uk5siBrYZY6YN+k8e1mLq2M8Ii5c7GWb+sQw19qP4qi69xF+0Kpsl1gveQMbHPxsKu8vAg0vXGg40Lck+ITNH5QgRiwOZn4a7+wBrDW990IM6+wKJgDp4LMftjTsBvDyl9sIvHD5EqoCAsrVi21I5SIyUCOAjrRo38DKQCDsJWt4aCtWNq5kqH9jbqIwEH4fB94j32nDMD227COWfZ3YNe5iWxh0xP5/vyYdOPXmY0fMgzXp8qKZsZKZbPUx4Z9x8ytccOqDyuhK/sUPax6qj4Xh8iF34YIwJLhR42w+nX+Xhp9cF9XUcqRO7MbX414bhaBo/0aFwr5qzBR4ECh6kAusYXwpwzDqk7Zl9TwKiR4wjcOpcJ4dEKXsLTMP+s1xw/pDXiux08QiIy0Bw/enKVGlDn8S7g7k2hKJU7CPJ1T7CRuqgyqu2dX6dvWKtNn+P8Mxn2On+F0LpM/u4d+5PpwaEsDdpKQKptszZXgnwkpaHLD8lHaF7n2DsjAfFRkc1VKzwQojb+hc5d9MQDvjRlibK5YpKZyRx0q2PcrQL3nBLrI1dJzfa7nclvTLF4t5Aw3+W7Eix40fDHYMfVNtXkILUyFUFr81InUuNdo0tIyif7Q2L8cXK66xEA2aKDjHdV/5yy5uRYtPHo7qSi25XJHAHpaGC7k3jSpozr05QSGe3AtGAGVYQNtI0bInFoSm5hl0wcGnT9sZWESMvsoLMBE7rOLwY9aMXgXy/RkPjFBlZLC7442rRojj2TMlE4OcPz5m5hlc49Hwc1TPNW0joccVUZIALb4g8VeCVKo3TZXZgupwTypvmjQhsq5KVh04nAkwh8dMhwbpw79d6tidRqrcrjOM5uuCt1QlBiTI2ogSC9RBIVmaFZe/q1hJitqNUmaSkBTpt9uekjcivDYGjwaENPBFVyiAWM5k4eok+CHaGDK3OVAiIHsEIWXhlDHMKw9oGn/e22ex76+nRU7cg1NyG4ou39eprCPX+sxvmAC1HmDxFeODS9s9f1EvzOOyCW2tWbIa8tOjp7lbPLlTOOkHSrbUDNS8G9tRwCzMYc4cko0UuBI1TiLRxDMZea1wInMIMDLcocysGl/OcoZtdneoNn/FoDVFD5bu19mi+lOUfR4qJjbNaPzNKElLy3qCLuLPcpZkmUh3tfzB97YalJ6/YQGypnNUPrDQ+sD+nqUnVnvVY5a2jN25uGRYYDSNDIyPDzGwoGABve/iWJhloSofdOAEISDuygnAWy+GARwQ2bc4sroEWQdvIhgMHReaCN/CoFjXq+uQdq3NbxvYUCbZAlexgqqru2wX01Uhk59y0Cz/kUOLR6dYvxsVjbWBxqvLQZaMYnnHHR65jdDuKZasV5V2nFFerVPG0EXsphQWj3Z9t7nWqWNROhGcX9mexuUatC1sZZi0LX1aCJ4RgpNO1DS0UjpLhZx+QTqfTVxUsAyFTX8tFgN22aCpZWR/2APHO4K6tNo06bhdufmaCxs7wPhb9Fb17JC0sWT3iey463cYfKLSOvF7BUPyQ7ppX8soZa95F0MEAg5fyh8q3LXaaUXxJ72dyFMWurwQp3hHkRUtG/PsXRaZ0Rj2+D1UE8pPStO9hUE541MQj3lF4FVllD+jo7ENVw+gAlwwLOkGBwBqeTSXVCzhzRJIczm19AYPOQVPE2YVmLRQ6uUC3sRJTTC4Wcg+kQ+l8/Uqj2HjcBdHMP8xuibTWoRJ80i6MLiblT/9HVxXuZLAw4AUe9ewcwAoy/p8AI79xxPLMcPhVwD5FEobEK/P5O0XnKWvTav6zSkaeGcErHt1DjyRpiKtSxZQMeS07IuM5eyYNJZbKZnbjptQP8FbLvPzMe9/AmapTEZ5fLGvdvSqWnbqYuoPKxQ+CkZSjNI+zEeWAeV7pxqN0ice10N25NF04j3yhj8mGKPOb679CLMPq95Cj7iCbi7wT17qZggjgHGnzMgVTpanOfqlvDreMEFtCZaDrT+T1Wcxxc5J/raC5UYfHuUwDp6utwg/5DrTkqYEC07ZfWdmSTczJg03AOKdCQk7bGLEcws4lZLPH2OocVIRgP5Zg+f2VQlilO4EicQOUdpH//vw8lPOhxXjbX1Z3OrLRACbbqh5EWS9iTX2PfQ4gnVdATWkAK5LJhiduaSBfX1PO8niJ8FNtegK18ASw1FX3msQAyHu+Z5bCEojd1ri2zYYYTBWZAt/mhBBN7LsqtdhpdOaN7LXipqGvzfu8vaUakd0oZ8Zryi23Y+Ss580EzugzZd+MRr55JpRkdUgwFWNdLsPz5j42ZOZ4ey67a33e8wlD9O5TiN5cMBU3pb4RVUB0bxbOW45yfc9O85ehwWHTc5Fhh0wX+TlqyLJrWLFKp1hD2J/NNZys144JbG1W4faL49V7d84djGKgO1uk0p6BWRCJtcJBVN6DvIyAjdGL2zLMkqTNsiufi5EfdzbmJi3X6Qh326aZZv4b62qxzdtK8Q6z1CD+OEuZyyJ0zTS3JyYlpKGEnMlkd9DLtqfpgBeJ6gsYLNgLBtbBRiVJ9zvoShomLYxKXSSqfBEZgPbS0Tl87MFemaGAq09JfwvvyV9CiNpjSJkjUTlWRRLNacUiR+xamHui0z49mm0MHdxqBLOelA3sA/84Ej8zJCOAaDjfFevRX9/uRnNqwH9kricM/Drq3SEnVhv6sSbbJuE3hCC7qKwwGdHX4IyN+Kl3hIGTZWKK4M+NNKyAdeT7T6OmbEpZgUi1/e07dn1vne/x4PyHGXvGeUSTa6LPPl0Vs1FqGvHlsebEdVxjpzbSbsKFtiymVaY7/lpzD1ydk0WPRuYXmuKRZeWOe4+6wRRmWfhaL59DmKuSTLrIsbWKdKy/A6uMM5DUN3c+aQQC7eC2zB+0y1EHq5ol9quaYvd+fbmMsDM7lkJLlvscCBn87G6QV1aq75y/FNM+udCtEYo14zJaCZ2Af3AyVMYigHkHH45cLN70tqkizFd3U7oKUWUDFDRcO6WT6fTVrmx0MHJvMJdB+e/6m7yvLIwp9qTG8MNFtfirhm3OKeCV/c4BM9L6/FPTyDB5U+ej1Ps/shDv88vD8scXDilCCalzAmhVRrNokTSEoOU1MWkHJZNXxAXqSz+9E8TGyJLMPpEZk5Ry8yuZNuAxsgRV21OBJJ3RNB0Cp2UvAhAdJMlBv+dysFM8I+RRdQjGf4DriUeD5BDDk2HTstzjfqbbEYbE4ml5Qd4REeEJbHvy9yKGXwzYzxsrKj2rfLwA6c0kUrSt2lm3ETOLG9V4d91HlzBOpIj0l7WxcXPmbSB1Tj9n+nb+Nb5U7bKme5seA8AR8PqmpxsyI13Am2XmwvMp2buBDzeGcUheR38mCsWU5vvNkbYED2DKo3gJoysSOreKNJ2sZtVV626qmPFWyiqI0u1TaX4TPaNPB7PXcwzqo6blX8mjr06rpF39fkVyQw5ZJyynLEYPUylQeYHGNrRRDgYI6pg7zA+xCkKkmuIkN7MKTTPZ60dKdHKeYkg6/GFHZPRNsxpYOXvN7v6572jby29iSc+N8WJn3dPWhBNZ9I5uyRdEo3UW+kwQf0NenQvWwnIw3zGB2F0REQmYlFtgCh1CsIpe3AjUe8rIKHxvJggTb1YfzAGNmej9GduH7WTxDVz79GkwZ5cWWVg88ex5cXh5EtDk0UxLFbeso0UANBWLxEUnE5PFjeQb//Um1JtGTY71BKEQvjZFVh9C55tSSG8ahVjWzA7h8+K9BFzC/BKGWc3ooDl5b+pastgZYA+nqu9UXvnWacC9gUddQeAojn0KToTo+Y1tPXDEygOA2fMKKHw8xfBr2M29pS7UjqAI9DPj5xMLxoQ4GAWGQOyeIvfQ1JtFSfwlKM5VuS4bXmEjZhg/pZh3ILHPTvdXJvICKf4ZoFugnEXKcvI8WSmFtyC+sPh8tb9SGGC9pFoZj/2i9HCDlCzIIPf8hffrmLYqj9zIOQyDV+ztks1XP4HYNlEtZFrqOLPvgosc8FO3YGMPPp9DOY6yE5znnPcbIU6/trXs3xJzTGId24GOcvr2/qaCDhLNSSb701yd7BlzCIZw6GbQeyyMTAwUmz6Zijptz8lLUXpY7sxFrSzPZAw8YqsEMVOT1tViNIaYct6moVBviX9tbd7qGa5RCbJp3Zxt3cMOcJwOLseXFHqsbiuA2jcjiQ+Yh152z7VDUs9VFBUE/REi6RYJUx0fWuzWxSdQzVDRRl3O8HNk2GhVY6+SSeWWnOeITxqYnLnPNAPXN1RYFLUXBOpX0LkuEwiMvYpVI50+iCkF9/jMKJF5aX0fBBQQeyLR1Qjnfk1s3xnGSwXLnPDuUb+ZSCeich6/9x9MxpVsHDW8qvkJnft3BF95woQsA95ZM7779ef6jNbk55D0QPLEUmbldq4NLc2jmLF+E6nhQAbHYtC1AwWpblpNr8MDnvwEEpCn2Gs205Chh5MauhO6e1UB3V2uiPIZsohgCllLK7vcScjFPS/6FB8dT4he9KUAoKkJL7fbeQ4SBNb/RJPL0cZii0aq105gDIeO0SFn7GXlxBP24N94ZK82+6j4pTvEQEAEeIJGqwre2cmJBRdbkVkYzNQXMaepsMtmbc91E6aktE8vIcUEXeCWXBHdck7e3JKPIy48WWK7A5Kwnn+po8Tp4+vyNff+rW7VYK3m4t9simmPD8oxYDkrhNBThcot9nw6ksON4E3atDBI2apUhIuHKORL1KHG2qFqdScwnUdBklsa9k5JK4HkKwaQhUgHqMu5tTTibWpeOw0ux9vvrgbkpvUQM5D2y0pSUdm5X5yiXyEaVjcHPP6XY/lGLTOtdKBtkoBhwoANeS0ZQmWgWhlmGkrLkYIaAYKBICrBANafUzZjpGekFQAN5XO95iXWKB1Pva8zrH50Aqw9GsXt86I9UPr6WANpDXiq4JoGaelM7o0RKPwdWFnCyqrDIgjZoicOotkJCUImVfa2ZqkzolPdQ8oO14xoxGrUNHSOQRI4I+JlYF1gQN5VcczG4aNnTOrA8yqa5ut5n4wUsQ2tcUDKj7bIyuTlibDFtVysRCJAnInM545t0uGZs0eX9HPs5/b0fc7x8UVGDj6ust5Bp58CcWhN+DtPOuSmjkDVEy/HyDoLZYCS+aYfhFvMCSMrEvMXgo6WYZ3axR2jMbNs96DEmbtMsur5EdYW9j4l8HSb/m6NO6XB3VLDDZDMNsngw1FXX9+QUC1amrgmPN02k3s1rZL7+plCTqKAbEtrfsfmZbeYEVaYUtPT8UApJZIRbQ+4iInWSjusEYWdsxJXzhMbCwV6zMk6SwOPEWssRROTeLtO+Y0p0XxWPurK6qirc5c/+NbJXA1uqaiIsdgY3h/gUnpyne0dYTKOFt34yKFSXrRRhM63DiYStLnfa/RfpYZJwWTGX792HWJ4d8vbc06+f6XMhj4I3JqgHUp/YTnFxti9koSIFTDJrI5T+JZm3wqxbo4iprrjufsJZMvVVrubxZxFPXdnAV1FsuqfdEZgIplPfr4abcqUt4xJO5hVwwODa04plydsWZMKEJLZ1of1GUxHxgUGWAOqWRb2+c+FFaKteS8DGDbdOlj3RzpmgHqogiZJpTRKiR+zFwyJLWrAmxkxLq7aTQJCLlmSYN2jDfv7V4fOqFLUUBgCCZwdt4k19NAqgVvKITMCcbg2RMkECx1HbGz6mQukiPdkUudEcWVuyA3ze5+k8gGHd6Lz1NCijPSo+mYR6xhpT/2DrE7uzDpEKPqhaeqJ8iDqgftd68dZPEBxr0nevoQqp6IUGpdj/ExMPUqj1L7Aah+25GGAU6xyrt5nft/MYRfY1x2aekS7EbAOC4RqQjShapx3GBGKCY29yDrgmoCYBc3c9jjCtcSC74DuehBGYIbp5Bk7ZzZI65oUZQkEOuNDiCe8rUWFX01ha5mZuncI0B5H/cNCJ/vmToaHalEag13FhR+F4ERg7FLMcexD02pRYoCiCBvZ5+pSYccCvMm/ADpUg0MoUm08hqbfKA/m7FvS9iGXkjKp8ugdesQR9fAxzwjozZ998QB8I51rQFmntcOQWCmoTKYYqxSMz/QMQpGAF5BWlLa6Ov6WBLK2tgcxl45xMB3UuxVPv27SPTnVQXENGIl9n5aaYnO6RHrs/0gCF6qZMWFEsLOa+LpIlmnjXGhI/akGOIrfOGjryroaO8qUGoSQcsl4FepvcxLtJSoBvGm0UCS9OPEj6HfLfv2ZJiTzvEek8pCEqeqqVgC2Scy8+4dA9iFbgfGwPq6FQ2LMZsRY8QTt64Sfk6Ci8psabNcebZdkXAcbSikMnBS0PK5PjHWvMNezlFzhJUNK5TAuEMetcwk7RVDPjFFazENffg0fxM1KDkqTRMTX4DdHRQUWdHmJcr3Bu/EhRtLus9tK1F6UiJuCM58hzZ01K5jG2pfoTg/P32NLoCsP2XJLk6iYXDIIC6f7ydBYFPvD/s3dlya7juHIv77vDQUqihv1v7B3LFidhpEBduaN/HFW3q6tMkwSBRCIT8E4dX3MODFwnlGGjTvHLjaCrL/Nu8dO572QqvVRmMhwMLSE4bquQQiwtTYxvjFs+f2zHOnI862haRcvEN1GbdwxbLmhZwsSXqxeMNPQpch/acREfk2pO95ZWnCbrPuXe4pUtqZPU0wkTShcceHv//amAnzL8bBTdFzn7W+HSC6amDxX0EcJ88GiB/Sx3M4RC5TbYy79k6uOGgo+eevp/pURBUow3SH5TkfL+UMtHtyXwU4F+WjmIfcFPzAWSR6Dwcy65tVvqUxrZGu5pLdDJS992InE14wRpWSN2qOYdyFIkqPR6/+cEcwXUwVQ0pbaYBFo39FgbZZoXiCwt+wOBq9BWEjrNWulf3wSg4/aJ9SpWvKyuxGHSNH3aHz8sx9dvMPBY3CGzXmRTJjOHuPWicP9koZPbv1CIQlsaCzjQYTKhBE2rhPcPec6XTEv+rjZSNNv9fCmYrljvmqbnN2WvniHL47tdWO038tsFgx96tBE2KLPxO0Vhngnq/rWcQmqobCq8OjUI1iUORk2TfExarpFbnfurJpNR6jcLmqF4wPqLAD2VzUwPLw4+ynQqT9cV4bs6pFLM9vT3Apx8y8d0jXByT9QMnwy3gYJLpdM4CTAcI2DqB0IwoYgPuk0OeCGQ4oBNNSt/NX8QzWzlnzx5/mgxTgzWzT8Fdj7er8joV48Zorg2cChKW/pg92sq1YQspkk92FHLlrCwDnHKDeMe3ExLZjZtRmHSzNn3HGQ6v5oCCOz9+tbKVSB9jzvFztD5+/dPpGYGokwrumdjeHn1mF+PTTBc+r26zcT8LBJ/4grlGl22WSvYtZBoD5yjKa/Yv2alrNU8t6PnuUfyVcdfPx0wtqYtMh2K81Ahm76vtYQutrxhgo17ewnp7p/1FA0BHSmTsGQeWsLs1w7iMfkkCkBmXjwTGBv6+ZRMLP/nHBiqdQlaBdOQckrTGsCj9+mTjAjVA+q4oW5mTbFNYOxe70GBBKwQ6NMlgL1zNKFQ6TQrrtzAkkfSupoKWTNTXj817D8JyxzkRd7/WG6iuxaDvIaC0s57crZ7eCisyCpLdibK3KLoDLb5Qs8+0c8zZW701QY5uOSgIBXvSEyAmImcYfk/EwMMJGf64El64yb+VQbCe6xHy7G0i5R+n7HeQUr/AO7Wvz/1GmnIIeRKh4ogKMM+CJeoAI2TIu9h9gca0G+LHUpj3UuX0W9BMFpYLQiuNSAePRdjmHY8Dg8QHLJvKGia42tUEn/XOQ1Y2fPFgMZIfq8fCmkquqT+nsQGmYCk7nN9LugcbZ4Q0OlaHel8DWqXo2gVMZLotyDQBbIzS7kcVd0oIK9ihAk+GNV7I+rzBZfPvJhgF4BTfUox1VrYHBYDbNBwtC5N7YM5Pb3LfonyfrP3yVTrXoON3xqqANn0Wdej+1zF/lP91Et0Nm643blhuqbBIoCS3uormWqTGaOPDuG1ukCnHnIUiejfQk7Br+IHP+aQq6qo6YYZRhJ3gTOVSzjS3/uekRSNexOwKLXMfVH2xKPw2HSgIbYCmJzr3lNddFknhOU2MiGegncKeKGw/LYUQyXp2ZaEICRbWTMQ2HBcMk6UQe1saa9e+vqSsqXzMRncU7UUQa641jaWpgua239vcOvIODNkRWu7BWBznhidaCjTteEel7HMpbzRTRRG9syv46Gn0dN1oD1eXXyWQ+zRmsWrjIcKxKvax/Cql8L+pzjROzZhOhC9q/ZsgZQM1+Zf5V2Y9QVzPnpURvndc8TppG/f/n+Qi+hltZ+xVd9+Ack8/ydb7CWxtm+HPctDyANPnoX9Q0Yo6SMUmSkbQUPC6g5M203OBk1NO6ru5E9f6mA25fzUM1NRWKfCN8sM3oVBqbSuGc8OpOkicLmSedStmaKszdNwp2YXx9Zsez2elKGE9gbPaXRF2OyKTq3RaA0lz29FU8VZZmMx9WsvDgmMqjVln8pyOSn/DobZJ7lVP6LCTwm3DXfWW/FnGqmMj3gAifMOYkM+fwQNwSGaTTk/1KdbkSe3uqeqBf1IGW0u76sPiaYQGCJ31JxS50nlivDQQkBMUy5tKO7rlDx00o4fgK8aqXp+Kv5jOewmsVQL5DZpL9IWR3nsUVyQoZd941D+LS1/m3/KyRZragsaC4A6znRS50ZC1h5Ywv62Dhvsi2DYRVqYr4OpoJYwHSJsoSM20SmuP/U+PbQsMUhHZbnYlq1r6gr1yHPB6ZAJumfnWExvGRIcw5TE6g11tH3eoPylsXfVM3yfgRb0tGjAOW1k8nMsTbrJdIBgwpbOgqXuOCCE7/MYVW5f87E/ohRem1TQ6mPPPc3VmbpzdQQnX5xviO/0X7ox9M82LKba8uVpxnyO4sdII/cApLE8OHAmWuIYRbV1w71u8mkDwkMfMUaJYvB5V+kfyI90Ezi/Sd88fbu6Bf7EI/D5FcsTEFotuptJaZ99eShkKxxz7duLhaS3Geuc+q4gDwKS+89j0V3RqMdyORCNHHiQ/0VgzvsHE9Xeqnn25ooub3+BOMEPDLHCEWBpS+Kkj4CgZXPK4MBDLZC4XI+rabnz+fgy7WulTG4UivhrEo2azYVSADPeLNtWvthsCVZRCXZu/P6/FFQCOy11kOrUNCiWHUjFnJibDpy+A9cJ63B8ikyBlwGyPmSVEEKQign1+hiJorPVa7pzbC/76sK2Ld44S5eGgxWNXbeaEm0jqE55bWQcJWu3jbwFB6bNsuBy2kRdPbDOJQvLcBrV13SlkmXGbiW8PGU5//cjF6pMZD2PHFQAi/YIFv3+or8ygcqe/ubhyovGaDovHRIXQXKh97vjUvzq0lQC73TdDmQcdPjYXM1RuekgRZgyRt3pvSkSVvfME88qc901OZxXdb9SCeGErPCPCFlemNaAlb/mQczxX7P5ZJ/NJ8PPfVqrTsYv+wMNIjyVOVxn3aI8P50nVRA8fzY8ZW6NwId1pUEG/U+tASJUkipY3pWJhKeeehvIXJqCrI0sjqkT16GZha7YvHMlNSg4oHyOiiQj64ZgcuZzEGW84aYJkb3TxJhli85U5t7E7sKxRMr7/UN85WZsPMfC7QHr8X4KGb1boSB80hNprQZjMs9JfIhdOj558dXPfH8HfonqZx9DNDxb5IOr09X4y/ya8qafaU6D+zW/lfzohEYBamNrG7djWNLQuOlAtYkm3cAujlgXGGfK6mSM+iHDKcluXtdhSIX3aR6KXUiw1hKs6NirKTsAvISI2Wu6V/e9mMwOIHGkby6bjhJFKSQLWlxejt/hOprc15512JmepIspVSdWAgvw9NITP/4rN/a6xoeSkzQM26ntOFyyRyVklSmUQtT1nGMpq02rGWc/0kVhAJ0l4QAufcTDdmip2LbcwVnjPLI1OpTIG7fLGqNQf2+SvCKXabcpIlHVcfegVU7PZ2hYFGkynFTK920KiDbw1ZqVNYtWkBvPB1XO3i3XZ9Lt+2RGjAmVbS2A7t8Y8ohiamXu8UT3A6eAhm8YnkLmuBSKGTImzw3qU3nxM4O37FHJAPP7DaVb+i1TB58X56l26Twvbkhy6Z1pvkUIrHsCYtcSZUT8EiCOiGjW6s5NWUDiHzGQRyRUHH81ievcYPuc7ZYxJYGs8kORW1lW+XyrSjA4R4EaimM5JFBysnmqfU7MAYW7H0pU0FR7833VXl4ng2Ps59+y+NC3acOEWKQa5Dfg2EVKTwWaRoK8FCgCE7A1svw6taEtyqHyDwW3NLo/mS54H5YJa/8h9GQRR7059UNHDuRSa1cSrKP5oargCpL/X+hb78lsEbkfBOhCUBXFg79Ezp55j9zXmNclKSOiamUj+za2a1kquuWgJj5DTxE9XRC659sEPPD0JUOK4IUExWEEc2o65s4ht3DUaCPKtgil9s24Sg6ZVotX9hWqPx+/y5eMEZIhhrvB+gfcsOrcDa0YEOdWRk2lPbQzzDbL8tr+HnugUjtNUilycYc61kdwUwrtkCpC/qwiVHaDN/q6KooBXB5pQMxurpYC7Pyl1jcj+4flfKN9Tvp4nXqO4acYSyyLfEPIHJd68tekbRny22c23OfhmEtzMujk7QTXsMv0PoGuN3vd8XJe9DJFLTHvh8SNCzxBVTPt5ymh7kBdRKQSQ5IDfhMzas2t/PD2PJw8r4Qz44gIwXRjiv8S/MYelL+MYk6vUh8A7mL7tKGUWdzreNJ7tL2hIRBNltT+zH5MrFsSJHL6k1pYdcr7yVQdBY0pX/k7NADQftBSGtwtNvE7LykbSLKy+qWtecaHxiNxVVtiYvd1Awbq8ta/qDjtQGUG9v95Msw8/Bc9R3nQbUaouuO+TFGJq3PMzQo3cvKOx1ukZN53OuUzvMXQpqnWYylKnMAurykhhha4lcWNXV+dEUEsB0au9OGACLzmiKYNBdfncMmZz1fnvo8JwgrSTcg7VX215vOfTjgEpgvCxBCYK4bA7Kp5vpfJCLzBL452gXOIkIyWrcvPuDmkzt0/BVQgOBluW+i2FRZ6tvwSUifCroaBgIrFJ9nxruTdtANlHiQD90WtpXBQ4G0cnTyTCQfS8o1YkS4t2MZYZlpy0bw7uZkUR20FdgkOjVfCR+ziKjv7fHupgjpLGiFPTFNCR4yKwpFBGqNkYN5TNNK44AEfTXn4WMNrPN+5K8HDU8K4+6cE+SP3kLFVd0s7qtlg35e+sJfN/jY8a5SiyZpsGrTmfrKHDW1gC+sqzekEzcJihXOLePPnorNEXunhxDMSf1y9Wxoo6beHZxp0UXP/p2l1Ulh5Bty26/Y8Kd3StYfasUjv5tdRllrCNIccJMbVk4eYS1XxkHn05XmlYhSfTytxn4N2e02gwA+5PLcFwgpTlrLMko+M9E0TWJf5z0h0W1oixWIkRiUqz3o5wLBsOSzDBBB1ZUpRISYodT4FDXxhdNgP0ZfNeJjNwwyP7ItPJHgCrxA5lczm7f5lOYht+rzBQzhA6SPIS6QlEFDXJY/WgYWG1Br5uFC1cMxZUPSUefNfPtLd2EnmOYffMt0bNi1RBbcDWRUyZaCEjWzvl4PlAmxvFzgUI33b4DU2MKqWg/lpLcPlHS3DJevWXzqi81ZwNXsnJ/unxGnhdFi5EcVIojYc8fiqVwhCIXPdkIVpuVJzJ67UWdi+wIB4/XcC11MYxroImwz8ApVNHUCGJH7pZeBqmqbXjdjMeTxCyszmYJfJYOV7XSWXViqwcDe6NwoGlKcPZcwzpletY3eNBk6fk0C2H+Ar3ZotTAfUpOYlyOZACM1AQwUNetKqOXltR9M+CVGAFkjEZf3js4wxNJc50Hh9Ax3FLXnoBKWkm/h3p5dzYiW/0fq8qh4QeczPxfp95dL2ff2+iEJWkb6BiAuZvMVxdPs5TEcqrHlt/5987BEwcHO5bqodEpEmrEEgEBSPa4rslDbSBIX1y4EPS9XiRihpdfXpbKhzQxHkjV2XPDksPD3UfVPuz+FucJ7GbMnlWZwUDsGLtPV18KbuECUvZbv5GwFfCx0ksn6G5vf/2dSMxMHz2PkL/sxbIK/5tkIJrXPSc9TuiihJpsH0DT/Ixx0AGIx+nJY5UHOkxCWnTj7+5hVyh0yyr+18nRTei3XWtczVaMYnZkNUyLjbZEHsqwj/Jd+i3aYcuDbUoKM9PmvzCMJ1IPtDaaqZGH/G1gOQjmp2AauD+ZjYzODiw9w4rNTspr4XOcy8BPyXckBpnpFba+CixXlQ1NdWKLGoDk1zZI2MxhhxJjoLmaMIefFgMG54ao6NVHuk8ImzP8GfKfiKDyibQZ5I5GuKT/1J5LyXDfqhLxEXF5nIzn67TslxIUEuVW5FUgNtr23pxB5xYLMt+6aV9tljHhoN3LXdIIgMHZJBPUIqqIXBxGqAK0RD8zicQnUcCaFfZb1YccUzhcP/z/gFyidHYOFfMVEM+9Sc1reUzPe/e7M2Ry3wenmmm6935tyq2LDc8XkjB9xUaGyr6YEqH9xpznunnQgsBVF4Ul/BeicZF7Itr9s08xRM3xxVA/xB8IlWi3EtKBSpzsZ23+h2EnEYTgGLyZm3sCcnTXW9zE4EzU1WcA3//oww7IoIGfSRIwR7U+ychLra4GL7OOZNuDLpokOh4LmmWoxNGCweDKkWlevYosL1bIuC0a4qBloP05Fx3aVPOEFkTCypatqzeckzjt5+vfErPpQHpn/N/JbzSOTRS1ZKIWKOTcxjZRW1Jk9Fw9PuPIyV7J8/0mWu5om3XPzupucLB3DBx6oOCuypDtOBbnacQgL4ZJAwdFMRQlXN2bSfnZkGj7rPLDItAwQqgY8otKPW8KanchgMIIRnXlbBaGQRsTvw2SBVPSEXSpiaUBjwEMuP/iaUVVT6EWiUYgm521lC+y9mNd1cYS8hiRR3QF9A1vqmKKyuJSjj1vpGccpsUrUm04n6aYoXt/9eHUBZEyKiLJqGOBhlStfyvp6fKFBA4ZAvEoLV1f1HxemofFViD4IRCqrzZi4gBtqQg2IP9mOIylWpHk2qyx3yfpGZYwShIvP+ovdKnC+RHnevIP9MhpnTDp7+QC6Ys8VBBWsW/1dvDMvuaMmLpo0kG2IDYgjcvyPmgW16QoonDmVD6Df2002OgTn37g6hKMRDT1Cw1+mDwpg9Tnd4UxTCuRPHCteceO4Zh8GoqdfxBhnByhn7i5HPbfBgdndTGTTvhyEb+JwDbFkPa8RcZsuedRHStyPYn3htJg6woVCMNCIAH7AhwV5gpTBN0uADxtFih1K6LkD4HK0V67hS5k1CGXN6nammSsa6BzEkknIDJ/3kagVBZSwQM9OupVNElcc8NDTg7LdXBlPc4x44CFEluB6sozGdTo3bqw93/Uvsxg1EbtNunAuYs9SzuBzHMOcyWl0OTxfJe02pp7rsZTVVq4FbI+nLymR+FW8tcAuHZHrv/2Miv+l5AQOUInhtLcHlUo6WM0On6xa/WPP0NvWoQio7IZdWObZJM+J12qfPCypEzpjAQV4uMLmbgFN3EQekKAFU/YykAJ9Pvg+4BkQHfFTsjlYHfP98KPlF1DrNxtU6ch3iD4MPK+Iog/w4J8TQztvn4HQhCxr4BBfOcqmlUdhQNiusGoSQzQoTsxB1z1vin4Hc4G+YqnT8x0Jg28pOyzuoRIkbI+YRQ4dUDn0tWzF5Z6lvDAkBlxWncEwH3kIB7FGeSjubRnZ8vUHgOFueuITYiskcyymOfBD6upeQoHAGns01oQNm9qEOzGny4sg6p4ZCyuiK96B3Ur3/d2QLo+KkHvLITEVvtATZ/8UbcUSR9VGJ6v6/0W15l9JvQ7N10IEofVMRYFyfVnneMhU+t2awsUcSsQ8y98ykVdgVaeJoN0BW6SdaoCOAVStk3kP5qExHQn6H/lkFB4jpC2AIk+dC24TIW9qomdN6EpQeb2tohkeWj7RZGai4jIgykWz0D9Mubk7z2KMVCkJlDN/AqMqFGsLw4mIB4uwSIQ6EeyjvmhERdYWOfQehG0zqSJw1isMxLnvjjmQjmHYODv0xQtCH14pWpMYYXuYK8E8lPNYG1H7yjgowESOAJ2YBONDXbEN2yQpwUtcz9f7RTbpxLCmN5YW7nCOiN27hlsXn+GLe05RaIBOXBTfn9oza2LNisCZzHBw8B2U06gCDMJ8XTIiAqrIOKnlEboKFbwWFFA5CYw7kSugUkRzctLaVSQQQJ8ddeHXRi7w+Y5JV6FTzgopFUhFI8HnVIzPrXJisWIp7fuclUL1LHLIgllm/QtRI6Zgrryn2j5+PIGdlNXIw4KWETyjOH1kLcEbeIyVmCXyuEwBQ7GV5LlHR6U/quOVu7JbcXMi3PJ3SW8o6SJ+m57DLjzSEb3bF0avynouAU+zSTlrEAcp7Xb2GX4FbsVs0xKmETgU/3E5hC5DGNxsP9wEZb7wcCM8DjlWvTxrywadNkXcdPZuelJ/0zegmLZs261+y79xYhCf7Zs/FAxb4dhhxVOXI1DpEnGM07xNQgh5jcTuF0lqMEW0ob5zViIHzNQxVFALN142KKmchtI6e6iAlIjjwiP37h4Ynow2FkktPHY+4jxpxAyQLoXOq4I4iSQlpcdKSKJ51hL2fSDaAX8wnFLDfyFup1TEBMY14l5rSirDl1bJhVgHx9vJAN1IVFhiu23OnZYylsrqjwMrd0mgHNwMnyw2RyDT7YwrTzu34eGjRXq6A21Yf0mt505uAWcyJWdJrPoNTKKhTyeo/JmIp8DAfARRl+axQ6gf9SH9lvJkJHu9R57aWclsHI08FVRAUCyWWD9rqXwAHURARRSKj58xWYx8ufNXARusRnwqmvWZZDNVeZi98BS/a/zfSgCyAzWRbrIh+tJk2BfwCyJk8W8LD1KUyN7JO+0QPlJGKNi8Brt0y5VoTVuQGNg8R6FTBO9eUcG07Q+XzexrPg3jSz0fmgqMB5ADcPvpEmIYYIO2q7QZEG6jDq6BRwmnnUMV0SyUyxiipRdI2mGxJOoPCo0k1CLcC17HsEFq8EkjefHol+LzZO2Tw0ISWTroX1eZ/cs4ujF5Ax3Q3/Iin1Gwsy5/IFsU1VAvAXyhbE1m3TN0FoeaizRYfbLSrBOPoBCAqFzNQsgFaD9U9piipsz8AhUyzGJ1gyKvE7dNfyrP2LRX4I3cUxMRtTw58T8uPHIUTdh/aqtEL0kCBTauQ1GP/S9mg5gz2jQwyDsLjsm5KaCeHFbKYLjlc2otGUg3+h1I+tG/h4IrHoov/BW6198RfkHWL+AfPxeKe+Vvp4NI21X6FNDvARuCG+FQvLGPdmsUhxUtL0QaJx7aIQapssnWJaygkizQFumAPqTE3te1oS9a8wBrZVmnzDQwgdgfHkJgyugF5zruPygjnhwYvduKtc6DH7BfER/0MY0hSwgWhEl0dVYWkEtO2syxuAipVVj3TmiZG8qpH0b4VTqvGLzo81PmKJQC7riWPyEbpMT+WvOoYQtQZ6ZfMwK5N+kFRwR3C+w1rNKQ3N4R0qE87dEpanRNxENAd3Qa175bCOBFRXX9mtBDStdamevGKfGyNKXXs0czRNNES/C5kk0E8kHKEJE/9CTEBNm2LkrjqfgXNaBK6aiC1F/bJ8IfXCRaRF9xcZjUE3MPvjzpRr1Y1F4K3BuWHBxPzdKmA3VHWUsBRm0oc9QbHsjCXp0da48uf+yXEmGf+Vrj6CiHzBdLKVxD2aLmt2KI2l10+PfjFUudfaSFRM/khT6hvTAuH63cZraaKNXW5z5W8wEydefIV1K3sPXTfRYCU89n0v8LgRGCRdBxuGhoVcHTA0kd3Hr76OBEdM3M6dB5cXrYimtYBhvjsL2WNQFiX4Kpk6+f9whQ0oByDurtEmkGE3dkh+nJ9LB9STtiiuCA+jiEDaw3n5A69BYKqOYOi3YIqRHAQl7WPaDtYi6SvNl7DVZmeoEtYsSmr9oupErphP/WSUE3osY18oRgFgBx0WaeP+sc9Hw35fc6mQ0v658XpwM8hgV+Xb5UsAk80tSusCQ6xPy8+MD5rDQIR2JI1yOCFIXGpykMqyA4aJlaKLRwfypWQT7AProDMO1/xlDk+9IdrtbTvM2YGvy3P/OWEIPV8rlm7mMTu8Q4aRoVT9ZY8sNDdsnNXwjLbzwMlE7+uV0b3G5coWTgp0/Qr1XZw6FKod51nyv+9CK2ooOA9RykCy0NzPgHVukzzbufOPQxYFNuRVH5/nblzORT30DdAQTv8O3PZU3BX2kGNGIPJdsO7sISIXhoNGvv8nUOERp5/Ij5fjz4SvveRgL22h4dGIk2LY8pl4W4JRftP9wPdIeyivkdLbn/1Zt1YKwl5MaXdex6yzzikI01MfuVK8QHpDjoZ4TZmgJ18waJ6In/IEZM+jOoiwg4qe6o6/VekFVt8Q6wdbb7yuTgWNEAuvqe18dg81VBZC0d1O3+xQ8oMHVUPP1LcnPCGvkp2oIyN1AL5Gq67bjHNVCuaC4BdlBFHP2D024W8YORMfzgu9Gz7hoFGXMXkO4/PgzuoxefnSOVVS4dwEj7lje4q901FrZ3leHpuLgm3MyM8gzTLUm0erXU7t3YaZYRsrFdGKmzUy6v/Un5KfcFTIJ3GpCmDT+pZoqK2iagKvApvnmpIMYWJnGqiKjZUPqrjCf8s4MLE1USZdVcMOZCfXKGahaD4FwiyC6atZfJjhes63lZ+eqgooqZZdXeTb/+9fgUSp7QQMy3J+wBeuboeHNzlIMG2ILfKwgMUo/6cM5DHHA1hG/N4mez7mFDOrWabNxUU4+sI3MZSkuQMucwHFkxk9Gna6qKGlv2ofNRCO6fblbkoK9cP4x64QeYQa0FjoiWCesRvqtEfPH+qKOFTilJ2Nr5JDZnxmi526N+HKcVMbKk61nf4oTjzshpTnA2Sitn+QAnUAwO8CxpWfe2fs8aZE161OBsJcTS2HPq9fsuZmV/y/cE2kMI4Cd2o5YDs7LV+UzoCtwErQsKFwUgKKRiOBfYEtABIJADb84RQpiENhJii3Mka0Gpd84AEiXiOx1N3ywGp8BY6lhFRbP8DQdd1coWNo9n0xLuDQU9PPPUCyMv4+dYxxnT+neH55x4A76MOzh2I/7nuFr/mp7/UrjUxSCfj9xxVSPzcc6gaIa62DJ4b4M4rWFq1jdoAIAIpu8JmXpJif1uT/thoqA5+JF040dtXz470AAoYsmsxOM8MVGoMsYglfYIwNBGNrCP7Y00xsLh2nFigAk4FyoEp85ElasH9Zd6P5LncMVghPNkWv30QBkj4lNY5AnDdxi0PI5qYSGuc+wpvzStVLQSVPrQ7N2/xcStUeq5L8X+ecGQc66EwvHCuHTKNNsdas2MbHioDxeoiNpLRr9AZf0sygZbBzWGyO+e5nqq7J3AKnfP2WE9t9t8MZQCQXTDS+neOqjlLwmKGfdROhqrf/04pyXFVAwG8LMhLzeKr1HIAd8m4JKVNDpflnx7m7PKTZEEii5Lv1DohgAuYLV7xdS4mwPkSk1sM8MhNAbRQMVI9gk7cD0x488lAt8hMcv4NYCIggPoQj7MaH2qXGZSLX4GBSM6zG5FO7nWTJ5y9/oG+yLEDpC6noF+ccrIdcdaccXKyP6nQhzndYDXAfTqiXEoZSvUZO3zPnUeRmwjoCO4iosC4kBwruymyUroROSZGbRgCXuLMySFaOaqxMVkvmYDHajzzMc+Ncmwqa1PcVEl97neATofy5eGu9ebbH6D2Bt3+nyP7MNTF1iXCW9gR1PgKdbSnqo5/qA7+804/FAu3Qj6hr/Yinm499teiqElrd2oScI9G/h4ReYAW892mPRff/ym1xqNMu5dI6yZK8oB/NyUZecnNsxPZ82ArIrsAP0DO4x6Tm5WJUx6lKc/Jc1/BQlN6OrxdhV6qpRcO7XcrcX/Mtu68zWmtD30eW8D2/vMoSHOHMgwgQ2HrifFujau9SYfhfM0NLweQL06vObsSJsOBgLFTuZjxGr1Yvrj1dYSYbs8bgDc9FHbUjJz57rldTTv/HAxNdnfhYLxJ52OCd7qICwMAiHvmwYDfAFI+M52O3u62aatrTlVHx6JwnI4SRrKBx1Aj+wBpXiKLyf5YkbLOG+K6YiFCAtGr0tcMeP+vvhM87oGTdJLsj/GchXeO5I+NPzJofLYea0rmmu0KP6/xQyXvhBOkbeqH6vZcugzDQw+XXG6zuanZVjXEn4nmUNThBo45+58C0xDbgZ0U86iXZyEcPovKO1WiH+LXb5kT5tVDYgyc36rYt5KnnYI3uHdwXY+tUxPe2aqOa9YGqfHixcruje3N0FN4NYvJBg5/n1Z4Vge4uR2wf84P/c00aKjrL2IKW3HoWuYCnJwEhJYoFnW/MGcFCUkb6JoFrsn3yXgCQyDWM6DQNlEiyOkBIY3OlHJtlyn83+IAkmCENk7Bz/l8CkygvIt5qbEhLR3uNSoSzSlJiICUqbyJxxGHfWn4wBO5ZwoX1PGAUtTGXQ0T83gT6brHD7BphSR4P7pntgk0i5HCUPSBclvjQ2BMhXPI3uX5wlUlaklA8R6xlbsMg9GNj5u4qNMx/9CNigqOGQp7nshDoG/XXfHRYx90uufpy37dE7Pa769aE7Cnu2qAVNmLUwRhWYhEZe+myHiyNeg9SZ121awFRkC2RF/o8OKAUn/pUGusDhsWN06vnLlQNF2Ei4Mnhs+Tp1llxbegyaxV1XAJOSPZlLWIheP9Xztu3B5qk9j9T9GMbyxV7Eog9FINAs70pK9cNR/7QIeu0Pgxg0TBND07abWXNeUWxwdNnF5e1saW9HIPG46e4ydzExXbV02a7T5y8VxagL6ezddnEgolgieSxFI8zkjAUoOhvOwCWWnV6WwnaTIfn/W7pafKkfumcUF2eVOiKfUTX+Dr5MeksKI7/elUnhKiLp6dn9TkoSRHfhq+FIvu2Acvunl8O48OEPIEy7tklB1sR75IxhMz9H1ekjLnX4tixsz++0Nm4eHcOuIp4zmOC0YlHWNc0J2DeZlaDMyQHvQhAJOCzzljdsKBePP/qJXk+cW1xH5NOIsygSKsUjwXcf2Cbhdyt+Qp4Ty/vgXuaHe39qt1ulvxm4XWWW1d3FjnA+IZ+Pslr6c926tMaxVIcMEJMP+YhUS20bL8mE4QmejWz9ljnn858TkcJ/5ekhKFjiEIi7a8G3PCCxmckANRR6avLBtm4mQHNtBb9lYMBHLca2GXSnT3a6ySrqz/Xp4GrFPsManjlKBqPanqZSkOm5lS6Ip8QGNLVkejqTmAg8wB0jODqqhSkZfpG8zJm8pQ/9AhYTc7jQIdImSj4PSNaSf5Pm3PHaolJn8VLYT2guLvxh0J8GAEg33VrZFAWYeSxz6aVY+s2V63wZ4zC0vkfBBdfWlrsLeY+3en7hezHlm1G+pG188M/YRODvE/NHGmxWXGApsk0Fupi1shSsP05O0BmRCnBH2pkAlTwnUMxfyOuhOp0oaGncv+WA//blPU3lVPZMnINvhQFpAp6HNy+gaGLTeHoRrX+NKo/JzRLiUfVDgVkj+oyfbD1OqYM7cSYKvQh3Z1Y+orqa06Bc5rBKxKvw7Eu0AFGLxtPRb8g5IUQ4cZwcAERYz5lQYMfcPLOTtxJ6bdRTmgXTmr/Gj1x5J6YtQgh+5HjgRUJJbD051acikKEqJqYHRXZh+Rcm5oB1SI08IF7wTGtn9/AjRA47+RDuohWUzBV2MGXzF8GR185cn8tBwv7iWd4tLjr5YTYh5/qqeKBXZFPgNU9CGA/Ssj8SeEr++AtcAJJ/JG0ddsCUV72NRO5iTj2gpWXTqAS34Ae4n3FC1V6eQBWEFIDuK6gYpEmoQaYKJ5oBZKz+TG36lTcBT04bZjJNLYLY+sfOoJAw5wUB66eT6oCaZvvuPGpv1DJSMYfY01z/tvmiWoedsC2o0ysL775+BokEFgRdG0zzGAzAna0DQcjol2eFpIjffqpTdOiPoi6Nr+wTSppiUX/LSjBtTdxKpeE6AVcJRVRqepaijKsTT8RfTgi5i+aVBaLJ9Wp7FY3mL7zd5jGTWS3j9n8VgeuJ0qsvYG9lEtWoy1iHWRqI2UwCSyhXBGgKZsY8yyjaevPIIXfvauOxq0bK8+D8K946L0s/c2MDmYVfc5gH/evWdmP5KE3iODeR2ds8QR+VouvIVO/rJfyxdCMSYI5kXh8hKOxpVxbhJcsNQO8g6ieKT0R8qHRyIXfBjhcUMwCbqsjEQ2gn9Ew43W+MkkHfrwI/kO+lWj6M8fk2QBX46LGfabQevovN/80DJXEui7+r1CKen00E4Q6/baxjJuHYUoUaFn/VSsF15uz3LTb6XtHrQjDYuDtRZ1SIOyJ+h+8SS8k8iuBwEy+GTTEe1BAEbmp+RJoSSwt8tWQC2klkKJ0pFLbp+zMULIOG1N91InQR3RzsxJXO5AfiCBOxb21TQEo+ZCTTX/L7ti5ZKWLV0vQ+m4A8n1SCHDizyRhYyW2To0FjMyUQpCkFIJvdQrV8STXc221+DBydqukC7SK3a1vAMfZf54UFVkCaktN1BblQPaEicWCihBCu4tTv/aum14APRMX1KqC3vt/V5h06wr7zcknOKv3DvyJWdSVO/nONbUH/MsUS3Z4QSvoJqr5EoiveahEFiDkTKjaDaGr1Eycr/ljXobLaajT4+upZoMsB12mCKJ9r5Rh+VHIAbasa27MjdUZjzUBkvP3J4zCKKL3RH0eKlUo6jIQBG4p/hS3io+PLPzC+oSrUz7xzUfqLFiObiM5aAQaLeurJfYHr+lsk6x/Zfu89nmqBsyDUo7qWiSpyMu70DOESA1Ta2/s9iknSl9g1vgiPP6hqmwItTIZV5zqJof2nAXOy75Le/VdX71U7EMpH82J2GaoMGZjtgUY7ahyGRPKNvxr+67kuzbB4g1iUMXp0yCPmqzy8eA6NdWLWmrAqAec011NuJ5gnlLfn5+zq+hWsidXeYIKFthI184C+ttqdGs/FP+6q5RdGji5i7ELFMPmSanaKSSHDotU7y0N856FG6mlKac9wBQL6e0WNVIc9Miw1jICWj6NgKxcXxwcXgouUNj45hZI9zp/S4EquHTr+mnbOl5Vg/1CYBAfK5PUxPLE6mKT7HFcsHXYMZlBA1phj00kRblaoMr/AD7M1eDkHOAxEGVYng4CgRjlv3Rl0FKhMkDX//BJ4JO3YY2etKVeLhfKsHEYkN8mKZcBtsIYcfm1bJDYKKRzyXa2xAT7fvI+/t/jR2AInHd/UNzs6fx4EoZm7x7AAAtbzMoOwKXl8guMqD1Mhy15i0T3ekVA5U0bKCN4JP7Ta97B/AaSh5gH4GkJZvHM7VuzPqQUO9pfChYzU4Lb33prgCq/yv5GVuZtBk3y15iyArggxM/9KAppjre3hfdAShEx0lQ8l8Or8P0QnJ4A7wVGNV76qAPO5Uw3xx6eIKWHtGiRSQjxU4pl8Kw7VHFlP2Us60yJO9DEAzklM8+Dt8EO0zLI5hWfod1e9iSRawh4q1mOLJL4kRAjXorgXfu5yQMM3hTZSJAlXWQK/1Ke7fGirmnfgGtXPSssKxPdDII1lxJEkYbhGBD9g/JWqHhYKbZSY4RWuv+p1Ld0/M8NNHQpM6a5wKxpqAZzD8RYfCvsIezUEGUb8hDi6MwO024Z58x5IVetwgmW7oOua9YAAY+NSDK5FNGBPep20OWq0LBEOLECEMhD5gCP1yKQRtG6lk57cU0DgVOzNROaopB59ulH9h7SGcjVuShE6bdcaoNCJtKWE1Q1ICxBCplLmbEHs+I58qYrQG35o7evMZBk464NWTnRCnhY0sk4WvIgdO3Swcx0mv0kN6kIfoI1obrdm0HQ08tbSWL/mNx4YD0VIcjUIkKaBnociTb6srRxL3xoSkrgyUhbp8dsaSHYm6iMshveUnXK7WvBshpSMrsofp7fQP0Ul0s8k4PVX5nmPF4IcRGZYLLkQmOtpmgyzNBjt74mEPOiIn57SKJBj/eROT0W8sZZyvYKtBNxVyJxhZF17g9vwr02upjUv89nDgTR34MMYseTjGdXqnMiZI3R9W97lRtfhK7mxv7Ao3J9KjYPjitFhU+vpgNui6FewzAYbao0/zM+CQFaPzWuQX28/5GJ0xyu0XYM7sDtLQKjPekD8Ubv07taJ3MvAQB7MJPH4jh0kuvUzL7qatDEzDmlp+tXQNueGikloPNgyt+s77U25o215hXKkuncSq63jZkfZg5lw6GDL0UgEXcod+iKkV/tKh6Qih9Rzjd4hIvAC5KcJ9ls8d7fKjvUxpUrSwpTitd17zk/Fs7lgkld+dlY32KKg4gqrpi0PwW6vv7P0a35yTgs0AKaNet//73bsCeU4iYZmp1cDxhN49O2tZ06VRurIKZFjKN/xEeKKWqepM9kf+pDJfO2wpjg/tYx54UzlSDIljc2IYSvGWGgdUOh8REEOfzBANcItBuHosONx3qNepAnGfDXO0aaSae/YHc73DKO3CmykCQcUP6ioOioQDmVmIu95Zbc5nJwWSOs0DrGziJ4O3SwXMhqeUX6f11d8ATpSt9vTDiRxBfjiDFmDMlc60KCOMYUuW7Zeu33BwLjU/qdh2/nlqhleXpAvG+KDl/58EELm3heW3f3wSTDLZmwA8G089aEs3NVKmXPgRCFWLwEmuI9mNOcjAc1yMlUCvYQTL+W+8UEGGzCxu0fVqu7HE1HSWuZRE9hXAqo8zPPtS2I5EhXxCV9Bs9WrmWG9HiLsoXciHXprTlWnqaazmJZyLACydPrqdcf8HQCRB00s1qchGYgm2ivibf1iioohRLIvFtQC8JjihovKTjS510Q1JJUWU0GO7gYXiIeTkOuF606EmDUtH54LNYejp7iLCVfdGfEW+rmlxzo7CiIJ3B3B9rYVkdZq2QBA7dmp45cA1eWNWcgjDDwReaJu3tkUJHSqcGctiERAOQdxQKTZnviXrQjjGaJVQyAqNlj6xLkxm8kzqQJW6RGuAThHu2D2Wp2iITeUymNTLJDMXtmZpC0HuA1qSsKVwO2RjQpg+9MfztX9FTeH2jwlw09no8llDbWV3+NezUMpU6NJZiLUD1l/YikMkakWxT66Oqiy1vE5lSe04G4yB/V/nEKSuLt4ZnJGaNupybEl4lGI1CMaGrK9t2fbK4rnhALxsJ7WsDOBGfB/ShDSudxkt3NXBEuPOnwEvSfrRvfzT7zWZ+8prMEDUzu+k56yk+AUD3o3C8XIlEQOEwRQ0114jxHyO1UaaHzmto0u2Km9jZ8zv9WhenNzSm5lOhx6+g2SkcfmDuTxkayXZwWpqCYxeS7YnWB4fvB1MTtYHAiMkKV1DbrhF/UdsWCYSOUATmmVeZpffkk1cdJwvzB5/IBIlUHgnqSBW2LTl4bpDfHvr0yFD/qOnqgKuUrmxMalCG9eVOXwPqyzzpEMqxYe+xTvNqPKDz+5VCxu2Zd5nRBt2iOkLvoersheL5m7pEFM7OInNEfRg4DytCF2cFr+vTj8HwwWgaKjlp+wEvSegASL7r2sxlWntJWENEtjNAI0AxTssTkQ/XNTEsRg4PVXjHkPptF3y6xWnZu+VwnEzbjgOMyqdvOj10DkxM27xllglM1TbivDfmarg8zJRaUmrGgwB2JStxSaHVmLCFkDfPr+tbHK0ABGmtGZyPOe66ktu1PWJqy7NrQkHEacDi4ALLjYHx3WwquvZUEbsFK+/wskUkzZqX9fUMxjLRH0ja2aqnchO6DUubn49DwgXP0DfT5V0+HvNTicPPMN/esth/ONpgVALRApyI8WjT9hrJVBjYKhIFKO8Pab7USOuYThN+JCc2tltjlKLOuJ7WVbAhIZi3OMZfgLAmpxgZ42c7C+Bp5imvs88J55qynKnwaH1mL+2HnvIb3VZlVGVL79PdDw8Z59yrE3Bmn0LXwACKZ20uQofWenWcT/yM+4HJDiKbVM2YXrGBaiwttTD95Mh3pdHTUeXKg+cAK1DAR1ZOZJjHW1udCVlQOYUIMRTMcfq8ussQOcN4feYJF3J3btEmSyfhoT8Wm3Jls5l9Ne9AwOLZPxbNjBmbfrnrXthUm4KNqZLLsxaDhcyEq2p4gCi9WFVMZUKOhNIh5FRIYzs4BHym10UledQzUcl9JmuliakwFXKfwIxd9h3DQ1MgFlla7+mhFlFOP21BZgpoEbOrmMYixpobA6YJnghIp5Xwpxtd2pQ7sFixv7/IM87TKw85LJlRb5oIFJqHWLsY9Y6cc/iV3f87KkaHKMRSw1pbbvBlOWXHDZcOeMsPX6S83HhPzDaytGTisD8nNCbl06e42wGbBnp+Am8vOODqw67rUKEhnknZV6wVBCXiGZ/PE8xS6aJHR9huooEk5YxEjASroeUlNmhpgvyWb2PSjpvC4yiLT3ToHVLoNbXTY3CxWpyOnwLWL84V0vZQa+jKEDAlvfdU1I9Neceb2KNn8Cg/BsoaDou2oZRrNTZ1QzALaLidONCnsMRlS3Psd45sTqFF6SFNmPRdf0ZhDHqn3kjfPdao6SdawJZN0zNFaVQc6+r5Sp2borVOpc00LzGDiHQVLYYBNPh2J/Nyn4axu7qXZ6ezZVm6ADxvicd8W1u7m0FoZvvSxR+U46JS14naF/oxyZu+cjiQUt36tnspfxYSXyBhIPV7+aac/ws3eaAMv+gYjcaOeDQHHodXO0ajCt0VePKYdEDMeLiXaZl+N7UaLX/FQZHOBcSerp8KmsuhfFXaYBQfKTgDi/GqBcehodU9eqgyHjKp2/85aDxmiYpjplNujoZTvFBW7eKRnOOumUriOpeKcaQo+xURQaAROcQTcVtNLpDF1N9iSvwzeRiVsUpwn/lQTAu5zg99xcRzYdX4fs8xmbJHJFRmuZjbhG4xIyY3QAnx0DkShWRPq2eLwnMEye35+Sk4v9HmANsrDmJ0o7uR557McGC0Tx8b1+XoGKmTe5kEKdYSq8ErOZ1auZHeDQn7sJ3tR9VaZMWZOn7RnZYtG+0w3Ui4UEtrGyFIhCgyPn8p8fOY8namlc+bg4HotHFShKfpOM7T0fUbTBErrLL4BM0f1ZkIhdzIHRyp/bOWKujT/91S+0jd2+4IrTctE08UfFTK6rlIussNBGDkVblWaOwif52wQLDETjFLGLLSh6irNYUki9OxxenznWhqh+iQgsW/HLAqTc4vgtuz0xTWFHV56Ro4u2P8Exzsu3Z5LM7TwXIybPTsf0pTLgpxaFPJfJjyjlyxPuXoshVuy926dMiiHpMWCHl81+Z0lW7lbE4gP+EAlWSLEamsw0wE3dEey4SL1MMVWB2HmNd/dqXQlOFE3NcLF1dkGp+vlsknFOWQwF0tJP9QrQ6Jkt9W4Nnd6L3FLXqqGpKijT3MNzQrkYaeNi8S1CMns90p1SA2FnVH+YGwRBZ/bV37/1ejsjwilYfBBLpnMsAbMvb5Q7LoXYiUObtcsRCEuQR6hVvIFYQN/ZHApD2/c5LC+FqNNeWOO0YuLofrDgp0eVYhtN6ler2S1HMMr4z7UL4x7SAePZhauZNeL7Mqm9LMrUVdWTWPYe8Lk4UPNhVFMus0gmDKXvqmn1Sjiodk2LMHYjLrQdDu6thd7hEFpeF1L1n9VsPeWAF0/fj5UyM2LcVXwHjHediDCGAp6uPz5QncP2QhkL9UobRoNNOH/5xCQnVgDGAkeFSqzdTEQ3QVvjfR1oRZ0QNC4XRj1D1R4li03W4N0Gi9fKicTX6Xx1fGaTZ03HVn7dH4JYNK+lxQJ+3/MkrJCJxNNKkm8DbGCE25c++LBlCZpwio2I5M00ywWE50KHVFs1y37mIQ1r5g1CEvI3pe3yb0fZS3vmwBdNB0Xs/LeeSDRMOM200cvyJisz2x1qBdZcxjMahrg/8c8RpLmSeZeRi8LGW0npI/mu3px7TZ0rdecF0S3VNUlQMBZg2AGcTFsf/446vtbdtKgRBzo17DBXCdTcnMtlY6lVjDULZ7rHKjwloBeG8m2crgv5SgI8mrd7Q8ji5rrgNdGKGgkQjywU5jbrdsCNQd0jjwcdw/gwxTwOIHYzrnxnZLUemkC0z4J6NIU4YHdLn8fJA9+suiKCvIS8dx3o66o+cYLJ6+yWUM4VeMovvFJ83Ybc57KEVNX3JKe6hzzcIRoSq/Smq+ljzdHA2Ctm70wDd/WOoN/FoVqfUG7ePPr8X7viPHgEwASDZkiHm32vKYy0t9nRAUwSkE1WIbY/B4zEVbWo05QpqqiljPPfbs2RimXPH3Tiv435Kuo4v2DEfuM4IFyXrgwx7KK0VNJSGkcUG+fQm5qk0QjIJknZsOsVw3tYLPg6JMpk8JkQv4V38lICyBb4OOo17f0tcN/kuFbdy2FJImlkJB5zwuJ21IxT7gDZQ1YXe8OJbvVpLbu7jtaRQwle8yze2Wiwd0Lj9A8ScxtuPJw7OAWdRsNz/d/1LeXtwuSDwI5GgIE4r5fOqe8LAKZDG2+zUQ6pfmiT8XFCKGQqfqHglHA9dnffUSXHGPaEZ+i/szwvNSu+ESMR4570s49rAXNQ9B/DTWp8IHDJB0SEZTatFZAUUKd2Kido56wajl4WHe9ZIrPEf50kBAuIlXH+ptK3IRsyTZwUlyykZw6WciP1aNxAydOtUeOKDpwXnm6yw+D2/LsPTwdJr2Sr9QxXhs1TSo5hCmwiZO86YIBA0ILurw0NxMG/XafeOu+x31gQYY/HTNaxUVa1QGoKLEUaEWnTwNqejmIZVhzrDtCM4HtC+q7eUa07Z1lw9M75bK/ubSuwyOmRtq6SD+VXJ8hzuQIPbhcpcYi8nr3Bv5530NKSWwXPhc/DCTRF+maTuIBUyE1SAGDLhUS1gitUcJiOkjCsAii0B1LA8A/AzHElhlrMa5LOgSh7FQpbVya88ns5C5BA6iaKtuq7GzJFvi/2PkGuiZGchxAu7PE8KUvOIaQiNk1TJDn1UQhCUSfhAELZawxra64fCNdxDdAkgvxGU/lxHinhOuOOe9bIOgyVjP+mSapYnTXGyjVaxiBt6CJT0NezZ9CsM30tMoQ1oCukG2DVlbibsZ+FoenU3KzoBksyCJjnLLXDRJtCSzAKplReeP2zF5jQm9l4v7B6IB9QXrMJy1xVKlv27gLSNMOFgaIt7TcYIJuXWqfvu1LNzDLemu+rSDYPSZqDXUDYvplZcahmRA/3USQTIXdAIaTFqo16ACc11k8dj45rovjgsIkH1yoQ3cln+fiqtR3Ck3P+/MXPs5uAV6yd4gSwPG0ip1R83TIIkG+zSD2vtb1g1hFEfUbKMRyTlQA0UiR5RUZWOuCUO/VGqZERQWrXlFjznW4mRmCHf6S8Qfbn6oOqBGss297vvh8gz3oQxqBSLkClnF+366pUJROhQH6wYrN3TT284Qr/mhwYgeXxrmfBah4zxOkZUKanplFVWlDH48CBOzaevicwqITnloL+sVleEW5zud8r29PEIyPlQelZk7c3nW3ZO5mX6bC7Rn5JDD0NVRiJliV3j5/CnHnnkIpPVEfzJVqrzYAVQ0IJBYQ9Ud2yWLjq0pHbgvJOAuqXyc1E/3QC6Tv0fOugJ2dlCpZDDNfoV4DaMnRC0IxKVxgh2oOohpZj//Q28vk6m4fORPf23xAI7RIOdW7n3Lmz6uR6PWmBnrHV1Fs3pVdNYCn3KqcgsFjVHeyJeSZsBFVngvwmzm1gaF3jcUCl3hiw1pX8N5xaWlhTbAFVGBF0WptiSMO/DphdrpGEPnZRCc6DhiS1umYlLCmvMGht2HOl9KHqrB5TySW5wFPJk/4wmT8ohnM5HdnJO5SadfOwrZQ1ykmldPAkLvHSDYGima8k9ey3f1h5VrMEThj84/kFp+QqmGi93cYli2QofWUNSclqbRKiXlv4Tk/K2ZOe1gFLq/xCHQmG0/gb81QXS6sGO6sN3Aj5pKpovdbU94IdtvamBdU17z1Y03JShTj+vrGXDW/2p1mOHYdzxKTxXgkoWEkP9cPTCwUn9L7zSgrMLWZIhneVu8g29LtpiHZnI0Hv62sA+33Je8N0KQwk0wlDl0kgJmQZQBJD5y2Y68afsxbT1ABmPnT0pMbhI+5PD+aYCGoXF93Lw7laqG8vJeYHECS5oRHvjF2oJzfhZQ/uptE29TCK/jX5+DJhc5xTQB3OM2nUTQ4IbRfW5jYTWLfsbdKefxxz4VFF0p66LeKVw4mEzNISDA36kuCsoek3MACjCyc3MEhFsfcnrj3m0mcGpKh7rrB6eemRtJUIZKF8s2RQZTiP/9VuIZ6Jpa0YdKtjS+3s0qnE+uJx6FDGc7+jOv6ol3l2FyiqdU8FvhJEVfkRS7tVS27i0VKIQ+1I1ICtIut9yd/HGWpB/nTyU0M41pEnFiqgbZ2Kj/TjngGhmVIq6EyCAvxqc1Ob04Zb5oOMXT5/IuW+mJYtVdqVOfUrLeKVfGHkFgYX7PgeOuGWojUrMW/kdmLSiNm3xGpc/EGuwmIx7SPBWBCEpDCY55d9gcqYm0AulggbGMxZOMVLjr1GpJ2n6nLT27sTs9b3Bn87KKBFHTzovs3TydxuyPNa6d01YYidhqZhIkrPGhBakY9Hi3vW/TSyzZeTqJrtNJEUxcvvURZ+hUXBbnqmNVsbLbNRCStekdLq7ZQvmwbLVG73bq7/5PGT89sJ9O+vaQnQmINDbE5inO4hm1CkB6Zfxi08ydTO3C9j8lAvPoimaIHagKUjQKNpJoqfh6xXs4uoKDYiG6ltmY87qQTQR0sAYNcSF3iOHsBxLqW50CR71TgtB/ocstNZmB03GVCtr5U5P0vC0sx8bnjVVBYyZ5G9ld32OnjSLrVDafLHv7uTYM33Jon/YAgv9UFI397ltKV5+ZrUp/sC8h5xSh+vWbFOXZqaBBYi7eTEnhV8nYpYd+PMMdsJMcoG7wLaIDQI46Lvjqrj2XIcR+sbcrrD1YWGcroLX++BdGhfe4qZMlLfbCpK9O14fwlWt/SefmQpG3bKOKi0ltKc+9Mzg9LryOt0wN7V4VhHGSS3hK+eTl4eJeYLYHLk2H/zgA/8m+6fBQ+gY/1vP3mvY16gKvtQfjMVOLMUS1kNlgeGWviWFGMqretV3mY7afN2mDxVHMWuuQ3jXbTCWyKfgcUJPiPubvqreZ14eu2LIF6NDHQxuCNueYLaqdXwSSoNhM9aCQv4ZLeAlHZpzi+LuWiifQysMll4Qjh9c3z8Xrd6t12aBtjjfAYfMakRdt3//CGPT1Ih0Kk1M42p03FejeyU5g84r+kkBwpkWQA7aTaGbu1GmwIuzcrVNRPlut7AsPQdS6HSAg8T44Amarkz9o29zJzvEQR8a1Txy0hH+f4kgZYwE672aUMegXY7ssSA5AHXu6tqu8aOMyTWa6kOP/yT0IeEUMHkEbt8WK7mZxwhrBF9D8kLsM8sa+lzhoy1RmUeQNDg0N6VN2o8GNwhpfmaDsvihoQoj2YuD2T/F44hcuEb5sCwyf9zWv99xPf6CDxcLBtzWHxRg3P9xjV7GHCPAR5sS1HbhoKQduPU7C33/BgC4Jz4HEBMQQW4HGx/GLgVBtdl3Cmq1TntuFe/i2BVcCKynqjRKUgMQd+5ZLn9ClIn5TXR+fSbWA0mHSGl5+z04AU0Y6NDGiI4ktyrqWOoRI1FiWEmS0PoO8o5rxvGOILTmtH4Fs3BGFzOeqyH1MRSFnTY7FLN9dlgQPnXpj0PnBRU/zu6Z2+qCwTKYUE898fkeZKQHWb0Qcr3spklYwD60Qy9xKVpWl3bjzoEV9XAQ55mCWZyxp/MXbwmOems+c8HT3tIFITQa8wWvUQ+mm2wem7pwWhRgRwKkyA8J4FiytefB4v3FYUqg+fCdbYii3uIY0Q+ltVo88/jHZv5PY3qbJV5zRu75DChp8MncNkf1/6Z4+f8pghofLZZocWjIduJdxN9Y7pqMHaRcRVZx2XWsua226LkCTKR1BWRsPXqJiHG5NazN7Cf3ZLeGEbwnul9VLMnsYkb0KVHJDJQ+dGxOV9hc9BkSyiOnHGdmxZwIXlPVEtwTBmCqreQA7+4WxZ1ZF1IMNfjOZczAwhArXlxd11Emg3GinrNSxxr4pncTQQQiUSKP+jv8aUxtLWqjP0QyeXS+Dt8Qg/xTZrjbmuweshcpfP1QSWM5K2pLIf8fIfkazpBU9e8hBfWh3O91lgKp5vEAkjjU98X5EYe30AVsA0Tl1pUPymIOuEutIZ+ImhcY9t1Wa3QkSW1KsY4xo3U1On+loT+WoGUOLOi9UXoO9mbAgzGXBjMIcKvb/2lPNTDWHZAg3dDL4GebH/HaSAugvfmQKr/cLOWrbGSKLzLGgk1tJZThQ1qclIsJglG6YLXEBjeksB00OHUJslBREEBtsF7cAw2wXfcjcSf2cS+LhdZBr4vKdJcR8J++vgYmcvL/27WXgYG9DJ7EhTc39tUpxZRsEAjVpmVjiBLy80yNNZ1xrSlZHbSuKL6ZP4/slb2LhOfV00iVSGloOMoWlwzCBIgK795hHVHwu/JZ3cG4Unxo70Naowf5C6tXamQK1Xtkz/w28w//+kMgx+mG6MUctEB1xIU+dDgyg2op5Fbs5KV85KpbRcH6o/q+i71tGjbvIV56dYtLCVXhTqpSK7y2di58OcloFKTG43VuHnUd5fiov5wIe11r4po1PPPjCitP1qjgRL5FLM0xEIKQmtlcwR7TypcKnYjdureD6GvL80UURQ60antStEOg1P1ShQnk+KqXSJrqPAnnZ0Qld5VCfEs2ozRa9Bnt2GyFRBmjOAS73kJqIrdwj+Weyrf32IQe09oPgJfEsn+I9W9bYKDZ/zzyAKiEIqoU9ckWLiCMcduMOqCPBcd3EcRjZOM2dCz42B21Fox0ykJl953E+78pzgzKdjA8pKncv4eOvRbulEkWaFlPNrB5stTqA4EWQg/q0x3dD4P1/7aXVAR//6apytG6MNTZsjDuEDhknR2L0BX4woB6abCY7iJNcHxqUlQNUa3KDB+50ytGiNyjtl2yQECwFxIOEc+HCbGf85OvaHpzTxRZGPqtq9lwisJtOQyUtUy4feviLeqrvV+Au92sp130tAbNa+bIMB6lw4s+4rh+Cq0D9VE5VnYC1gPzu0akRNv8UzxRVJ82JZa0sKJhJdwbKYjWcSWRTVCptW9InV8Y7wskBbE2nL+uphcGIBLkw5Ln6+x5RzMVSadC7TGkQPJ1UAoyfTOItpqRx8yfZsEHnoToGnGsFM0TpcwxElDlKN486RShOQfEkB1WULKocURZUTrNxsL7gRW1IpjMivW3y03gS5vP2SaFHSrGUFlJdLSRyZH+ghDjXLI5YEjW/xxJH+MF0p2nXwEmDCdo5Exl4nLlj+HZjhcoQA78VAojbE+3/xuH5ChdI9t5GY2lV0t7P9E+1dc79zL6/GCeeYqVzNGU2zo57Z00MvffrKMkaWh7XqTK27aGkfsYmeJJl9dGG5E7xmg5cjq4QWaDNVWa2t0zW2/uHohk1zVE429gH8+smjfWiHkquYAP3iKaSV8MQplRd8fE4DRFFwr/lYgSGWP5ZDz7dXH6IDwxGuhJ0i7bvprz23PkL0JBi+6tITqwMS+/6GuyP20xeoD5Cw09e2cHFANc7c8ieW1QLEn9z1e2Oac3HsE05f56xEMcpIGRTgFFwfvMHWokRl9SOHzqfysjkVY9Rf0uWDziK2huSB0DiwLkWsKGdAyflxz3wrID6aOT/uMA0ybmD72DKBvDZjJXAueMxh1rB4ndFlaxItlo4zRmmoMH/L1QX4XXkQnccjOxx+kkRmRtT7/TjhJUrxrg8XD6WPkVCp6267pGQY+bzbbQhKh+nuPz+BaMF4BOvvtVAdyjbzIpC9JiDT4tyDqFxeOXKK78IDSCQhx9EISrgaD3mHw0f+70FSnCXA0VqIepOIkEHZ3OPkzbwaawK4CdVoIaHxnUm67/dVfKbij3xp5KgNoO7cbSnrPbOvbAr5d7fWzDeV+2lbzex+R38lCOLoihtrYk/X6BXSE05q9yetMCBDtq9cU4KBHcpEMPG42Txqd20dWw+lAp9T0QNTr9rHHx0SiVc3nsylglG2FQPnR8Wq3+958iaErCLHtijXmqDv8RAurIhY5TX4vAxRqbiMYEpGHHGsTVNFRPcyLAJoUdm2+B/u8eeeZf2L7D3z5kdG6Ye41N05+rPMEUumPEElzsJrxTBXTYMgZ9/LZ9+SHCJP+3mJTjBk93KH4j2n69HT6j5tpL7it7jgQQ+/NeDA8cleTuhp0KR406yJBd5ISn0CtfuzzzlysarwfgnDeaXVKSLmmIYbJHE7kztkD09UvDQE69qKnc78lUDnmm9wS+lhnE7bxGeHdmesu6En1ghZU3eLJygX2Sm/2pMK2bv8byCV/XfH3dFCtWMR7eXQ3tiMV07IQp6zRTnZLspm9I0BATdkCJSZ7MKKOO9Wt6R0kmqMWblBv29w0OW2hrNMZOTUzpZkMbaZF0jx/k+j7LPMf8VAgzt7ZVptPeVlTj3yvDIpDwk/Ovll+M+36nR/v3vPfGU6Jsm9wzL/goUxCAJfivG5+6Q0ZpWKNwShQ6SBOLjm6nWGc1hfkeSDXkdE/B1VL6R25gA0BtnF7TSYPsf0KXWHA5UclQCdjSS68le+q9wpKimhbuPPAcVchZQBXa8V5dzpXrbr2XfeGK7dKdUvVqjeAdHRJv/KoDrXbbKM1Jds6RUg6KahC3VJcYuYgdCjVWSYikpaIWaI5pXKXZnlM1H6dpLgRFWjsPOvuHvQcgrfq9f8byEyu7BRYUIe54OoGSzXoi74pi0FBNjpnfWc62RYQLX8O+PA0PfnI5RtPvGj2oZWpKxmf2BmBKxLAclQo0pyYQZEFhJy2yqT7s4eg8bqGRwiShDycihyD76oR8Xmw7CrVNF7wt1nKZHJ18j1fNeW/asQS0qfscFumlEBaes45YpaWCNbFdOrSWKYhd+BA4kuFFty/JRvKzsM11blj/PHoN79fB0AnpFXIxHfQAsUMFIGpWyf0iUG4U5F4q2HDynqEahwZor/wORq1NA5BQ69458oz2RFlYqPZIZZbcrmgEVsPRQlgDLiwl9R3fAo4CbZNOfkji0JpPz2TJwf1sP6AEYIWMloqIBy5oqCCWz2xJgucYRPVtrlLwleQZ7DSL7S4Y22wQWLtbBCu3HbmnfAg1spQlxxPNnQ9U+jccK75X4qTxML6T8IAmgQwoBclvzd+ihPT35fEslPXcnt3V4aP9YYwOfd0L7cAxYH7krQMdJuw3Wlb9sKEjLx9BULjjYIYk4B3q8uX4FadfWwxmwqk7b9szTLqw2j2/fG7v+VGbP/KkYYPcqwC/nAKczdcF4TlnqjVsuoWb5wOIAjedwa1HGwLyAYXplQU8xGSbT7SaGw4ayipVbaqgyo3WM1hCW2Jr7JnvI1kF4oRYqgoq0kHTy+04Zx69I0/mQbco/dWw+f3TU1DbginljSPaFZ9zj+yfvglceDlZTJV/GLjWJ6bATScAGMvQywIMyFyNjNicDKQo+NJ1gNOoGV0Bg/YiXhcboQh1tPr9ETgGTZi7wbJhZmonqcnqwBwUvEEQPoI2bh2Omz/D592RpUAF9+N7V6xHsHV7TuZgO2HsM1PtWTASzslungypYJ6wWCxor2XQkaruBHCwRbCWyulOdx+2id52eUdgiPF8lRLeiEwR1FbvG1v19gyH71Rd6wKnCaGWENOYiOXank2wEW0utYHdvmPKZlH5qK/GrUd4syjXRUNiCvOuCtE6GhSGGQVKNbQ0oBtAT1kR1tCUYw8byeTjBZVGUVQcucRSFJntGE+R556c4iV0Ul8BLp/1zsKZNtiJSYbCxxqdeBmQ64vJeury3U4caqMCid/K0XDnlwIOuZFe9lD86kSj1ZWAVF66/DotLNYMzPaWKkcVnVZOaMXSXi47cp8o1PZRFxgpW3OWflN8iQjkSxJXgzPjkEpCFPCu5soM6iPTgUuO3+PbP23acHDvl6l7d+77xlxM++MhbIaoh3hL7uYSdhZmqy8xUIfRUChKrSiO4eh9hSZbeFZIIhbn0AK7+dQRTI7tAnxdIQPXANmCU9RFoYjHAj7qJvxsuaKwSixRfNJji+n14g637UNK0hW0LfpJdVspSdBBVbLLphj6U52DZ4M7chdt7dHUEJvTPOgJ87nXXEciRhCplaZYTomd4Mycy0/KTgV0HyYBK/ffiZCksByqp7X6wJAGgiZ6+ZpBxt6ubW0cggC25HvC4pYhCPrMJzVkLVQvhFOl0DGF/TmhVNpkRtqyZb5yf9oqqbsi24pA3p2zZAeBASR4/nm+t/Pl6pHD3fVJ16fVVMytacLHUEzKVF/iyY7DJ4nlhAhT8vsjB6Xk7Iq81V93Vg8UFZSC07ZkyadoCBkzbDFDhHAHedpUqw0Wjby4ZW5tWqt9SnEh1npoXsqVBo79da22w/0YN8id8fKJlDcExK0GgEmjKUjUxO2sFhyyu6K98UArbtus9Xq+es5LlvorBGg/ulwnzB92rwO1VK6aG5/iumEGnmKX4QwPIBUAaafky+ZqsuSafJ+gsXuDK+qwgl4gNGfTJThbl0CTCRa1X+nq1iL2CdRgVFKMprLHNkM/tbkFNJdqaWhYHmas1bflwniaEsCYbRGdzD/nE3iG5zSlDpaGBtTSpVvWfeO0bUj38oQCocKIo7z/ep4YF5Tj0VUYyXoJ7GMGimwR5s+85PjTzZRHRrHffceS68lezfamA93eXR+v1WlFsuMtQFF7WjalkVTOkBQRiPtqJyxQu2aWA7CUVr8puhlQ9Cugiz3xVTkcpAUjq3RbzXDU3WtCwwwAVMgKrARWkWNmmKIvUDU6RGDV14qGWMrcWHTafqdAhCrec9jZyLPkmxLIh3muCzEnqRAF3jp9K3mGNv4f0St7UOh7C+bw+4acSt+78lssc9vWBuJJeUJgadoFWWIH3SkDgpmGnNR0CXqhGtjws3E1IP+9ilzKzTf9vU2nIfGl7l1Q/9UMBadCWB9Nurukp/9GP96WPOtjBmUErqi5VwIcSVnKkT5Cw6nzalgJq6TUcD+YMA+tLi4CA2V8qOv3TEntBttaSPrdhhhq6OI8GSffApVGDYtn0qSnQmVl4wFIi9P6BbxVXQlYRONklFuIGiu4PDnKi2ryQKiu4BLKiwh7hfCpl5JIMGZn64NajZGqdFTi5ILzds7UOtAt0X9D29H7FflS4PtylXpqn0RqegvBIgNyZCby4F19PRJUkfcXhoe7YwnQz97y9SShTVlYpIjgQ8dJBN6uqPJVKa0Zi2s94KJV3+vCzYcgvC+NkTlinEkwI/3uaPAxFGxhwezJL0uW99abx+fwW5UxtqaxSMzohaEFcLiKfgKyye3Xw0XwCvE3sek4WSF1062tOuNKPq15QU963LYVsnNkRdB5lU++f7rwXT3gRWc3o9VI7m9F+5OCXdoOYSgF2jlbX3RuWn5fo9wfP//Y+Z5X3cVYEodiL3V7FiN9cOKB3afkCR3wAFvCEwyFNJIfwTwa9wkNbNiz7OUOvb/LGIIUBrRKeUMQHy9qSQoU8KzxDRQh5WbFP/MU0wUxd9uv7Rs0zgo1pGm7+fMq5feudykhFlqc9mNkOapGwdWye3GW84E6dxHyJ1TigWQozwroWJuP2xITXEWYbmgNwUYiPRA2x1xPsewMUBcs/1LFB0VgpqYadbbDTD6ceAVRWosuU7vANr0w6BEp1bOrU4+mnjy9odxO1PEKpPdSaHtAp3ua7ZBOGh5KE2QRxa7q52mw6PwLLHYzacCzsDovADBa7C0lKXVFbyT4XLUu74CNQnJ2qONsPvsQeXYp/qVxMGF9HDmbr6QGKep+3xi6sVqaEoQsvDoupsmrrHHC5RZGCrRnZh6m5tCO0UNmV6hLNDC18SDUsmCnX+jQc/nfZ8D/co+fp6khKv3+IK8zN5XLXxowmxn8NFGO8XoCFzxj7XSHyuOVEtIePpBTFC1vhcWuxHA/EkpR14pIa+JJEGzNGg6pek9zAan6FJwo9JD6NynTKOYHERaZJCL/98qpjRIybr9aLPnluQ/l0zX0iSQHsZcWZAVP7aIkgrspb6DJjYvG2hanI2K7HIn+eSCvewbBw7z2yd/mnRkEuLC+Q4mvC6KAZvlKN06v10HuE8thFSwuWw2AGCywP1e9iO+vzTSE4/Ti8qwR1EAQ1/zbCmtU2JTHyFIcGHQvkAlf11hYpPeo+icAEHpeSNmNhofs0RfEb04368rDw4TGPb5UWwAAlfeb4WBn51QnsLsMoqx2pPUPWSNWQazezc5BLl337p3r0SXPfAewomFn1Adw2vh+PxNzW0/G2e2sFXxWKtXbdBeqmVy2hDAVzhigY1dPFR1EUyS9Uuk4JU+iQ+CK6Tw+9vjpuWtYz6W7ykMe+Z/520tCH2LTJ4p6IA5l+nRprfMyPJUYxh1CoOd1ivvP+1y5cvBEktEC0+Y4D3Z7PPpQLKwnQfus9e15OCGrfzqZCfQtRbDB/dDRaMhApitKDnHD4iARaNHPUSyKr91Ssg5gHNVvkMWdcE+oapyCvhTq+1L1eF74H36CMX5MxajlEBwqmg1taFjemOeZ7xvoEnlAmUWreH98Yphg4US16hQ8yB4KBS6BkAtxlXo8MzFL5Ben6xq/6UCc/yfs7uAImtS/W4S45bk+ivrFVwVeqThvReA8tbZH2j31BHj3Je5TjUPPmR+i6pHbXvzDseObPJszD3fmMmcsa5aiuYLi2+jg9AGeOHbTpHRj8WSgTPtaCilIAOi5HJLAGHd1JhLMoMKssUgbQ8dPqs49JsSWz5AvRYRas5I6dd0gEOxK7trmjkWBM1Sp8s0SXDF8qfFDFAXdLnTzjk+lzFy0R5e5CexJ0DV9iIWXGsRYIcs8CVgG1gQrdcefgTpfNASUbsWBnuSFo4oSeNUJyky1m4UDMIuWEjbrFbTHmbSYQc1FTYu93Gg8n9j40V1S9q9sN2IyhNLmy0F/XpElup/8MGrr8ZipMGf9N2cEQp8XMeCvNSR7x4liea+HydZHDoc24+Hcat1T5PGnkcSfgH6pUpoLifJClBr4b0+K+it7r8aFdTNZNI6+a+9ppZPnbQ+EzzQtS2dL8gxekLqLxUKGMgWHPDk/wty5eUH4W4KFYyMFno+Te+zGin93Se8BtRQh8sAkhvmdjFNew2zOX6TIArdUwUjsGnsn8H1ewoH1kQd9l13ykTvyzXC+RJgyE7ZWxROXOgTT4wTlzDKyfNngQyX3CZw6X/BG2dO10sLdKCo3sCMJp33S7N/mDJDWyqZSGjA8aXOZ51JXSUtBEW8fX8R/02sRJYAkNRMXPf8tSj/rk/rhmF40eWNb0BYlG5/7JKJnKEl2u+A/zUfwPOlo2T0StOLdll0iQziPxEdm6/Z+AnacCONxz+ZmmI/7MBkoqgjDDD9tQjAgYPmOMb6cCy6cyEDYnnovHzVJtCLZrzpJHJcJPhH12ldtyNM7swVO6yFzS3+jeNzJLpuLMithoXB+rR/Pl4xWSPQxcED0NnM/pv2DBDQf76vFL+eKQ9qL1rEk1pXgODB5vQJI+TyupXhO6UXBSQrEQXU6yNk4oibbhPbafx2/YVwAhLYQeXjU7lNuUpyhdmGZQSdo8mdv45H3GM9tKUzZEOuhZz5YXHqrOpdBtuaURAzwwgdJOoDKFz9+LZPm31v44k8E6JIPdL5vQIUKaoGPX+43JRC5pt8lkONergMIL3X+c3RD9BHsacwNMlRYOQP4HIhW5JVrfdiuuQL0LSVZX/z3DAAtT3twyG1AGyuBUTlmnBTiVwUOjMsq0R+fV+AMmruyb7GMZqmxqNfi4whM5eWACTzVxvnGIf84ZH3Z9XAeS59I3buW16BPGo+t0Z8Z4VZVWx+acShsiWxU3gjW3f9YKpV0eThfzuZ4vJ+KsDvVGqWRO8sLMDhZgudizObmlFlFY1q/Btkv7zmxr7rSpyuTUjLni8k0UPkIfSWXw/Fuiz3IewzV6xgBsFNrB4u8EzeEYk2nEcHruLuRAHnzssr2TSuogR1WUqY5x12zdZJwnG4n1uNrPpuEAFYG3yRQlK/vf4z1gf0B23hiyI5KV41k9PQFgepL9pZJrMfskl6KTGKHzcg/xK7Ol1apc8lRFGyxDp/kF533dEFZwgPhkTHTtJthW2lBDHVhZNf/YESqHx+CuXzx6EK6fiPoG0HF74uOCM0g9bhKpuCVy0Lr5JZ4odp9otXG5CHzHlLs2hrhAwyEvR+fM2m5NW5H6KW9Oob+n0MdcSZ21d3pP2vcDmH+AsUJFZ6JhQOho/XuESXSyS2ip29BsKgRn+1NN8efX2M26ibuXV+8OjDz//mQw92gI+RByX3PzrPyS9d6tIIL3yKBr7WcpJpFFPpVX1AJBjdMlPVZW+hGeTJfa3CTJrTsH9+//Uii3Ci4ydyxxJ52RXBa4U9kfyh9hXyh+MKiASpeWZpnxYs/EGhui8Rg5rNbR+DvMh6RSghpalhae924KucxkL9fo7BD+go4YE3vLB6YnRQL0Fe2aT/s4ttIjnYYOxK+kn597VWefS+/ss9AWv+sMgBZV5n0/nqiPJxNUlMM7tj7v2JrR9DEB9fQOP7+JD5zuwd+URxdRrsEYgDzlSJL5hh2XDnwwAHcsy4SLYkX6rMW7uWxy39RP3D8TzIpnoIqKAQtZf9n1ksUsq3mpomhAKNc/ebPdNclf/F5jo6mSc0C8XaI+gotnwBLFPUbMcPhMTcdpOOBLcjNxpqZfn21DtWWGaqSYapArN2xZIzNl4pfUZqWkmtfX7lLVGQmv47fqX0ntkIV7ZugR6zH7NBL6TzV/2t0zAezKQRWB9SFIsWezOsyUDU/IhSk1VsOyfcLdhllIlUggpDu2FNPxZoH12xur3RQz7IrXBcQrOnlihBmHXkyMHIlX2fvj4JTssfQ6uoWUPQlw1XoLs79XjOOkuQf1TMeVEd79Mzw0t1WY6Pwlujchdfnx2FTvC1W3nrRKvlitnflb0UGA5xPZaXXsU0Fwivs0dyCDUrYWtASy7GXBgm/IRrIsd8y78zRMhjAwglTnzzoooRm7K0boVEqe9FvpoVAUf3HWfBDfKyIVqEri7XBz91VJ3Ji4ge685xeyZ942Q6L1lxWoGGkjns4Kxr/GNa4fsvX5iinff1wrB/E7VA9tN8SPJVucMrdprCcGqsGAXzDillHcyAmen7q8dQcejwsemo8MgkoCAMbWrRKc+PlpkwOZkxhMqwnqAfjhFuFb0RO4wp1sHd7/SnpWgiibxchdkpKwlU1iXXkDmFkjEGT2xwxhbJkLhXJT4iVhVTJxaY0JzBqmXB3JTiKPsiuf7xhFmtr9DgSjSLgi2Xq+OU8IRkpr2X/gzSPjul9/pYZyRqEw1LpWJ+MaBJ5Me+GL3LC0dSr6nFZo5TFcOCCR6pknXsrQuZUg3kE1mbrJV+STLwmjdJwv6pY1Q/t1S/M2DXY4ZY3aHpFqMejHXFta0XeYctBC8TTpDMQKypF/6C+l6BMMRY/uFmvbTxn4U6UZ3SlAkwaDHxACaz/ppOC9QLJk5LmARPajfaXpYDvtWOcX4ImAK082plJeKmA+ZOWlgmREUv+AhsdiGv8tj0SfsKikoFzSRv2XCcvDA9UpiW3yQFKciPw9nEYqJEGHm4fwwVLmYP9YYokHbI8PDfmH2qUJT0KWHaVwZ5EdERr6oSWU85KcoSSndJ30y77t+FC3I4238ppOQXc9veypaFJ1R7IVZo1+yCkBvXXLitZeW2/vW85qzVmmOOFt3788ETtKbeZmcRddpN9CqUxrOmohnZdrY3ZggcuVXWeLJM2TSZp9u5luzB5v5G2Uup95lSHU6jMHGH+wDu8yMFIh62Ffw5v/TgLAitFkaNQ5B1u9oLhKvZ5TXBJt07wdIImhBZH7dvlwFvNDT7Ym3RjB2ROjfAP/5XQhnHyAgSC+lapxGvCAo+dR8yeVB8kTzwMS47KkU46PSRFs0Ih3ouR2kOSkHZpI7BZzSVJHs1BpX14S/0NQQEI4JjId1WAgKyYoFJpiFqnIYioixxan5KzeK5DGma1iQGMUUR/T05lhvE+tLfuSS4mQqbV/5aWdc51O4CH9i0CANNe7+dRNIc1XF7HxOjEfCI75jlEpoLIaF4TH9ZZWMyyuxXJHwHtGJYj7n1LsaVfcQg04xbNTz4c0DynCxSL3EHn5qBZK7iln6RLo/XlI7CqalK1RQ3n6e9xbW2CyVWKCD6P01ROiLAgkUfle2SlzexBOTygLDyKBl1KZrG+IJpyNJg22d5RBA5mU1ScTHMwE30AwV7nSkiX1nJscJ+jXfUu6hPc2+OrNoinwVMBkFnhBLZh9GdBQ8ikTcMMmJFDWmRn7zM8rIitp8hrgudmoGMk4r1UeR+ZY49mapBEGBvu/tsm7Urm4ZQPdVMGQougUn8Tb4hekbdCpI9mSf8aGkL3NL2Dhlxb5A4KFXPozjLlj6z1KG58SpeXYU6UXcOp9jFj3sSuHxrRHt7SvIni80ZayP/7EbsofGqig+vcnnsZNKppMP4gy7zKO7HAyWcKQEZ4yAk9rNS/agMmevDq95D6nkb4YjgxZLSqskD4HrvZD6SGtukp9+CGEhHY7ugZc6mnMBwI6QGvAAeCn18Cwrozt7pWHdkP+m682CSRFMGDEtUR03QrbAiscvkxEiygsZVFr1kV6KnaJTIys0swTM4ndkxe4DqHlXY+8313UzhThGyjv9n7UIU/F0QXKTt4aApPfegRHIMVy2ir0ik0wngneMZ0UCz2D7ctpQMlo74Wr9hdJonToyGfAunblB23BtS817gJiTILKeLbCXZFR3tau9Sy+nS7eQ1MeNt/PR3a6sa6q8//Q2ogZq3Ovvj+VQPbcmL8zRzzIskv+Ze+g+uQanLJ5aUt0tbIejTitDSvunnW49bH0bQz2T0znf2XO6HskT7rgnQeNit6hVhHiAvAfPGyhepH76bh06bF2Nxpq3DDmWlZ36YWMM/Z8UBkm5x4fosGNoX38kUuiUaEyVqcmqCigGHjZ52hGZLieQh0WyoImsuDG33glRuJz+rndOwhbqacvTKtqY1WbjKI4RD2wie1W6EjoJx+47MvN0MQyXYTu/6AYdFymV4ZHq+pRBacPUQdVJWTU/aLBuuMgGjVWPcUrndISpc7AJI4ARY7oAqJtIQgQBIz01aZ6Tu1Wdb+iEIahzWJh8ATQakYKE4Hje/an9C69pZEzuokVY+Ed4M8RPqVm3OlDoA9it4C1Te51HI6RweSQhVXXyrsPyQSBiXltWmqz1DBxNmAy5ofRAs5xWLgH1smS0tvW9x6nyk4m2ZtRzhEApqbZN68plRcE1ukW6wIlHya2F2gZvl++X5kQouvvf2PuIuXEg9ddnhDMiZkxcimBMHZ55+nRSDIrVbyYoAtshNl7qs7EryYzy27PAnY/gbicvhMZ+fMiTtkUMQrYLlfIQBotz8OCAaKb1bRn1Ai6izxN3XlsEK9HKglzU/MIhw8mN8wTo2n7dinMYsXFLJ7shBxfM7WYPM1Ogjr87UERu2RzRwF3GCycKnqGuEyXJNurh8s9zZOFl+eoA2itrnjRxQt9kKcYMCwdQI+pSUqU/KHmvvCZwE3NXX8FSTDorrIzf/lJmWekkLagTBK8OAOrF6h0Dnt+3T1jy8uuX2kOIgG9FE/r4GcNtDAYL6ZrSXtUZNAWqFwWSIuA6aF/BJPEFvZXCHWx8nXOM1a+eAYIrmv/YIb5Q4w6hiIj/svyxORJ1SZM+vRoCaXxoilLgWqwzw0JhfoAjoXTWRdzePAAqtzhT0troEk4l8QLSoKdhTm8I0hn0zV6nVzxZNviwOZkXJuAui7p5b/FJGzMHYe7GIMDNHK2P6B/Bygo1hVIs91QavEiADX0rNGdwCo0xZze7KJTQDBdKDUY/imapJY90tCDJWEuJCK2+joKYitu+jaXbX2JaW+2TDF9fl1gdyzwQmote08GWcUK/Xr5WsqzzzUBWrZyesCjkWMkuECgIqdGTmdIplK35dT75wJViTTwow4ub6/M703oQNEgVCf4GUkyfurew+A6+J1hFrV5AJVfPcV7fzJHOQrKmp9pUPPLCIx9JEOObLu/ZEh5Ms3n06mexlDYABkanoI1U/m+1yoGSldIdTtgzlmJtiKDhEvkjk88lIHdOr97B932E8FQV5NTrnDlGoT4DNlatjifYSK/LMR74uR7qL6zH3KKvwpEfyXrHPkLNsfJloL9etWM1FdO3dXI1gIGt3+/84wv7ZCwwxuntn7K7ZF39AKzJXEUleRLZQlG351LUM/0mWn6nGkbDgGZ/+0xmlcmxmsvGVcnwXPdWf44c6CXNFGe8VkJcuEEV3uDFsZ8dO2ftoucaB4Tpnjlx78iLrSld1KLS1iA7qFpsZKm4Lcc7u5r04gkRA//6U7pY9Gm66qKlT0bglJChNHhssVZ40r3GFLvO6TpUYLIxt1vUiW9j8wo0PQo9046JqGCCkBN3+O/ZC1ZTM9ito33acQqlylK6Ey2WKtzwNMol0KCdy//A/H2eTflgpxd+zjleMR4PnpPCMcaQx33LwCemhbymF+O0S4pvK078LYQLv8Tz5jkya+Ol/2LTxGOyGIKfjZ4o9DVHyKAg22FSEnlmY+oABI2cDLb2zdEQMkGczUkhQFedleQ3uzk+iGh5mwltQT8Y66tGPsfQqHA0vNpKHCDH/jhQIR0ithR51oasVF41uugcAHbWkGIBrp/hbodP5dJmxwDWSp2qnGrHPJ5Ybk3ZNqtrzHmSHSwVoCGvQyyApF9GlX1IR0R1+14+60Hy5A6MdvS4ZnXXN0KeSujN2XQakHoIkzihTaOAtGlQDnyYGQYf4A+xIzX+DMdRKohNuWd5BsV8Rx2DIhY0cDYMxyF/lYGmL7GXB0Hke8JAgMyUIGL4c/etwygPqeMUP5Os1Udk4uM4QXtIP9U80gZOa4ftB3Aph1cl5hpqQdTZT4G6DQJjXNeSa/utbxEFmRiNVfNSK/HQ1kcxas4A6TWE78lOiKIF+KitQSXv5Um86G1thLCu1MHxfrlR3GFLef2Wk1l+a/HITXjLez6gFump8itiefrO8QMtLbdPwdW4L1eIFnBgB5sIets2Xmw4c41+43GKfb43qmmlLZClcWO2Xg4xmKDdCRFR5CNyFs+3ucqj2ZadGTL55OAj8AanpCA62lpE8ICv02YWhrC2PcGHArOdZesCU9wO7A6/nieg+RvTHq6ZEQDWyfoIoED7rWUsq9KePBx+89FM23lOvBen49kjwR1BQ6ivXoPspaHxyfKHKK36vsIwQHk+1S/xMie/13UKWWHdgJHDhz9yjdeWinLknlgh0YXUyZvhWajyfwn75yhqEpuExJ2kN36y3EzYEPl68PtFmF08yOXFKrnBge+rcbXNP08V8wZxAd7ckl40hK/c/VESAlMCx3+LufLfy/r8Zv2L3WQU96LuQAdxj7qUyW6QFRv9d8ryOxheoEonUHtRtmeT7yln3az8ES25Bb0mj8FNi+kJfMyGuzzzxbiU2Jf2sqFHKLpAgEps+2E5O3jveso91KlAyz0SiYFCtvfN+/5+G/3dMEDmcF6YhSf+lCGf2uha2Oqmgqrodz5Riy+bBJ0RAPitxsmUdbSAofhkwhTWqdWc4KnKNBUjNqHh+ixE7UUxTIZYeqlwbS2YxQ1ZO6p9dr0aPu8FcKgchcKcpDEJ38XUPYUlLE5FyftG5eocbY7d6DRxM5J+uPIS/H5VBDZ3JrAK+sWOTRrUZ3RmzC6v5di7dEzQRC69J1RDzYFoIEtatrKES674o8hQNO7xl1CMcIR9WYtWevY9YtfNbSOb+k2bx0L4s09gtv7+UfpROc4kv2xInQuSYXP/D33iL/7BwF5KK9YDnhshUBVX8WKbKOHH+DnIVFimF5t7UDtdFNh5UHyGcDA0FIAVPHdqlr1YLWartFDZ7c0Oj/9xrSrTE2jvk/BMTjqNMKcHfAIqAmMNG1nBo3QiMIIRA1xAzSfs8VuwwwFUq3EKy/jwU25RlfHgTtsv551czWiKJGve9do747mPLSxxQz2unws4Y45VZ1xIJHtn6iWC9BB7+jF4R+aKbJv3BR67jjn0IM9cvU7cCoZWBBpCfEImL9zH29xrIME8YcpzAEEkoAOXzgup6Wv+Nl1FmnM7t9KCEsrsZTVFexaU+MKhH8KvW5CoyPNhE/GQDVufOVVOWDC1tRNUG7bsuYe3Ibc/JPpYRFbPd8TMkH4vBsKroDGLViA8CEP4iDRwhG9iFQ/do36ztZWuoDGX9l5liLRF3cv8xixdCzyNEN0eKgjl3y8bf1HZOiJGQZQHHyqLxg6dWDgY5/OxTOPhZCLCjoR92CjfqBD1pyAShTBZIoKha6IExrTDEGWSIOk/qHRQngs8sqhpwx2nrE9VWVUceKG6RgD7AdI8Hz4Hg7fEMFfkw3qaOs1IVrgp8xnuZTqhct5sSronDdUdhQLSs1ha8uY5tecLfDYQI1CFLCB72QJ2cCalCA3MtHgAOsKayIbwAAnK5NidQ998+VMjsHdoIrYUCTAAIrgzBOclb3nt/9T6kFmGWMMKxisgzLIDM/em1ts0weQKYZsVvbHKkXXJZLEJj4eq1lGmCHDZ32s2yKMQIAgEpcvjCFew+FUkl2rWpwnm9K0eD2ykfmnZj/fvLHvf9yYNeZY8XqhySu4nXKUc4r76O0SJJLT+ND6QvN8v+XSU/TqIi8PcragAGaQJQcXk6yejamUOl73hZWy66bt2CnD/gQzWFWboTzxiCM/11spMx3sviLK+dPcP+FYfKEB2q0SzFbVZrOSHXUNv3nqJwDmISe9uAX0NAz9FOu20Lu5k65I3W0s8ipJ55Q7lXh0GnPqm7FVE0UKwm4avjINNTa8wE6O4Lbx8yBnblDKDbWra8MkpqQa26sHBzcZb6jLVtgOrWtlhkuznEKiNrNZ83ldg8V4SBAhxcIViBW6kmT/p3Ga5AqH+cvlpTvjRgUTuK0W0V6scR9fOVICc7QPtuIT9fjOnwKB+yUmn6biFd95I6gf8f5v0d5DgpXpZ+Pe+qNTgA6m7XTV+cYl0ha/eyDQge1dKAoHDUeG2TqKnykvi2Qh8fOnZYssjTH21IjJ1/TEal/YTXRAydBL8UhooXmtCppTw+imhpjyTLfgF8NHyeG0KnvH+7RZqHUdHHaU7/w8565uhqNlLhstk2qtNRU7FLthA2WqLlnyMXUP37oh0s2GruyYpzEaEqJAr4HwVxLVB+B2ate4jAdQpISNSdtkT1QK+zZWeahgDkmLpKxDxImMU2xGSt3bobsg0ODSS6bRnG0kxhQPmrBcbcGEVgcjKBcfNLKBUXN9H5PUCPDd0Na4uCLHHh76a4lSwFAQymxTQF5wp5FwitY0Se7UBg7xecSG5NikCgoCYISJ23/BtRcCTup7lEUoml7gOZT65V3i9Ia16jvvcFMLCT33MmN3YJjzCHhHh2s/IQt0BP79z/b8kdUbcoglY1H2yCGAwEgtCwwVbXhqKGaFSDgVwbCAMusEp/Ys9+E3+XhWOhT71bjh/hnAsoMq9MUQ8V/+eig2qQdCBfbYCJxvrWCIHsA1zlDe6eExlYUwJ/W//+Vpr6pG0hxVUbXDaZznD02NmP4rXo6x6cltkZM9gyEXymluZaGQJjABsthgNLOS6wgeIm8yJnkmewgkKeNClBmwnQO/gulP5UVCCIgamcGIKanF8lDFElqHwW+NTpANqXLaXv8veK+WCskQSzt9xfr6Gk0RQGypiPVY2qAxmcXIl8ImmcVbM/+m1KJkC5DNdXB92d/Lj+dWIDVmMgY+yRhA4bcWyDPoQcrEUMoAI1jlxcHuwHpTw4+OvgAbYzZidwWdAygRGdhAAe90ovD51OR2bkvCurMx8EbPsj30TZWUsH8v65qd/Ds0rR46+CfXgNiLCLDqN6ghsGFQJfrERkPMIuV0Euwdcgs6n3ZhbdHPJ57swL/RaqdcNLr/cGQYXCF10jEypF9IRFqVne8KNJkKq1Ojw/0VmcK0+7SzJE3Vg49twTuqh7S4zhyB3KzpLpKAbCr3dB5l2GpWAJk5/dHDXwI7TpPU8m2Ak+WWdvXPJ7dEY+sIimMim0ScQvq1n0M5YmHHgPO5uiwIQNAVOrtSORq1uSh4pi4PZIus/btTIFnZUwpfQWWcDImYqdYnoUdl/DmopNX99PufEbW6uzfOKtnC04GX2LhP8VUxrYG9A5DkdAJ4mAZMa4hYBfaN1ywLsAJp/Clbu9+RCxRX06xLzXtiARnFfqELGwvisWE0IlOceh68I+Q7pZ2bLLMC0mHsuNy/GnPL/mTvMY/gnvlLiZGYwcUJohuYQNkR6+gDnzQ4bxHAYEYONUnXqeKesorbZJ6cnO56KDtBI+bit0IZQiEaKTvPuG5kgwUXAtPjL0KAfVXMm4BNcxrnT8WgxvpavklsRwk9E+XDllQl0xjoN6hX0dycbNfqGKUSSAuFQJrxeA0pVBIemqKw7idD22srAOUISjsJEJBhSXuR3y3EPhpr3kON0gTVzekUyATzqg/NKzO6grZvKphX0+CKRKlNhUhQfxCjGMNBFe/ZESbHZzqH5huq4ypXaE0V5LnjNhU242aqNtDIamuqAL86+59Sj06yxe1AaKRcdzQVC3nZqjQ/8kpsVKP28wfQ+vPk4KEEAvr19FukbXd6PaHE/qlDUkymEYrfSo+DMPSKH7KgUPmT9fyh0o8Tcb2H/VTKOYCbgKPSLowv2ODCRg2/+mLeqov9OjVn33t5LiY+RuNkx8qgknQPDySbGM/OP/+LhCJQGShY2q9DOitZgYWbTJJ1lcJSd424lnGp7ei6qmbwX5L0pdK6qfCxMxRbP1jghE1ONdFL1Ivk7tH+8nDn9DoFIrMLQwR5J2gx//61YQdWshHlu2a7Z1y+Ei7MauyAO+dhje9mx6klUOWq+N5qpX1BAH4D1DG1CY2vCi5niSeeKnds6aNJEuUdLOl13UnAsc1Z/9DkUcqIucPTy1N3+jG/mHiIcwhFV+u2ZHuUIlUXs9FtjuY43XJt2JZDPSPFJzk4RTC279QEen4byTk3LvLLcVTgTi8uCf12xlDjF6snE9uFfvGWZEji2YGvJlpEiDDWsWi7wPRUw546GtZmKimU4N/+ic4myM8ftp4pwDbzdqM3FC/x4Q8xc9JLmuptBjio6CoOBUjCUTKJMYLTPYfmydurSIDSmVhtiYZtbw9CMkECRNqiqwZkgXjUHWOH/CYmSPY9p/mZF/r0850q5UZHbWmp/LusfP4+baCVkCr4KaXBNa6yogBI4U5Dbs14w1R+Fi1I2j4ZENvr8g0R/O1EP8kxRFSnClkksaHUKNX3KNmiiPAERlZCS0dLsE95Y8JPzQQiAYaEOU/8SDjjrvvgbo9mOHSuxBMph+U5DtfNxqWY9/SIZGie99j/UrPKrWyBWFsEwwNWnxJwS4fe0NiBwrNGFAak03QFTRs21hWapolTWRgGzw10DAd3ANgg+3LLz3JVMuG9/rSePX/t4/8NHYYhjqOULtI2rH1UXmDUT002LrBkEvQGb7Oo9dDTLmqETP1Gg5G20fbQn4sNDpmJbYeGEdwXKF8JqUawHOd4T6+moGCY0AimOwe2H6BA4NisZplKQW7VoK5M4x6b1aUrUDYECjre2xqhF+OBeILUsafBK5exwfmocn3vEcR0TO2M8yjvHOFElu5hJkED/wp5+1HBWmAMkCo6XHkcN+4WktmodBrWu/GopyfDQYBvBwu2t/3gIax6PHz30t8r2KjjdID+wymFvFJPHBOzKKmm3ETbltZYKGp2a2mVaZRATV5Z10MYj8d6qz0qpPjbD7yck1lKPGfPgl3O7zgm46C5dRfehaw5XlY1Ji8DOmW9XPCnR1I06mXwc6Qr3SuH2lEdISSJ157yCPmZBEXu+SdOwdUY8sF4y2waZGqkranP4xn+vPqyzWnG2pg47B2lcq+admsCAacpb03Z+y2AmotSD7NLL/eyHSuzVCbybNUqEIKDb51ueWuawDTVgXOfHhSOaClW17x1U+w09OSyNQ51C+tUstiZEY8iiw4paYlqiTogj9t39/Z/US8VN95oWXgwqToOf+k+ek1xhVZmvdnIMLB1DxXbUOqNH5e6jyiQyOO4z9TFluRl+vfM0+JqdVytzAa9Z2E+cAutR5dCYgO8zA+VwVJGir8zv9x15nPVDogPoA3v39BYyiT4XCbBSn4cDuzpq85KbidZcH4WW3L3/Hr0N9QVJpUrElf3Eyeqmuwxp1xRGg3TDdqFiEDm+swYwWodtHn3NY9UfkCby6JFEtKFD69WqEZ6kcCpyvWhF0kuARqKmby+16jIlGsrVjVxXoHItsuS0aeDG74eH0otZIevcx5hT0p59tbqODmCMEFiuzGfMGYKOy5kqBtjomq4CvVxej6vEtttlY+sGdNBLitEEweCckF/he83Tyo7fJcrewAEza/vQ7UTRGfAwdz/bpafX5COPtw4FEIcbvTxGpN/uO6gM2iIJye+LI3sMShrjaaRXW3sU1Rq5SOIY9K6FRYpZl1R58+4cSkAIJ5EsXlZ/lnX8KFTWWKdg7+0I0CUh96jqNN9bOA5Ot1283QADgY0ed2UZYBOY1MWqIycxuhm1/5pequZc+kDMpba6UqnvamL59+71EPR5+3sMJHykIf6Rj5R9CpQTz+RuO8fCpaGj5dIncOzghrotMf+qfWR1BVb8wY2jU0pNZ1so5CgPpf2kXeQhJxyUU3v75ZmVQY+BVWb2KLUBfXIt2B11CThmBjNhVmrmdQQIolC8/Pg5aU/VchEzAcv3TiSYCp66avWBmC8sYY8jsywC+g1TuXXYhcThxKgbvqziWtgTRFYHPhEquVkihiV1ygaCD61NhIzLgi5190H1bpOL3e1oqEc3DHD3L7Lwq/YuEBXrE5BTn9Jp1bLcHQAyssFLkZlXemIwovFeolwKI4b43S0+oe6am4uwGBn7myPnplea+PR4NJL2UUxgSFqktFIhzZQuoPNuJtCWhmkGZRZnYRGrGEzTkhpeV1Ll2UA0M8msnP5p5DZ9U1zTLuWjlLC2sNIALYNQcC0D+XiIzpq6uSeB2KIlyS0cpcFYWzHljWFkx66iucX5qEwxyWy2i2472eP0k9J9mIJEITOOiZXDAiTtDXdWSdpa4t75rHQdALW7qQU7jaRqrJ83KOmetLc+KQ7FryyrAPmcuMCf6WdzadtHkDcemRt5wcEPhvQhyR5Dy5mZzaCpZ5ayPEymdXC+/8GPoRzz3IY7l8LSi35XrGXeAjFIeykYgWOwf7ULab16obeDd8u07VYAjgNUVf7H7QCjG3U3TnCGi0ErqkemsuypOq2IyxVaWhiWdW/Y/33QlhpyLsIJixCT76xbAwXFNaiR3eNhhPBLi1HRFHi6vCqWlF60nlzCAciMqhuLZEYeV7YP7CiimAyAcO2lA7oerTHzds+sOBSljNVSLtd/rfEjkgv/sz52ZgqMbhe7da5aLequj2CdivKmXH4XmGf+yLpWa1li/me2nmYGzGhNIYuD5Fq7NvXiM7dQYvPz6QshiiCJDgfnnPVrMbD3alVUtrv9OiwApdtykN/F2oDcNeGprKraYFTyKO/ZiJYsD7CElB1+9qX95YNPrpqllJtX2oo1sibr+nt1SETVsCdY9pqN50Oqghmt87SZoEtZJexNMGyVLkE0YCUVNISdHAhoGmyzb6fYyVIBMirHNnKsr+UPgV/aVfIVmVR33pwaiR+YVaxE3/fqEN5mvsasmzSigsAlKOlhE3TXVMGyHUqm2tmz/cHV0TLtvmhw96aZkqmoXznnLxEPoFMYBUUfR/lMq2tX6B+uWKQmc8RRFyAOVeMNtR4QV/R/VMpTnWt+FiOLnBP8x6YcjY8846z4wI3CzqU9eizfiuNdIi7QfMAuk6G1H3mNjUPJai9gLLlTZIm6SlciKUq5vEIEFqCtEDmmXIBSoSoYjHPO/PUFFah+6oIFgojOEBHlAG9bcqvdxM9Zb39xcLyI6/pxWBpjnyIanY5JdDyCtBKtzAnG67BkJUBD9iyFTwYMzKgA0wwCjIgOTvaVrBQTtL5KL81NEDNHU2imlN7Ec/Z6V90mfLocr1VSD01JWwFvKTYNWvMS707RgfunednRVXA44kcUuD2bS6fGyBtLxQSE5TnxfwDsnPMaRhCnnPfRUwc+EEfshZTodBHqO+mUACF5CuTTFLQbw25N3gP/AgwV6xnIp945oHg8BfSx7YSSW3LF7dTNi1l8lwNHZ8rmQziY88BQ3m8J/iVHVTIjg34LSWngaoipqInoKFi8NLolFFZ/SzKspm0VPomb/MB/1oihztrgaIteN8U0XU3eZlf+UW2DOk4fzSwrh/IZqm0Mpq5JoKcE9u3/d+ssZbTFEjn3RvXV3bfbDSdPf4c76eynIDoxcUYcqrCbTITUq9q+C/lqxvjpVP65aHP53d6D22eSildpy2jQ+M6wR0HwS1rkIXNckJ2OfUWgXEeEG6ZD9a21i1IMG9GNMBUJ48Cibha/G3WmJ09U4IaKiCx/3sHamgbD4mNucjbyiQDjRhkrBnTBCrNh46IMdWKK8wS72qFzSj5BjwQWuRp9tFI3ph6412i3igbOYqMG9iod46dVmRE4jvya374W/joN2Si806yOJWUxgMz+aJGIYn7KiS0bfFumRq8O0izMj+DgV0fnXOrVFvdVvBHVKuUMZ/RhdbIQAtfnV3gV6Do7opiPzU/QqC62S1DoPZJnwQwMWQPwrwcPHGtpzd/DGhsD/ju//4QyGiVmYm9auC8WQ/xB0g2XKq+3aj7mpUiv0LVoGHWpfdP1+raDldwZDUHsK/nCG9pg5DAlR6JQDPEJ6dfWX0esc7H1s0dXlnGVuSJAUNSFAyR1GIfXBGf9Ifq152OGunLo3D1EyQlKKyIigxoS0EgEDhYMOtC2eThzT/XgnmKBRbqbBV4Km2PjqnRUqBx+bwCtDfQ2v8Jcjy01UaLjW44ZLrXEKCJPAO70eSzMEV0RcsaFExe4/6i2G2SYxDAYqZQtOv76XWke8RNxIObw2zJdsDXluiQ8+CO5Nm2KDOoV1WvBQSFpizPsZJ/+0yasR0uBjaBMzkFUyiL3aaGPv40cnzyS6dz1KakDkdhkyf8bF4xM/aBv5LUgUWze/WrmcHI6n7k1wIin18LwUN7GSGAmv9QiEEhCFNiDH1mGsB2NBeBWh50GhBw2Omg38VLQmkyrgT4zjd1PBsd78iJJUg9l8De+xLJpwNS7kkkhyWdnfGRxdKCehRAI4soLVJZbKenF5jbDhLxTZuYyr25NfFJ+6hAIadQKHV36hSA/BhoaMykRPdHfdGxQic7Op1NjV2sN3rKN1VJ+f5Jj/qfFtoaXlbMQEbwTgjsLlBCxMyViOChpKvdOU0h92JrQUuBzCCN85VpKnBKBbOzJV/J1iZWYoD/Up+1bGMh8G7LR/O4T84nT3poY11aHg63Ydn5EdnASPTvfzWGjhBiaO80jwNq3zy0pGapG22CN+2jS7dp/Pn0+Gls/QS0cjyo6mV5q8XS7+BYKBeW29VcMMCeoKm0FebSZIamot04hF/WZ3I/FQ3Yaw9ulC4ZC96645U37wDot+EkXkR+YTVUqz3D63V4QsC4XljjxTOmBIJir5fGcNjTiW7istd8AB4hqBgUyozgPA7oFdq0vJNpSG49YaiFyvDdyd4SlVnX4AOzaW+f0C5Ztf/KNFIcKM0AnBRPOvU5YbE6EwF6fE5n0oiinhfFNzzfTcG8HrIji7v6kSsfBin6cDUBiwr0plq2Hpafb4CR4PUpLt6SS2z1Gq8CxxkUCDUcXsS7OLmotGwqJf0JLeUZTU8eOzVsAr3M6QIqh2plM+y1CGzaP5nYEIKZKe9hmBHhqGsEUg+NpKRUml0hsZvws0BhaPPRZ9CCg4KNZGSXxft4MZwGF4emRqaAEA8SJwWiH9fhOI0gbCnj6wv/ZD/PVNUhdBO4PhQaWD/qp5chWZClM5RwhvsFTTqqARtgw+YkpGSlMM6oa9VT2DIteHHncx7/lRB8VS1e8N6hNSR9wjIMxV909OpLpTCSlS8wE0tztdq5WEzCCh9KDSK65iREQ9cMUhQeYvE2nUjwUfSmqFrhCMrZIT7mORSx5rZS1bbTXF7KAAkWOlyT7B8qu43UOjXP+0DWRYbuQJ1hMl9HqkuK5RW9CMynkCmN9/3TP1Ta4nQ8Toe8b58U5Dto1E4ERwKUFQggveiiLplzKFFlP3a8qoA8gmNrWwrzVDOSCtet9ZqmFpgXilc4rrDC1eXZGY+7Fm7EkUT3TJlPLOlUdtcIxUMThSa07NYcEilzZPdLQzUC9iu7a0JR16to0LbGUqu/xVhKBoTK78Sd0/ONpvmgEHdEhQSemopRw/0vFQj0FstM9bsgGDJEdcyqeyh9HdoObLjbq/GDQzD2HMg2qtLXJZaakzLQCFrmKLOLLzm1xRlzSpe1KNI074QMLqgrz3wbf5TBNufiwX0l2nqAK+jj2lX5C4jFtXtzi80Igj2snxn2/R83lcRkW9Ni/vjF0Lt3qHskC0gPt/kkUnkehvOtSaZIOUNFgs4U0Kdp28LJnlz98923bVQPZJk8oAFUlv8YaLTtf4+/KHGu6G59tp+Zm4XQkcHlfbE75mbbzE51F3ksnpQesubQQRAKSl6FRgrI9o61HQGRyn3l21UJb2y59ZgxWA/qbnDMUPgvtQnuXDCd7PL4Y6xF2A77uWCUz7T0lzyoS4GuRNo5BzUNFamLJJ7rTwkoiw3xdoLmQq+lTZ7oI/HTyoo1QQdxHQ6YaLBZkEcmXYGwRK8J/ks9ELZuh2ZcGZ+up0tfGh8wab7/e2eWuk5WYtpbt22IVKLJgCEBb/56HAZK8n5xuK3xwgUqShFkK8TLzBRBPJj7pm8fHlor8NYYzXq07UOBuG0VXvDrI2FIEcKW8cs1raCReJv6Z5oKOwcbZyB2eFxAsgdf5M/fKzocDp53FKD/CiIdcHnRyX/8UDZ0qJAOqolnBQ2Mz2RpTsGHpy3c/wlCBCbK/Fr3qBxAYyme4uGmFtWY1P1KsM2mSSWH2vBWI7hO1ZDZBFKtDDqNeDf1gzw/VH9Y0+rzW6FIcJejPKv+2FT1AkJWAdf8b4N2uL7OUuZWPLkQjloVDX2J6pWGUuseESdJu4TS6qkFKaT/5lAMGloCVFn9B8pwkZjL+VW5nuFtpYysMSXiHKgSTjH/SJjC7bpdoYvcXSIy2/jw0Aqajhd/UX3LfrCedVJWVY7llWlgpnDxYlkOvGgybq85uL2WfdnhoUWzTmk1syRRkJAVEgrAwRDoOlKQmzih37Zu+TwjbD85YoXa4oxe5BLlPowtJY/SDMnYIqPkuccfAhH9hohs9HIA+8SKmTsPeImnCYdrDPPWh+ELG2FSDQPfP2/InkCOZSFPbyZF8U2ZgMP+efY5myHwUtdbh/dlhygU3nE+CNi30VCyh4lTPiJIPTuNILri1Q3VNnQleQrcxQDeHxudTLKsdMZN7CPhc+S3UV21UEH0oWWLhE/it+Lw9yY0fULWDO77v//BGDusYbq9pRNk0v/w26UDoMatUKnRzNtzPFVKHlgY5+G3TEZOSLJ6xloPSX8H4znq9q7eRmn/apxbRXjonfMkfe+heIOGOQWirbKrrFYokOncyJMaFEgeX1u2snsMEeqQfpVOjxz0bW3W6bukhyaY4kVSbjJRIxp+YxzLN6fhwAhBHpJZ2QHsU9EMGw6+56wtlmS2Fpjn9bScj+ITwpYOHMs46HdizP6hHk7a+zW4fDasD7zYPpSjynWAoaps+tqIjnnkOqVQcvzGAo6AAlVE1+VerRASE/zJkb55VC8u/8cV93rb4st9uxpmkGcnF4/nX52xgum4nRomuI0mjio4ThYPZ3eYrOh7t8mLKOGjtfRKs6ugTtBtsTZPrQ3eND6prOCPv0RrzRItK1PRow+DvwRa2JZaEz0gv0LLMzmXBPQ3th1MXShZQsG7Nj2XJ2XdtLbFA1v1hDRIIfc6TIUBqALMkqVAOFNnO0fZJ/x2yqaB324gekCkrfRqt8rl8tz1aUtj+YZWYUUWAt0rUXYsRBDQt6zw/DYcB42eNlB+pcJxdSACoOgYjiUaUvAK3ACiTlQBn+TUZH+giFnLjMwmgZunJdUQvLThRzCDE8Y5NkUoNZ8gJdl3PPpTgW/2HOjOb/C9zr1LfF16ur7+d03h+a2Y4uktzuqhCX/lGadzjCkcEh3KqaSLrpbjjwo+FT9XR8Gn4mFvZmfrot6aDveofftIYj1pWzdIRgrPi9QQw4pcxZK0AVr4pJWRl1e2V8AZnLaC52YhzpU5yuMOE3RuqXydWEwhHOzV2Rjrgt4mWYpJ3DE5hrc0GyTLCEQoCcLStpupW30UMOpv2d2aGvKw1+ePKb2GpWC82Qkmuq92l4fjyvjQDpn4EpRz6zc1F/fjiAsNwYei5a0BzcYuvzWwcm8WuFjQBlkcWT5Ug3dDLI57e/wVWXBJtjciRkA6ij4xdiyR+gPXwIBs07qPO6Heh7iL9xZ+v4LKgoXfZ7jgDAmYkVh/mf4GZKmlxcMN3Deh0gWYBshLpLlQglA57wq6lGgrb5Rhu3h1oYQFhjWqNfrTE30RGPA0z/2hZ57FQad02vtPmH52Zv2Nn4qmmWWZYOcZzHQxBitcrarMQ2RUOrYTbmts01acZ6GCSf3CfBxwy8zPn1oihb1sW0inQC98QGvMGxm9HdUrlEgV2UXnEqBsZzLoHbQ/YPctvfpUc+I+gqiKoVsKuHea0brz9dNQ0rvMfZ7xyyJMqnkAsqyjjCzjePDtB5tj6U86paWDj/pMslGFNofb0q+p4cnmYUUI2P5m3QDEKpcrM/Rssn3eT1WYEqAmUIRKA2KW1nAOwU6yr/dUwRsNkazUoO4LGBbxXeX2JQjw+PkY42TkZBrhs0kVRGGQsF5BHub9D8Ro719qBQqRgDFQ7Y9J2n96Kb0XXqI2idzmwodFY9wraDSiQpF7qiWdIDA4qmtsE6vbOzRISoGHw/PlBQVhzIPlYb9qd78ED5Vq0rNhQQFdox8Pv1q/QMVmAtMQWhXQGpjY+QM6cYxNuIKQE/Vc0U6nB31Uhru4d9L+WZtHPvFQQDhlSkM7AZWgUc1wDzifJLbvAOezBYXhN0/D2Ps0QMKIqgL8/HmSOIOrLZ83cnuXW/FbH/Dv/xl14eknMSQmmBaVFQhA0mXl8lASiqYTXuoS9XkVgRvw1IRM17eZ78vF0m351SEJ15S56vSvCspw8TtJZ+W1722I98dKA+ArMk8wUWsdACSqngKs3LQy6r+Ys4U9YRNQBVUcr6A/NQMg89F7vZcGNGiYaipgpurGjvF4auXUmdrg7KWVATEbtzoBGCMXA5+j8YptBgCjMdl3nEpNtcZ+0OcfoJyApoNKbGyP6zMeykk28wOMVnW/TKNCkJ7OcYjEUgTvK06B9NLF8ilI+NRCod4NiTCnRrRl8lJmDunkQvd/AujJusiQyh8/jdgp5EsNPH6puMBuHHgmWy+cK3Q4LCfC/HkiLAFFwuN5LWPZXDJAsdq1PGVRc3sFb4Gou7jCRttdEfkW/3A4F6P0ioZjdqt/klKqJqs9qdhbB4qLgBphmhRa3Q+oxMofU0TpY9XXz+jWMnQPViXxUiVFVpeK8KHIYEymYaoWIUMzuhCg7/3vzwVdXJc881sEk3+KXUOqy6QfTkyyIWlJ5DD7RIESkmdDPl/mh+M9vEX5My6R0qJvejLKs744aMuuDP5yDM7loWedNXzK0Ml72hoP5eJLGJgVvarraFP6jXjCikl+tUKkZ81LqnA8/MAG5ZibgE6lTopXF+cMAp8hqClVFOyjLa0bNm1eX9CeGYe5UhXsVtw1xDb1zcI71ObhGavyyo1x9wr84FryCnu4p5IGhOqwvcouoPLSdbpz2RSMBZylzCrmrRxtvSOvGFmnAjJWqjcvpFZvUPKEZJ1yHIt8KP2araryylpBVZTiEmAcpi0eyPssLK630G56wE2yUZKkD82j9TVjziO8oWgsa0ahXoeWPrj/zyMT+pCzAKnYI3DwB2X5SQrD2xj9zorq81PN3CNx2nkcbGOysjEau2l7cnyvioCS+PkSJHHRJWXb9HLZMdcMJnCyJmiNt3+CnulUBIfXBZzI2SeKn2V7/7tfQnuNx1xfyU/WVbwSpGtVTsDX2B04B2KCTRmv53YfqgeqVTE9NLeTK7WVJ+IWhfEPSPLQaR4WV8zmUm96BWfyjSCrWwSaABrI3vVoIHtCzxvCyvCl8ZgZh7q4OUoEGIsSFpgZLDsnda77f+6uLdl1W1fO5X6fWiVKoh7zn9hdtpdIkMKTArXl/LiSnVRimiQINBrd+JtooKRAwpsnDQCrbSAqiMV5Jjn7/L1gVr7Eg/pV5CyXFeYrZcWCYcOC0jwCiBagzHmcf3odx8BMxX6ysllKrG3QGbZ7cfxpBFwUgjE02oIOM6MFoxEli6lACGK2aSLtsdI+2sGpi/XBlkd6S+/uCTuNZk4ixZXl5VOYAsG4urk0q/Py8AmBznLeB2VSH0b4rwlhcY1JKWCS98qsdYNPub2+5DeMPH6+GUcZWg4+Wf9B2OLXm7lUh6v0/86ANgdIQI3r3Btm6FpUwrPi5SQSHdWpD8MHwX//s/JFueyixgP4D61UVI/Whwjx/icdlXRgRazRvGc3nzjX61T48pjGcrT6KAj6jBk6Mg8uDjpWicScOhCe9P+zh6NkRYAvgUsf3n/Kifa/RQLT06RH05n+QIC2sPi7dHPzPt7QvEe1FGxVpPyEUPnSqzaZ0cvm84pQnoeLXb9fsT6mBKu6P55GBQPGo8l1pvrI4tdTjpev+Zvjlvg2OgeUrEBfxwvO7txcQLhXxBx8z6nsSfLs79NeKubDth16CLg9dYFGs9/Vyqo9k2hJZuwk70MhlWVS2tcZoTCFjN8JRRLw8UjAzedSAD4EQYbxoQxUsbG853qsp4Fg/m1qOPYxP5VJ0ClAztZ93roTK6mHPtIiZEPP4u+Zv2t2BW8Ros/J1pcMw3AaHVthv9zdZieDsA+9XqqSeYw3Nsmp0ozGqvWA9bwXFg4OrM4grOSh3XDdtg8Fs+2mGQjtICGRUCpyyX3tozssdXaTj9KXBAF+yhRw327kSMzPvE+WMq2ZMdGisJVhu/w3iv5mc4SdIrR5LxfXDOSFgCdg4BvXaoNGWwVLCvHniHbUoq4IySmClA0FKTKSHxb2LzDz7TdnlHPn0bgoFt4ikJ99KFwpBfDO9JidkXLwBTmpVw4Q0QtzTSmf9VbmEqARRZua3j1LE34AG+c5ORX+72Q6n7+2FnalQBE9yToMsRQF8o0nFOJ6oEzGmMntIXX3Qq5X3VSBAiqJlx+756cJCO7z0kJvSgwadIjBvuscbfAzz8Cc55Mwv9d3OgiXHpdA98GqhFFCcIn7bHIRTVoEd9Api1fUgkA15wZT8u0ZrMCTFppEsRNr3sOmCFjWuu1J4MuX6zWg/KG8Mi75QR9R8If6N2bL6jnm5YnjADWbrXxHMbIAcevyIk8r4/rrObXzNo8fJIrvxKR3RDgxBcx1LL2Xvdpe72jC3bhGiwL+eVtL7VG/xQBjAtHpw83WsuDMGRQBrdgYZ613qW7nJsO3QsTYT2G0YIeiwO+MruffZ24WS5sZKu3ciI09FGsWSPHVvNUtamXRrPqBv7tIYNjyTE2JgF0vWXlfrzpmP3H/saIn/rQ15BoySvBj7c+8K/pZmf0fcbbHh/5ycpSJfc8Ziv9V4wHm6tPM3wsJQzATwnUlKOkLObFcqcYyDYGTlsx574/l5sREJLgZ00lE44saPHZJKumUy2C2TZxV9ebFpBflKE9QTOngksz8+igQl4CB5JI0HqtcnCtSwWlpVe0kk99Yw02F6PkJo4cBGUmFlXc5gaI2kVA3VrYRj6OKWlVnIkHfR1EwlUFOVGjXukNdFzew6w8vKaEgsrJTCEQ3hZijPfs5Jq5MffBA+Dks2AAhMPBltE5nHRZorSnZCVl71cozuGe5zjs4wfkHf+jomh7MHYcik23SG6PTBEpyjPTZYNNXC5C7ZpKhsyf2gAq45iPOmi+y6yNWyabnQ35WPDtEaKs3f/mnilbLUzu/533riw9h1YzW6gJNpuyI6zYk1Mhs0ypziljxLiv/RlwmSioKSMjyF1PNxajZXJcB+FD1hAG+w56t0DPpJn1JSToMT6DU9eeaJhxdfaM/XA2qPfPMsGSc3PqNUU0E+XYNUFc7L+rebjtK2LiabXLMndU7Gp11nfM+dWzblWOEaDvVKbjGgPsluayJ8ffWzEYy5aqaPjYX8/OmoUghLJ1lePL1siuTtLyLWy5VfUtxTEIp37GnDiMZuFZjvMGnmqCaS2676FtsWNsy4Bz6y9334aSHUYQpnkR2OjFK7Ikbd8b5IC69Cp5R5un6QGE1yzEi08vzAa1bxOkpS6ZIJgZzwaf31EYbar4cXJ1e1oQo2E1zOmUv7U46Zx2hfcBS+ibuCYzznmj5A00JCZ6YHx9d6+m0xcZEfU5za25iPMMfmY4yO50qrVpuYeAP1EyAJTEBfJWe39xqvHD7PIMUIkhHGTsuMm/pZNoGdvnKKlSVlSQL5ZSqz3OpUHDDeFU9FydiBtZkJe4JnvPOVsI5E4NLk30Cru/YHyiddszpGadKxvQNa4FrTj2Yfd+Qt3sg3F7QJflNPy8PJQ41d17uFMoU1XlcMvJlga+jo2mAlI/HEtjUy0cRp77WyUxDrb7z/rjGec7Fn3ngVUBZyNCfv+QHMiiiKD2vR/NtSDLBTt3zcF5WmfyRPBXrauiUdiaYjZdJOBJz7KGuTZrxjTH32/pIm/DiFVL1eg1WfE3cNlZzChegi5aMFxHTOY0guvFfAkt8eGjWYtL3LjQdbkxbqiH69tkrlEmKXuAunZz09R5KHtJEvJfyWf69ukl4gRf9oWpx9tbuDA6awfVTd3tIm4ugTR3gFVOoXy0z4Wtx+eqwo86jLDbhCmluUC/WUUr1QDSpiWdNEwXdQFP42/Z0Kl3dO3j+yWiwcc/LU5zJmL1WPKknRNkJ6uqHvu5q8PdFPPknT7vCvstwysUUZksjFcE6VCmvFJurzEgcalhzTtZPF0AvXLsRsiHo4ppd1JHqFF8bHoAJvIU/nut+JB3elN4z3bWMu/y4gRegsGbw25MGeKAKlCnARLKxT9uGhmF+0+IMx0M88YRwDscQ0Bc5N+aIgkJAhXqyI6AfTrU/rBuOt0UlsdRYFI1z2a2AWb4yszOn+WNAziKL1p4yVaRa+d2mPYdELz+vgySvyLmL2/O8hICXn/g39cozUyl7rjHibHU3Mi9hVfDQcpm/p+OQ9BlvHKt/6jCLUQUYqMTcpQLM61pSsZpFGFgG1XxktncYQxWjEty8Pp4gGXGUV1dxysmtm/ceMWYKXtw2xVwuT+JKkyHnt65jSUA4DgePH9peslyA9tm1y9C7kh2D4zaWQLbtBRdUuOTW0TXBtXl45hkRdV6Bdo8dihemd1GfPFauGT0O4O8bmN2F5K/zmTh5rRUr5SENfXlV6f1t6ISXE3NPjc0ocCd1nb8Rs8iKGssAO+FPmPSC4S80s1vcYPnbbyEdRkPPmMvoA9s2Hh+aoQo+rBUtwlA8amfJsHQ+YlRi4nTnn9PCUV2zbEZHkViEJP3QY6CigL1oA7e6PoWHZnz8ax52aIXT88pkOLG8P/oeI/ucs54nA84MddCtECw0RoyPLwYH1QH/DQtQOtpJjixAHSTsmGNNVGa3uPXwvHzMOMOBFBjOQPcXwoD4TUa8bzpSZEZ5zIuu5/Utj+UHdjw8xe2HE5iegzkqHMUccSa5QwgDe6FQ7UZiCejVBd+11sPqaDg+XfCFsQ1qFAOk+dK6tKqo9b3cWnMRf0urSj89ShRYJnz3b//O9ZUP+EnMcb8/1wG7e/hziS+PrxyXrZfnAoH4pPPVhl/LUVPYyF5jwFyd/NnJu27jDHlEBR3+QjTFZ9XB8mb1dp4CqTWchkSCNgsjC8keoxo87dL+sWvk9pCeB9nKd8N3jAuzDQFfudbd4uYWL0A6y0jQH68Lzwak9ZhhHdGJCF+lNWPbuzilvBfH1VqLbnWWdJRGH6dSx9tCxDGIB6Ms/hU7pIr337rGdYMsFldzRmDgg8BOG7ZV31GEdZ/MIh5aw5x8Y0a4hkJfzxNwh2kTwhdcxaSePfa25HDOBiizM9YaGEOud+1iDmCKXILZ0X0udFN6TRngBGwxNeSSitYVz0k/z3lvB4ypTKb9j4loFl5eLAaJ+nIBiope1FQkjoethHiJRcImixdp830yKDz1kz58MeZYKYf277hh14l6A6pETz/RsCxHyezdbsNnkMETgOZ2HWL/WihJmQ67ecCMaSm6K6Sun3nH9z+CwJwiLW+lOsQyXVWeRr1AVlZ9uPM0fl8iTk+ZhYLlq8/JdS8XMTQx0t6xBBpkPBd7kag64iQDVp3lrzjZrVC4pA15VbatEOVykyf/q6wptMui4nPaQguvcl9xzTu3vJtaocp2SJlC3S7DdGRSFGrg3fp5/+ntU0poU5qR7L141ZbUNPblEJyFUMu9sszf1kvUS56tiUXgz//mWRKzbhqQAi7UcMWL2oLr4V0PJowny2cTTazc86f2xr1aWEfkmh1F1Ac4T0fgakwrkgWdDPS+D8HznUn6E1kFAvrkQ0+SlriEf6TMp9STNpQbqPElkKbp4WCAvORK+IzZREF1cKbkzbtoWuS4aXgXWjfst/ZdEGaoJbm0ywkZO/+Nyck+NOvGKLTTKECG99KgKwJu23i3qU6vegCXDs9bJAkZ3e6RoaSHway0ewtLx0XTsMZUJaTJZG+d9kFQ741f4BmCReExOxUYUXetexxKWn4o7qNHcMc03Gqc6zZoiiIGZ0J9jdY1Cs3r0lHFy1kbRUPyF53Hxx8CqkIvJz96TvXnhMyYZ8r4Cuq31NM9VxZFdZtGnHtOI/7XlC/3PI16zyBTPbupylWZ2pdTORxS2u9MTUUYJfde1t1f6hezugZ5HDszT2wYi8dQawvDikMWPmxUkgrAD46hD23T+vY8cnurBbsiE2e3UX4aw5CY0p2HMopXhDaQtKBMQs4Xt5+jyLYO1cgG3FUBVYzsswbcdDxhDyXXPZoOEtMoH06zqAmr3bIWf6dCQ41F4rYkmtHSAQ1l1CTDtTJYH1xyFjfBbvRlLPu9d0Qzej5fry/Kf8CA8g1j3GzKa8F3qnFdwEyxmYGptP9VMjqP2XhDJd+MgLQojUEQhFP5oOFMpgji6VhDOn6ekOahxUqqV9T+fr34lX9k4w5JFWAFsPfZM2dk+7EjXOdxzY01zUmvBRiPY4+XxTdVTLSI5PHl95wTD0fX1Dq7KmhUBlndCyXN7/EEPAi3wzmA+Tr0cCp5EPgR1ZObt/z2dHO8RfJ+Y50tvqh487WjJyWyJuWzoEsUpHdhC4X4k+vDwJqsTwY2FZERa4wTsv6qY5P5yIUplL7lVBovXB/0ZwhcsjdfdurF0talHOa00I+loM+aD0bkCz8hc7UmBOObaJ/iU2dB6/T7sZaUVJWez4qeYrcnl3F/DJfSJntDEWyZZnhTuHGxuSCKeKoQ1czx4qmctSY8lmqUe2WmTGk1E651zww9tM1lrtJS9bBSHssdZVjJw+c5f9/RnuMpUlgOINzg+JInvZx/WOWZTi5VNwKFceo0p1vQXr++l4i0APbCcPVuQO3hv9dpvPFI4/x/K55SDZ41AWyyTJ7MWfoouPZICpxJvjWSHaCtCIypePcCVgVaRKyY74851ApyzNw6x61llOH8V28o4FSlzMhF7advPY/SW4feWvl0c5c3O7v4ygYVvomsVTafwRi2j/VGLpJtS81sc7V+fb9l/ZKbzBWY/8CJ5QZoby2ldM532n2SWyssIKetXHYeDgbG3aYyi1KvVQk2I/nStsMOganKUqDMZKtufugd1vugJs9CU5qpu8G1q0b5iGlqb8M1pkcx56yvYjab1OWejLDfQvtq0Ou0JNa/5Si00uTL0ZaZFBpfiAqvUP7TZoqV3pue8Ut6cR5zx80N4h3lPrvZ86HTL08NkBb9ud8YOXQnguBDX1/AohFzRDAOc1cPQqRZMyWSFs3akkWf0RyHzBED3me7OfPFxMX95yPAqeYUJG25Lw3C59DXn9tZbNMy6I4iAcErOtl7NuPoRqzGNy489GGUvZqGHJK66qSCSK6Q0He4vluSq/B0rBCpfIsYmtRpIH+R3+YAf8mn8yCvVMNO+zNPu/4pHqBU/V2TqbHHjAISBZefI1cyGydK9vQsW4QFKJHcrfx7C0vwSKV99RWAmywu9vHEM6+HN0pL8j6HXuWZ8pjfTpr7X+Dr2G3sP3C/FSEPd/o51aFvXYmW/eX8byCUjtJ9oSU60YDA1SCczNFS0BlZvpDRZS5glgBgK8aHTusrJ3z2pupUq5/UVMZZ3gu2OE3PoVN1ynam63EOcdSSO+qcg1Jo5O0qRi1xhtEnnyZpf7bUFtmr7HUefeW/zxpzcHoUV5gzRV0ROlvjz41xt+wy3YAr7GOebri7pzY2CcwZ0+otyUKZOycKB0R6OCVKa7Pn1DwLtXW8SKGKyxXOLmdUXt+aiHc94S+0RxTsrd+2AnAvrar7TTfDGCqPMKKn1Vb7bSEP9gVPgkpAQav8ZaNWXU/x+ImHNAxp3LontPP11rvcT7hnB7suLT58+mfJv5lSEbQ1rZ1jJ2lQRN47f71Knv0x58OCgtyE/JWhX54EIvMU7YlYU3/RMTIeeDdF3RsvylRZHrUU+T31pwO0BkJgP5mdw11pKzFhn47AX9pJuIhxMbYLgWsTW8+nsMZ1Sh3InjoLisaFbUJfoRG5DeWIt1+VEATFZrupqHwJ6R4yhTxcTqIRewmYY2KDGWhVJ0XPSgpxh6MLhglDQXWATymXh3YU6pL/hBMufUcXsLTUZHKgi0+8GcDUWmXIw3tkd7ws94U6wxCJ0cn4FS7QTYqC0O7OX3nVKsEQRbCl1g9DTHHK25ZD0NrzilO0Q+oOtYr05CS+vAkCP0mh/eiCYLwEfIYuQkX88Ow9WikTVpj2m5IKuolgPIFlN+70im45KXDSzadMbHNKp9+y06lUt5BiwajwERIJieCI0ogYf3HuiimS1DULq5o7EWylaAiJj0l2zMDSaxq5J3Ucdd/FzoIxHiGpXBwyTtyR4lrs/MSS/6yZHLKoV+6WH0bHAoxX0Jgfer4N5tIh+bTdQIoDz5PxzW0BjzZw0r9NtZ+XxglILLqaBUosdZ7AyyAoxk2bfyCW4lej0E48n6dXwU9uSJawLJegBDgQGdl2OYdp0tHXkApWnBvX8pK3tGxp04lnkyM9tDp9yX06upB+f34Pq5LLppbCJeY+YeEo60ERGXbbQVlS1ujtuvXKujnW5UO5+tZfcBwKyZS+/uEAr1I/BtSnCbEK8aih753rHeX+JP9pB1nDkJSMF9/gGSDdTyHw9Jg7wSPvL0etfAE6MHSRY3EDHrbiTt7dtIPjlHe8VSBPTTeI88GqvkEfD0IGY5takDGD3WJJx+rCijxv4fLM69uCJYWb37T3p72bBv5SM4dbCn3y/EMTBhPIjur7U8W7V1XdiL5dLGgLTl3igE/LwjxfoUOrzkBEDCjMdwiLoHiJ3FsybKKYfmygw+Tc4w3Y9SNwoYcHL2xc/PRUu6uWgvRbVMDXXAADCLoseAJ+eXpMML5iFZi5cvS0QhptSna8vuIIA1dYTLKXPLswE5gGBxsd/QID0zEeF92+4XiTYtteKVYGDkxUK2EiiiWUVRihSgPXWtLPW2qrdtTBlVTrnxuB/25ASb/aivZjV8mO/COx8EBTIciF4MQjGFxPBTWNCoKwNgUhQpYhWC3tzCSzBShMJh86oazyE499eYdov5rH/+QjoffweD1g6z9hqz1VmE6VksaigXCDOPxXgQ+o8wCUPuw46F+Kf2lFn7T3CLdV3nr0Uwdc/gupXEGuhAJrMsZWKapnstHohzlAIQvcdMy7DkcHOQNAU9yAwyCK0Ty0/lYP2v9eYCBTfJfUeNy+42c7ARZb0291ZVYBF5MwAnVCsrBn5PgmnA67QRfWR7xO2cjMvCx+xg9RpkwHednpBXEZnl5zacbt2RQ1vOh7dXbwY5ij3bpAQwd2HW20WJUydEZhvG4sML4Ruqk33DgZZLIkGvxZ/d3MPWccjgLxR9pBP80TO0tcL1GbUdExNNl9+zu0MSv9XJOHztGLz2lbv9IKPsEQxitvOEbp3z1rBsgbwjRTQTzmOKifgDFAbsoNqOT7c3qqA5gkuzzDX8vAtFf8XLSQ1EMLnxbWxNRy1gykCULe8aK0swEeHlNnpNTBuwwPn3XwKvK7RKHQ5vZc6z0JlUTfdBhXN8o3wC5RBf5Sj+Ru+8Gh8NZQG4BWCWoupcoTjeezjF07EFaaXcXFQqBBqXrr2vqRSEoTMwHd2oPUqsTjFy1iDVb0DOYPkxfSUJiMOnohQa9lO7W+BSeoWqAvknRrKWZDCYouiVK93Xi7WIb0lLQ2nOWAjutGZgvfYMmIplZLIzraiPj9lY/Hz6NzIa3/XhOopngsbKz6XMooVSEsAao9IJiYUnaUqL/sh33fcYysU/Mzf++lQh2UYs18jFrW9KxMYvQ1cZGwOhICC+H59xZDFmJfIxpMxZp9f5VYGhaCYvZ2h1f10kADIhaRAZJIHmB8FacDLF7OdYXSHp4ZOyoaAWsuYXFoPBXK75hCadl6dNH7osbcr8PVNoPINVWQ9zeIvmYylfWC/Tc+h0fCR2cT3KV+/wEfaufY62nCROhzlDIRgaVKjkJO1v0HdqLczI8DnQG+P7+FUoo9vUPBoLqJUSqrvaNHwoAyLXNq2FnPuRQAP5GeSihHRWZRL84MgsYZuhH4kmRZiOmhBFJ7wVEqQXeyAIYRUJRo5QK7OgLu5bE/1mWBRk7L+uRolL6csmurq3zlVPSjP5pCvIFsoNU+7C0D8F453Ya8RwNAho+vzHwgevV70m/wG5/E1clzzqGbX8fhGSudYJuObRutmYcCcOV8deVxXiQbl9bJQTV50spdzOS0VLifOpsfjwj69097uadgCbJ5cZeiaPZxv0HguAAWTSSf64e1bMb1vZZFLGVniZrqfebJWG6e2s67EzSDguKzr0h3UVsqh0lBVGcrfdXKGOHp+e5Jqx0wJe5RjFG6eEkRDClUl1gYezoJDAdUDjCnEOZoxVV15JMzFlKHbNKuxYwDKk8JFvNVfKDTwU7t2BuUCD4Qz9egmlzRm9/9+3DNb4INpIcI0MC7wAb42Zsfyg81wHG32I+jyszzM387gyjJR3fljp+unH3GgEwCogV/YOlTreFYmfdkjCSLqdQhv4R5rBEXWFfUHob55EL2TZY1RRE5a4k8waJK4CWZUsuz1AqZsfTZMlziyFkSv9KDOmKSJEeoWhmSLv2++jP+ZjmsCZXQjmTkwE/eCSPVIBgHYuI+VMcrGmEFDnOpuPN3KnBGd+JIOO0TVdu22RRhC4lZq8ORVDsQtXr+iooBMvb5MhD03zcqnT4/sSlgTySbCjhEwMo8A+2J+T5XVXYmH8GGgDfjqiDdNGVv0Mldi6mX/q5R+o6XNpgzg3dZ1MrZ7zpAdTpiiOypTGfVy74Uquh3jZJx5GAU3+OewvefIlPly89xBD09JIJIcHgo4mtoB5QWnQbc94qA2ucy5V9Sl82e4wZ+PmiF7ZCOidUHXZ5Xx95i+Hg9FNXSiCXtBRB4U+Co3b8YigH812qopEpaSsaLl0RmgNUoMRDqDyJwFU/EdREV8dBwr5FUYB6dS1Qhfo0RzvCUR5NPdgx4F3Y8yxa8WzI6484lV4shaVx5YXtXp9ztdOssCdzcTzlB8LJ6ZgRWNrFu72ENdPzlPy3QzJa8iRdvUJec0Kzi8TecBs7qKNyWv6EMVbfnDKlj344op1PvhTH0hvr5nWtf3LX+4CJaPCMVbvFh6ORNWbu4pFRdJuPAKQt0I+OX3G+5QGvTf2nLb/JPVul4P/cHlM7g6xe8s8QFbwySI9LXisWVyfOxBMh2c7F1fV8tZob0oWQgUY9sbmOzWDXBq7p/uRpuzQd+yuS30bUoCoRiLhJ0haYKXrsbeipDNhMzK/IJw3uEg8f7P6ppg7WVfYC04dcD41M4frfwY6nYrqpyAfpUnu2vgO4UBFywCZV6IdVe8eBRzFZlrsPgmF18zrPtI1MEHMZdpqHHXYKgKHaXHuqsqY5CJdWqJ2U6/0yV+mM3i6R9f+smpWvrNdny12OroSgkZ9IWYIrlcfNJc9E5MrCphSosTUFeH2luxlaWg8rjrJ0Xzj5ehZA0I8BmSHOExDdux+qcxzzC6QbCxSn9MC25PdLPnPLts85cKaxSyYErrRMsnhUYAZBt+5nA1XOVjw6cJexoxq7aQugMVbj6Eh/TV13KR9WsO2oSjhnmLObuTMYYxGGyWaav8ks1kk5yJPXU1guIth68kW3D5GD1JuH6YcVfDJfZwPMAZP6yo44VRTyN1qejmtp1tJM/Jndpc6O6raIgxLS8IPuQdC9HeSttQ/T/mR4bSnXYc0rf1SHs9R+cePkX4kqbIcKUB3qzXhDvgmJFvLxr671mI9iQJT+8BQeI/jL4xoETVT4tUl6vhPS9lvvXzpl9A1mAgQwp3uOIHM8n3HS1dsoYj7mUftON6GDKQzmDOjRvT89KJ8wDpYI9tJfHw4Uv0aj7aXNRLAC4CKRw3Yq4vKeP4gmVH6498kO0ZFti59XhlpfVQ0lYKXD7JcNBQ54wdB6DKnST8WqNxU1sdQwf119+yccm9qxi5Oz3At/xNKICo26XgY4CBtLael69b28yIFCtdzQvqbOXWl/0eERE3VRijYrGSoyp5Vzet4vqqadQWYQSHt2iC0zuOCLUrK1EKL1MWQN835AxRCxMInkovyjiaVtCQVa6fs0OKJkgUsjFgmFNzEahtsAXtynglOLzRjlHwhkXc+kyrfd5KY0PlxwomJcrcb38Hy6pdI20oCNzFvUY6pIM87wVdoHFDComrbaYuYi4LemR9swd38vjt05kGJ3OZL1eQQU8j2gXIodXn7HAyHFODwUS+ZLvVR53rfhQDyUFonw1lXl1QMbWpFpQVGM9HaLJh+38aetnZeKct7HMwLWzPrcYda+g1sUWgZULW2Y+drPAQhWCZ7cF0T3kBG33HB9BK1q8ZLe8mO+/51Tpl6MZ0fHJxLoS7J0jgog1oISEXJtbqmz5gHuVgfLoobR2yQb2Nq5ZfoLN+lAtadOWx2A868iD6jLhCEAdmy48K0Qx+eK9tpqUKbwvKdvSZx5uDQd6BJTurjOO+RCUoUBhX/v+h/qCbs3DeVYASEEbOUVw4hR0cs/5IHfp4noM5wV8w5hcl88pwFoteeA2pDTQnTiJ0WB4dAsPRhK6VamFjZmo5SUXFgK9V6+vsIpKAFyuRCSCqFfE2HbFJKFnzgfyoUmESd53+Omu7ouMMyjHoZgDz4MV01ZYllnYLkJeSY9Lfuq33QzDnP5AX/jEOcG67k8L0l7ISaHcGuLQpgaCfrIrMM+mKEpyDld56nyKCEEBBltfggb4sdaHZp76tnHxu91CB3o/+RyxQQQTLFUWuEWCHtBFPwTwfafyCrEBniuvaPwnj65FuXo0EuCo6bV30EXBLXZRDYloLEBXx9WhvHOqIaRJtcGmqq/cFghM2SXPxhS9y+xUwrj4TxOxPsSfVgi2Webm73cVXms2H9HUFi8OxxH8ZycXwRDQ+blcKLFZCF3dNuYgaxIp8jXAQizpTlQOdbKsg+EkzHna02aOYvpsXitLFmeVQlHYgj2q1FNYcfz8KEcDRZgu481j86O/37EG5UBDs4NoBpIS4Q8PUxDaXp24/wA+jJ8i0XDuquCI88MPgOAtcqcjUP69JhNe3x4cXgMVMwof+DCAqYlU3equAbYLKiGoeMQahc6/hbXPH3gwI9LZhyifhoe+FeqqbBwavQRbtGfPuS6oNdGkqOHyfFDmDyzkZrfB3B0RSxShAR4l+k3z/CldBxxAULrqpP0x5xpPkunTPf0EGEnTj+d0vImf7wu05pGDVsmu3YZHltnWNerC+58hmNpQUuC9XtST8l5eyLI99ApZzP1Kv5XbkNZpMh4JGQhBistQ2DLdJPqBjpErkLoGJGRM19kbbw1YOyY/HkJNqHvekQC1DAXg4fCyhwHtjOc8ZXlmIDfc4bBD76e7esdWQyv5pJPjMt5B/eysBk7zohu9OF1fBc1yTfYIZoRdov5yM+7f4H+seKeGe8540V9vSlyYaEcP5OyEye5lIIwYUQcHIm7SKom2hO0y/77GsMpx42CGj186EabchoCRMjSWpUd3s7pJFIsXAq8alp2SroBVW1U+jQE5jenbropeEv9pEBILU7p0tzQCwdd8KEFDDSpV0iNNbup0sBqQFtznKXvo72YhtrS1cC7q3HwL/CuJgPXVbYFp4Hf8Xie6GagE9FBYg11VfpTuqAP2ZNrbowygKaR46sDBvYZ+RtyPcsB3ouwY5qVIvz30Nipt9inXbbOYQFw2Wc5fMtr12cFfKkq4PRAWOpchJVTLJn/FUSxF2A0jrhotyrknOWCzT4CO0sxsol/RRW3jknU4OmTuavsZFCezIWYxFI7tLogZK8GxfAGagMWkcT6GkzuRZ9CzHC4JwJnkLvJT4saiomUnXx+6pbUe7LWkt3Qw30Sa1g/t6lnKi38wRtQUsIkTjp2ELUk39ujsneiPVaUJexx4zoejwEQ9s6QROWvWJ/nvcAZ8D62biQB3tlttwRoaUbbaMKPPxO4GpJGDPAWij3Bnwwyc+SosjniRFDOgYZgSp9d12F6WtURSLPzGGnOs+Sirb1GiizsWetBwkz/0jNs5VTDBl3I7INpfVzqGxnwhpNZxD0YlSpLXzl/qnj4yVMwJa+0sylFSNL7kyXh/M4En3fB6WH19SwXhi6M+KhGwJUt0dIuzyLmYLSXN+VMv2LFnq9ieAmBSz/DhJ/+UK03dciUBcnvWr2Ujlm/g6bhxkiJypRP6zhujxMtcp4cO5h8FTs056dvHnRNU0LOPi+mZNspycbUCR/ib8V6YIhG4zBKpvC4fc8/tv2LZg+1IGC9sGK3npA0HnNMEvtFAk22Uke6Z6F1Xy0AZ+F9bdtDqqQKF2giU9KgrZFeuGZgHYX1HfQ8GLJnma/Ul0QLUvM49wFraRMmWR5pZatFymVqkUtLcjiG1bvKuqDLvF3RlkHR1nAtor+dIcz4HK3as//0vJfTUf1+tue9PhbYt+Vlf70RuKQh5jl3n4wLRTk00eMiWs7JH05bGVl1Z36yG9Rlue8wxt+dr5QBrTwAnZ2ta/EaH7FEnA9i6j949gNr3tKAAURmNtVaprAmWlH3ewKp4fQgULRxoUw0iAXDN02ZheI9qoGS6D5DH2dDIuKG+UEg1kJne00DQyrm0RVtB3jhydUNRBgl8CBNLKzAS3eIcBflh0SFbh9J1514YIFaRkeiynf7AoNOcRn2cffHC3+37+iY5Eq/6WyWX/Q2OjciUxfVReP89pyc45VpROAm2WhHzXMjf+KmYtnEoFEaJO0HtjQ4R2lyaiuzbfByJbsk0IYJ1HAJp8EoNHvBgEG5942ESrsTtNRf7UrE3JDDb21/N4sqAK/eJcB51PiHz3YksctamKVagZvTgR9TQjl0LLW/PdmzAukltSWNzLTalK+dKxxqQUgxWmlqy2dWE/2WnBdkCqaDxyfjpiiaIFQ26b7Zrt4WU8HvvXkr40eEnu8y8GFqkl30OcGzIMlqjGxsii7fgNkvNrS7i1kpec/CYOvb7DdKTB9n3ju/eRvRV96hsUGpk3rpNOqdElGFK1JMtJaA18/tmoTUHbtMm7ERyKzm9eUgptSYrjlmurm1L4aCR+aHVp9yWWEFb4iaXzdzDKX6yf/9rWSRNcsf3tlnwd+3OYtvcvTGnHHM7gY+v1vhoN4oYFfEgNzBytsS36ynBRVByjJlVQz2z7AU1rh+kD87nyp1Ptvq0ljQvj2/ge+la0pxqUJj1y0vUbx32hE0l+OPkM49qAcBlzZM5zdAdTFqoZkpd8fH0/FzJF48ZDbqVoYRA8bzRwuhqdVxS8DcJQ050AIXeNOZcIgjJJwtOtZrPYCdi3sCqOXxlwpBS7FsA3Xxmp+czZhS/HeAQdNYOB8duzCHDwWFPCob7MeJurcFkQJWbKfRLQ6RtrGTyDLHDQN5Fed6eLzYV69elNN11nfTi3jKZ7WJ/yirb+ykZS/cgJiMqN3n3lC2b08IUdM8YUvrv6G9Z+FMoyGo0Jw/fMUuCPBCdKAdGHoJZFVeuf3XzolIg1Y3ltqka5+mrfUsWojSTuCcHeZ948TQQJb31xP/m23OfAz+gdtOwnBdBWjxLAH+pplbMS59U4VBjpRBbBXGEiMafT1t/GTcO9whdDPf2kzLL8z5MjaivDkOWoHWVuA/D2R+uqH7FvLYl86PDzkz76HrkfaRnaiyTW3uv5LPaUk5ihyW9nwJMLfpXMrZYZTw2eJ5uHr9XYdh+et07ejL9E0Ht+BNTbSFbNw+FhnWPNheqJzBrZtDqKGJiHGVBPG8jvk8kocH6W9K8HdZV3dzW6MDx2EzvZBC0tvWkLlhM8prfRCLA1jOs+W8W/e6J+ROjshiw2vJSImr0GzrV7CeXh/IKaHdQGjawd9kWipzlgvucFA7z0fR2uiT27lVmbyiO4Gh0iVt5KnEt7QLJRHVP7LMbnTzr4+kh5VYGzG0o5FdvUHF7/0dnhmKN4z91XirfuRlWiH4U5MOXkB5l1s/bs48AN2AyYhU+umVGHqswk8lJJbAPnYVnthHE6svro2ZO0wF7aM6jHKABwNZN0vncwJh4ma2t8i1D8JPcXGi50rSbfB2v7FPk6qc0rHk8rr8EQ35qBvteNr2kL1zryEqiH5E7cETu92EtF9jii8bjBmvmw93iZgiSINrPEE1gm65f3IsctrOnUsHKEZJ04lzqH9Rl78RIH0LgFCpjeSQf896INfZdmif5xxkNs8n1T2ru0r/M7VsFS8Wzzs8oLOKknuaxsWRby3ignYt3nswxCHW9IrrEUb83Y+m9U2RGF4CFgKZGYBNmHbvV9pxywlQpazYXqLIu8plrR9cEZvjLclp/j1Txyt4Afz29OhAttUDnqWtdAPa0qgwe81tpKqnKZL7nREhOcbRtZSJcKPWWBzQ/9Um8SQrhzEJ0mufMio/P4EHrpcGFIj9KkgeeteqxyLGTES2QF8F0szVZuFhlEGXvEo+espNv+hBqm2yYfYwDdybbKidc7KHTTDYj4+Mw5YpExXnOfh8dJmmQvCLSzSYiFtb1ulD2rQH3L0R3p4VEVFMDwV1qoBE15L5bTL1CM2Sm6PcTj9nIy7NZ0vnqDKZpJysCoUjlyah+/IJSSaa/XuIjNqVJiTJuXB4KgnQhwgxVW5XpAwlSk8WSKA71nhyCCa5MZ6pSVAvjexgDpqOiiPyc7uMfUE2FTDvLv+lZiz/H/8fbz4UVQBYLavoe6qk2c7E2D6ZNYE4mGS7rpegwLRq8XVIm4qvOHSRAyy5E2pQSZwcMr/GMgBss51ApW/WyJZueW7EWshu9tS5hPfPQKl5wSg17IqN0Aqh1PgL6sZb3X1pgsD1CsM97qoVVx6vZbk88FRiqM911KIo68z55rCUz6buFCayHRcvR8Z/6SYgtb93iW6ih9jgXm8afT8No7286NcGGv3fjWAXdt5Shhh2cob2zsyTueWogbx/Ln0PTxdbso8cUS2EJgrDogqT5RWyhYWZ/XQ6MJMoIVottTV2KMu+pVqqZfwiuqJgJmAj9cH6Oxqiqri35MJEzTsmjuZQPvwaUBEFM0C7kaUcO1r1ozd9Rn2UvhWdlwUpW4JKTnhJIupr00DNnD1WCM7nQ/wtls/VmsY2AdpG81Da4SulLTggvyBJ6HxGit76LcbZ+PBQlBediu6M9BAdiyYB6GoFvW3ueXfFER9QvkomIdWaQTwQEKQBa9BNbDJeKcjq0WdfS1yY9ECc0v5eqLMch7Z5iVokLbi3JqmtMTP8L9YSiLESRqwujxxfsARayZUyUEcanZhk6PTWH5DO1sKp8f+w7c0rahr4EpFNP+oCN8FOgD0tEoO1rrMWqBbTjNmKI3eZD6vtuWArD3Iw7JVzZuTS21O+Y1rUOua0K0zo2uBrA0qkQyRH8tSzTnO99IyujkZOak7IaPbHl5diIdvsUZfIFVdEjiGhKGBbFUZFB4npgHFE4oMT+1T4lf0A3Lexr9YQ/rUvhD/T7JVLe5poCnKVHSkJSRA/gv38q1eNX43yQg4yPZoOlXDGdpJAj58p2Pcq8FlJ2fvzdAdXpTgucSgOUlsE57P6uS7vyuDTmyNK55BhcVyQtu7XlsZPJipxL2vE09/OhuIoKqtxucADMP5SsrOBYjK9zMVJgIgK3CIDlu/sl5wEthnHpfs8TUQ0qYFhT01FAoKYhDa93qIAEooaxBjL1def+FRAaxSsC/3cd7TH9bn2Gsigl7yfGAnHYeEAjp38HK2d0TILghV1Whm9Oim5n7DJ9y1H54NlKMiRL3TKb5Q4pKGLX2pBmvsKI8QdpPV+GRJhNEycP6hU1ltL5ME4utfRhiEk/Tlo2/rVbtoc8tNSDF4wU0qOlO1evTh8+ko2wNwP/rFeRQ4gZvGJP4vvfwLXkgLwVu2VaZAc/jXlhX6JqfsqPQRLRfUz5eKsankbrE1LR6fqbLTgakSEbteyoSr9z7o+a8rLrsT31kuJ8ej4sgk465YlA7Np3VbfIGNwAb3CH3Ba3t2dfKC6QGx/fOSHZnmPq/IQCEqWefi44r4rUEjMhILYeHAwcceDOhl+EzxOEo3w0bBOEDM8hkMqcjljfnIf+y1vt6gBNHHyV2r8yNWNp02549l9uRgkYz9iKTgs4/UGdOSFE4ulgxnq6JFNDdeYy3Ocs/m5aIRzvq2RGd4JfH6KQmR/mMK95mUUG4uJiRSJqAbWZbMkXacihYJn2jyXpi06KpZ1uoHrDlvflOyX4lzLicJrWLdlNyyV3olNYoZYWp4MUVE6XXDuKsHuPJnVlbf7clOf9zTj5pnJ2t1PKA0/6qo9T2IeelTOWiYFBiLDB+7Gokx46xq3tAsa+DYDvnnKmj1ssOic9h1iKeiuojZrQ58T4QO4TnCw1EfkUTLdTYgrfR/VjUv8l91aWh39acCTswkP5NzBLcTCNYp7yC8nF+mFKCIG/VyHvtCXr7DaslZNfwRfqYlfIrbMSl3lMGDM8mwP0BerL6+vCsUbqlfnn+K/fQQZ5f8YFOc1POAmCmMtYUqf66naAfHp86M9l8YyPjcO/lyhnQWSA+xX+ccgTYI5+hkflT/sZ1nOJ1mfS4mCd7TJ6PpK4TKU4kIzmNi2QwPT2r0mZjpe4YxA05WZ6GJNJVc1l7csytdFnvcG6Ri+jcTqYrbncNh2EhLs9m4KcsaInkzuetGTs3m6XpnOGoIDwrylIuQep+S2/MjT/fs4X7Cb/+x9P1O4fm1Jf6xxowfEQATE0JErBscrq0uS9nyfHMZjO2BJgkyzGnB5ZzJx4gYPUfPDzXosN3mtsBoJryiVmR+dhtJKhoJMQoM+hNaxPQ+FtVQamS9gsFIPA6vNV1ISiXufWl/qltN/f8EeBQ6vF2IxFwb5k6WUzKCipsSGKZenrmsWXxQPLtXZjgSGkqOORiPCRp/bzkI3pT4cUCaLrTEw3KjJISar+pICY1uLglcCAPCvYoF6aB+mbLTbk9vxpc1m5MKZ82YU8PDSbE/m6YED5lkkWRb5ztSKadzgUYUh+dOUQRf3c2ZXhpbt1aTGmsQirjKLCF5Jnci27IQvH8Rd9e2KeCokvVym4dxONHuOTcbTrkXid80iS9a1stkF7Xz+b58T5U73Ely1eaI3HPPFEcASfypt4XRGLRUKPF9VsYKYDmehmUCXycEW0rZq9Ks00nLRaA/8uJPOVhz2gKuhggF2NG0CR80P6mN/Lomi6UNwj9kcz1AqYsJxCf1udlL6/J5uTxgNUMvumX6xscZlKRYBXb+C2EbanivKoId8uu0ANjB7w95aBkVahUcW8CB3bv4o7eQqGKD/YuaYoSuZ2jzA2qeHs0OZ0+H390I6B13Kp+TCsFiCSSHbsy43j0UvrSBZCSd8aBZTTYjXndIkHK9qzuTsIylVfleVwb/cGyxd3TjQ+oG/G4Oufmu9tTTH1AsdTHtd+JKAzpdQOf9apsORyAEfqzOvNr6RcyzKBwjIZCHyABejePBhIQvfzQ0dGbU5nfYshsJ+jIiMkswC1ouMW0uqcyRZ4eQyDBKcIoKlb9Ld52I/X/u6qxVH1gITehsTq6tYEYfnrT7zJWB4foRJAB5IryoHvv//LDsnbHagRKOf9oboQJs770FTWmZm75eiOefqfK+ve/wx1D47QtcETjQ9nND59TbXXnSKkkzD8bzDfG4O5pGnLovD03L/1DnN16QBFp9xafQG9z/lk6cKUtvpGgu8Hd3r/+1b9mivj41zjhFuSMaP+/RY/gFjhtbrw8e6hh04b3eCMq9uyi9VozREF3jjmTkjkTo95YlQtp1I4zFdXl3AWsczea2oGjmScQvAdVL70FSt51WuqocTTuW6QNet21gfE17HMC9pES9irTFd9wA7Xn2PP32ouRbDuIXbz1j3rUfaQfUUj1fDMUCVZYaWy2NawtBI2aDZgH+XOdU/SJ44nYDhpG8J6SE7riVSDiU5VCrU0j+FLSQYzE/NUSWse+R6Hohd/kylreKjGqTgBs93wUxVAt0Ie0fwMoCKnUALJC+kO8DHHrkyD43tj2TEfSH50DAnhr+6ghauUJmJowmnszG3l2IivuhraxyLqD8dJpgBCUy+4Nm9Wm1g2d9Po0c2pWFtvKbxig6LOUoBCnhSzWvt+EEHMQ+IKQztlC+Exj4od2xrfouPvf61Lj72RHMclZ3p+92uQL41EOYsIhAGb5UvHoZYd4V9T9XtT2+bGJK3mefzDn0E1srZPTuWmJ0tT8yORLN6hJiuX/TRiYw7P2Wbcu+oP+ErTd12wbcTvX/7QN3PiXDBdPJ24Q0ak8Hen6tM/JkBbVOwAwfEmxYD3p4dshpA+JsfKnpoZ55jsn3QhMEcsmCmdR25yQjnwV9mwpiozLqBXJwJjwBLHYjn2CNxUrO17Vpp3NW36U/emyxhdY+C0soYTOcVDTGM8QQnNO4hO8pW9jyiNDp0jSP3AvP8euWPLz4hmPYoAwluMBtpg4Sjb+F2Ts1dtzyPGZJw4izfPZqPKOB1p5b0uxchtvNDpkJqXzPCX6soRp7ItiR0KL1y9vxhXXYVQC5lCFG96auZjmbIfZ2iJ20f6EvNc0Cn4sWihQRUqznDcwU8ajfJiAF9TlS6cVoiHLk5yZTlW6Cz+NgBxC40H7GNugUWwZhzgLeheAqQfykx4ZwIk9YLHcjLdqxuII66fI18OxajpVHjRi9L7Uio5WnFWiU7FBC0dmRl9tY2o/5rBJmMHlwULQ71tpR4ty7iX47GpbzODrNKvl4toqhYnc9QlJlxSqQdl5j2t0iocq/Oso9c5f0knlhtA+gcyjp/fTkfRuHoJ9jH1iu7wMIYZyXRlgZpG0dswwb/Sl5e2PvPYi6JNKI7lzkOqRjNYLTli98EfmLS8Xoa7fWwY3vwdGoisVVU0xCQxD6fcBs+h/jo56WwQkr8kv4UMonUqoJirDKOUo+YPL9oUyxjF6v+BPxBmGZc01uponBX+GGS0P8ZDC6R/TIsiXl+6XDbdU2z711C0cLvoPxLDrA8dCLdw3rMaY++BsZq+o83YTUcDUdMc4Fy4o4AE43c/x8cfDOrnGofCcvyOwfC/vXniD6ahvv3+YhNCffOdiqne0S/JiHm7xrV7KYi921rmDfiX1LEmzsd8lHHOUTFkEwh8R5Hvo9gVG0Zp17yspGideNS55hGyrRbTNRWuKqxzGn5gg83PcjOIFdxD77YyFM5da17kqdVYKcsVBd+DCV1YWMMwoO3yfOjZKpdLn98fGsw9gxRlIeiQO3Mri2WCZLTLld6WmTIw9aI+0qYMqJwj/BPq0/B0bkvatMW6aQbhFyRrV59H/N1RlXN76XjpJ+YYQtW6Lrr+IuRCfuiZbWtSBe/RskNbBuGhKIWxc/ZRq0w/XRcV2nahIzTtsHRyQabhcipOHcFiTeqMkbjL9hmJ1xgBFKF1dVsO4TSDzgo7mYXGDeMSYWgXU29zs4NwlNklByzbgvtvY3qAzI16haILy0t5qiW9oNLVW22XNOHkwxd7+vU98X1PM1DmN1usl3h9/cgb8dRHxQgexr15AkNoeQ7kXX7vHCbLxCyoMS7HrRUblatcVl93xBpBTQ8qx9NY0yPua8HCz8svmHeOnBzzAWTJUxGuTa7A12lb+W37pMUTaoJoSYBUqAFM96v7ZXsqNUjIFhN+5Mllo97H9BW/GzxKo6Z3Mibqmr2nZGuYCAvFPpqt8MhHVssFj0kNt3mbDgh8lLEJ/bln3DDf97lTzF1QJMIl5hKtQ0dpXargLDt8vWGI91kX4fuWMozDbDMnIBqfyytl2PuoKF3FTRAZp3m2d6nEjvk0pUWCh3d6ReuIhXWHzzGtB3+4zotqBFSBsc+fTmdCeHzagoz26fs00G0R/OCdSj7+JVvTaMUknzvr7I1Eu1EXR1JwrCZ190I13osqEnCNlxzxxZtkfpbZCQRwFG/QSoD79lBWjAW6uYsPY7e3hP+2nq4+F0alfDvfbJpBmbvFTgg0NpMypVagsw89wg7N+c6FBZ4CsZjshLDlYbCbygoMqtLkO/JRJbLWfYdU7N7DBzk466Yq0GWq0pwtQNHhLsq85/MpaicIWY/6/k0fQsg597mknRDYov59KG/yHFpSW3KUT6U5fmITiyhkwWwa+ENFrrosUOrCCe4+lCVLf6j8xUab2XH7dr0mFFMS4kkuKAbGEWFQ07RKM/KShei6aUJ8s5If8bBURFRf+i5igmkNTNayeYQmx33GwgtYsYkT1HZ9w/LTCp5qPVLOC+ThYS61+XyqzF+SCLarBmfARAjBd6sh4cfcXaEim5Pgn5E6bva8IoJcp3Ri29M45eio8X9SeM+X90tCNxboQv6xuo5d5KLugiU5nn+xjKn5bXbVVLjqGFPcsHwpNKBnsQrWDNt6pJdm4qrV5Kq4sDrjaYccbMrjdKE6lMr0+SRWhYmygJ+8PpWPucQGz7p4ly0tQY01pWI22GJLBVUvxzoE+zdII6IHv2FYJuRFWgyZDVr22KC8MfesF6uZlN/76EOHMPCjHw8diDRwYffj5N8o9VJUWM/65fCIwY9mg8ZDT+/2c3H6DT8dNyzQNJDb7Hr/KabiQx9i/ZUdS8n4zgbxAK0Vq6v6VLahtTmlvkOqGHxHzcgFhyTYEE4AcLqZ53DaZO8fVKSa45tHlA1MWNzTjLV5ExXjmLSmQ6DZIXThwIuxxOWI8KWw9DW0XW7EB4kth59Fw4jishXCUH4ieQHVTspg3beYuPPavTcqI6Sf7hZt/6XAbO7S9jc/L8zSiDpvnVulPW2Vf/669AgFfodNy4kzYY58lQoVzqMT+Ys+dLTLnLlXMpddplUpp0a+8JfeKxXyOmX83dEQgXq3cmwvv74vUSFOBdu0G0ezaAsbewoNy1qAbTCshbr58i2KYQou05W9K14p7pBTCz/HLuBGhuIKUZUAnv5AX36tA4E1jfLK5KyJoavtLQfRWJlsQ1KPvQcJ/fyvMJ0R5n3ED2E1FjIXmimW3FY4f6zD+FfRLE6tuuWOVl3+fQI/FazP9HiVGeAu0MlfD+nZzs88CCKLemiqacwtexCAZ6dDgMx0zFBG1flVlec6O9BQh2IwwDE8B5ao+bVG7BBh7iujC0o+yxgdnmWp5mDicbitpjOCI+pwokjm76cwrPPIQuZE2DX7bivSEHqeo/bTFDiu1yDSMGypQnMmjwyCQpgccc9Ls1Qzac7BZgfGjQQmfhTl8KovqalP9YD4kmGkhSgBWnFTbN/Ad+RMS9WLEwqcfTgCS88pFQS6fyoqrB63rCiPfWS6cRfKScvONwAVFWV5/zmCv2tQxgYvS/4IK28iYWWWefRs2GtWRVDI5lJEkvd/OZYZVoOJqAxboORldG3mWXvEpRqWxHxsbsuMEVrfUo4x+ST8oU74C4UaLe2c2EpTy3jO+9d3JAbke6wciV/O8Pstfno0/YVmMfaYWmMlUXtm10uno3huNJVfv9YS6OWd9RrW3bvslegwVZvkdcl+wtHtXzpIYOI98fd/d3lojS36Z3We8lCphT7216JzxeUGkz2sIS067BEPlu0t3vbCEloYc7S9VzTqumKAMh8ZzEniGo8AEZ0TKWziAyYb/GiLnGwYtNlf2ETA0kUPaELo4PFKwAoQRjPLd0UCmD+fl4QY6LzDlHxsQ+k87ypsyMpN2fLh86di+v33B/65a+sq9EXOhrUXkM6u0vSs75ApuHVSa/kxj6nm99phe6+jlQnYx8hm2uwJIAJUlVOFgD8xV6dZsEHj/BV9UGEkR1wHKArDku4a8GCsarWOVunwMMSGbS7cYy0zVQ26U+kLTkbhItUrwpG5wzEk5Ezmfots0iqbk8TlwRdpYUDHQ4fBqh0q53KYnFz+quOsP6P1AtmKnZbaHjLLzFlIfBDVAAPW5ecqjbaTGnvZvgeUFKtNWlveBHpkb9h79Q3xJyJ/72gZ0b6Q4i1AkMqqDNuc4r2+epuSOnsf0fb2kUF0J9nB7HWUNk98OdToxrRBONe1QXpGhoq4yg9x0btn3MN9TFNqo4wTmjXFOH3OYm88+nwc2DH9RKylojiq3JwmxLL5e/isgsT8Ho0fmOG9lm5DBri2ni4HZi47T66assXoeMIv21Nf7H4XLZuniiGpeui/9cI9xpvgJ3poW0HQoAk7VBuxc5HpH4ryW3vmz6Spr8cBE5PrJ7E00rpDTExRs2jidpCQrcRGmahA12TvT16qxAngW1OJ0g3hU5gEKTM+e8qwRJj6sSNaLZkfpVZdjzQ95gZbZorjDT1BlMYin/s6tWSPPdtZyp0Xd2mAE5mFZ09evt5MjT6333JDAw2dL/0WfRgqRI4hnZBOvH2kc+xaNb7/DVSIGug2d5XxT18Ue6tJIIML+dX0QaKjDVKUv6YQUDZPlQbQF6Cn1/ucSl5Xqt2fJxEZnaISfCJClOGd2TN/fXIOTu/oRGsIBeX8CBGA9fDMlt18JhmfMZPUSFvJb4m9eBkx3VBGUCDPZeosEXRf1NIALzQfd80JNwPBsHSB07K4dEO60WGISY7G2ds3oFnV+X0R1mh4aRDEPGcEjoi5YM5l0js7HVXFU7PthNIZuiyboDhr64sJS0looLXbGLM+krdrMegZo/duatHc0ef2ceq2MlpI9QNPmCImm/7wEAwMJz1HE9EkL4Mwbau0dFKzX/O9E5gx2o6oOn1dZkjVcOubDnVWV8QT5ZAIvjT9I7AVHQc/EyaWUhwMsivyhtEOoSscPfN0/BuAFB/2GjRgP+Dvrc/C75s3YbHTYZ0iB2Udzqt4QnJukH4dCmSku1xzvuL6S9B8v9fKgdXLWINtZfRgC5Rl1Z+ebYpbXezHNPI6zz3vCAQ4JEPIWyDAT3xoIMiw6QefZC2EzUYfEYH8oJm9rVqqbqDi3J0fUxhdGQOVWOBUqmL7+1y+/1EHTSEEMeONrc7Hrx0zeyOfjcmwZKJAG3dNZCbMpvqKVHidoAKhW3Utwbj8kIhrBAkhF9l3OMoW3Ow2XxZjSrAUz4CrEBBXaEdljCQunmWccF+y2eUtYHzeQWdLYDquhCTn1G1gHNE4lefhiZUREUbwATt+Tfd274mS3a7QIN3Dz5+WwzsrHLDqcgPR8MJ2+s5ZbbmP+j7RkDQvPXPzAJXGkE2LNi9d9okgr10YEgXhjjnJnIJVF0+peWfodiwbHChzzJyHE85Vm6jq64NrxfBcytc6AXkh8B7PiyhNTuNB7w+Dndx+6BEFI31YgQOxnl3aKXp0qZZXYduO0OksJzWct7F8BZjBOTxvwddW+aBsKdl0VZwMddOjOJLPH00WcvS9GBG9zWWgTn8UimJ49cEd8OU44N5SGAMPYWBiadLNVdX3cS/yASdeUwD6ugjuNGPLwa+oEa6IMRcX1l6lwgQCybzf/82gGCVXIks0erYcBDSr9Yl8sVgPrUvPhyUxDWDjvLiC8CTiTZLloQHXQqO+s0tS5k82hR5F0cn0rrdmkYhLrevakFeVF2ph4z9uxSeKOBJL6dmBTwSmrdZ0+RJSOMf0OPbKltjo9P6TPtj+p4d7jk2KvFbLYybMOxXe7uwlUz2ar/n6xb9uxnMa8O1q4PixoZdzJr21PQ0rHlQaEj/nbMBF+9LHqro1EgjCgqj2jUZcfQdyKSo6zxbkh8lGCy0oifzKQEVmUTH5rI6gW2dJojBGASVF/3m2FBMX9Y5pgNh5g4CJl9ffAGRNiH6qFhC69qjMsWB3OWk3IzuVf/s1UDvFJ2l6vs6WlK+cC2Q8R8uL4YiidE1pK1HW9zD7OVW7lgYIpOyvGtPmeFwRPJS3uMZbfQxbqtYVGBneReHSeBkai65aji9CSWhHXoSoNylK5xO5ABGtpMI57ni48kgHeN0l3uOBqcHQQoyOx1l02R2SB20HZJZE9ITCX8+GNU4TZBJbJAkVbAJGq6+xYYsujsOch+MymoVtxeYfM1fyqT8Vazx/gk21EEPeDqq9ZN4AMQQFsuJgW6ky7RMUpzuNnARJGiOuujiru55CTjgncVfv5nVgaq7P+X2+KaV4LSpTvzvBXZlpY7sSVBb1GkvaM+DQVSGm1CS1yB+eg4B1FuRFDDsiqrsUyCCBK/758Mmrc+iZC6PT53YPGPD3+kmsvYBV/EhhsoyspvN7+kv1wpq1ixTDc2T3V9RUJZ7bhpJ9Hgp5XK+mxFnFuRR9mIxXTQLGOMHKoZBQ8h2kG05QWTnvj7W92dqMyAqRwjqBf9ERgg4Slz0o4wkaKvXhZCpRA7/JziGbtaPLa3oCjKvbU8FyBwT9TlQM+nzsOaTr6JGglirOo4H5g0MFD4UA9V2y4U3K6ZvBIphwLZ7US4N9WdL6nAUcoT4CfjaeeTTsxfCeoPX+pMH0W5HtEDpx1DSuYsgkNDdbznCWcgXohT8Losrt92ajWAUDgrHGytvlOKHK3eU8xnnvkKp8FJtz4Jh8jLtNcFbsIu0kEh6FFRSFfUq0VfMMmcJtj+bSO0QMEfGZq6aSgROmkMbg2ZCTxVAQrJc3zVwnSDByy+b/UF3ac0ZjUmLLEM/MqWYM10ydyt9U9AlCT6KeJhOaq+bLCQ2nPkOsEH5a+KSJUN3TVAZdpU6Q7Pxpzqu2AAcWTBdPx8fgmkcNLc7WrYyHssQt2sPpSo3VWKPqQTD0/uJ8xM0g3sOWh4CeB39mXVH/dKiOShPRxOyjAFGVh/5a6gzxJT4DMsQO4jNEsvF8fSokmSmdOkq+wdUfi34Ys4CeCczQB9ElS0/czY090BO6yqNr2MYce5rTkQ+nXbwYWofA9QbKM28YmOFWWilwjQlN8dX/DeepPlj2iQ6PtkJCOLCxpIs4e1kiuU06enNT+i1PG3cYn2ET7s/xtzar5IQUlbJMuke+WpaifZwRjFDUgCypZ31bVR5JVHch2bJ4mpmtrI+jonaqosrSg6QRBtKk+YyLPSZD0GCmv3lCuJKJqlC3XIqQRAEDNIWsIg6HqFjvKYxyXMbCUMNryTqLQ5HR2T/kDkCNHNWqkGlVhkyHCrjZWclMG5XiLStjZHHdIoKPCGrMcBDYEdQ4eJM1oHiORtqdY+4aFmLXOdsAw6Bh2TTrmASKJZrffaq0XOY83+woyCBrwcabtU1zD/i2vtH7P4vOdPGLqqOjkGev3URP/goKClwTm5pcyq0OlG9Zpk9gdvWkCHUZWPSRqsFumfdmrY7WBB3O7rs2nLXx89fVG8OrE25GD3RJzvA99UCReydjFue8tfxDA4OeEu27igOHM1hBiaO4bSZXPYXs03XLdoIvWo+6iKJE+APBUQv2TiJ+YRhOwy1FDaUTs1cmZlVRGBPU1N92zPA0sHW9nsq4pYvX3xkvr44ng+Avg6aWW0IRR9yKuTCQhhvv/+ottNOXSAtYnNf0QSAr7pntb+K7xG0YeQiLKtUTd8GiRv6eozjCiWde+UM/whmhtpkfGB+GE1G/BMy+tQG1gx6ngU+r6EBRONz2zF9KCcRB/nHH9maBFYjURTo15BADpH1L8cXk66PA6Mh2D2ujJIUGfVjPohtOYf0ICrSizUOnRgV8fhygQ/EtzIelOgOP+an0swnZUOK22YQPbjN8yU9XHbLYOo3s8fZgkcacGAvF9j4QrnuKCSadYxtlx7Q8375KqnHH1C3qP6tehSJB0RI9JopBxLgX5qd82W4SfcKI5kxsbdG/ERGXbcQdkNDn9TIHtjBjMdaEDanDOqRp+w6DD2gv5aGZgyZLrnQmOvDaUO6kLCCMl8/cUeDch4ZjrrhDcA9ISzstgbdAwddH4HAykDpMmYbiTIk+7NHJm81L6Tiicy/BoB3Ac25TQIxw7ev/tYp4FrU0IkDjiigjGpk7e9kE5eZdC8ygKVyMe1qqOmHaU1YE9C3C45D6iD1nPsmk+DFvDd8vGKei3uruc/oXG3TbLr8sCMEhQH9nn23H5B8h8MJwbIjwU2e7yM6s8XgZzQ1jaZKNJX+rNc7x3dIMi25HUeIMoLOjQcb8tuXsbQM+aG4JowbFpfcvaDKKbH4g3lzotC5XvSV27EnZ8iDu2vsPJJr3CE1a/WzOOCbNpEyy0SNpQWoLKwtX60SWjo+Fw8YAXzVMZ9iXcg7u533i5TatUUPCav4oomm/PMVhIbxhsbOy5pY0ZSa9ZkWC6WGWxAiKiAMw1mzz/afnqzYNB2wTKqjfM9eEZfr34hqvbimCAvnw8PGMxsp3kA7AyZIdNx25zKitMPiim2l/95tq+n3PQakboYhQ9mi4umwmWtlZ7IVKlJPW4t/0DO2KKIotchUDWjZwU5WZg+PLcXtXEZwwi+OVI5PSAdXRuZhs86GE5xhxN469d6ySQsDSU19bbxQfdS+YaDW/UAz/GnZS8KMgfRs+8eyhOgEGD+MBjrQZWgS6rIoiy0sno/5Rm2rpj//0+x97mrzRVqhnlOAxJ0KZV0Ekr1telQPEQ8l6hsm16jfr3h/PCIB7u1WQJMaihEtZyTlyPLRKERg1pYDzHXoi788vsb1lm9R6ndCGthHEBWmI6ZxzNdU923IoWJmJGFfafTP3thJFAYd10qyq2D5JoRjaZby5J0XfHU8giLIO69ZOsHfiNSbyHrTj1MpXdh4ZheDhv67oQ+/rcSy7tU4I9hMtLW+pVSvkZEriYK7gu1CbxoB+3efFWo7YN7fOHLS50OQM+R77+e0DqqX03615EXDBhPwdtaItRJ1vYfvtO9576sYJyt9ZNPZzAml+z+kBmdRVSTM0XnPgS5MkWRMC30T8AeX7NRFlol7PqwmFtoyu6cAZG/hL5woz7NebEGAFR4+eKl3YTEEG22yCpUsnfp4ItNXMIdf7F4eDDlPSe1x6E4zKV1ylE3oxx/tNYDuQSIaAkUjAVwsYeQnPfcCqLI/CS+wZu21eY+kj0VAyIdu648jZUkfQMPU0SQr4GGD+7moNcuzDkKGtG+wJO74OAaZoGB2WpYzy9fHpuL5Xyeh9zEd46akPwQtbfRleMtxP6l82IWjpijdabGkswARfsSVuEK0JRWWTIJTUt0FaTkdzsDKRVczzMpWWXrRnH3EdFA/dfd69Q6u8p81j3/8GBgdRroM+HAZKzaDGGZS8BUuysEYcD0KPZot/Kb13WqwLfVHNCcNcTP25um4HBpl//Q85Bww6vtiO6AZoNp7dzj9gj4HS63SoXRiaO6Z7t7FGYCTOERul0upKfbyOJVZl2TwFbxPZv3wLV+yC/fssSAPS75AR2rfNln4czE2Ji8W2W7y+HWwSiMDyWIhX5oR2fdJgiqDM4UBcikCU2bWb0tBFYRqtsfOXm1jWNfOysLeXg2HjUcQ4m4AH2U+abfjhuwb+wEB12IfUMHC3Omfk+Y+0mSg/0BwPzxCIOxfnH5AYXB8JCJB6jTZA1G+KfCjPcnBooXEdrCNMiFXpDR5HuDQOiYyZ9O1K5go1+7+QNFBypH2ygH2hOlYOs+ycuvLnwGCWy/Tt4nZPcEL8y6yMB1ShxMLqz9egFjtj2QJhxKRN4awGOjDd6Pd/uO5YPSaJ00MIY+wvMyOqjjb1TYhXZY4ECcylb0IBBjML+XCJQGvq8/JHWfvwgIZAoyOfc986wmLEt7bk++Hdph0CO1X3zNJMySVO8OM9ZGKMXtRylasZnxnlRPsrDsGMXgGMcaWZTVcmQFV5ZxbfwN5eZYOX+jR00l50voDiR74eTswVtiWQXHZV+bjPpVSot2IAnkupTyi6MFGAvIcTONVLAN9WZ8LMgSDSQVyLYSxXoxuaWfr631W6yHZ/aaLcbB0OVDjcsdQzBeKhCvlUubnsPxF7vzpKzS3n3/+5rz3d0C+8VPV0fsOUPkqBskzFXjoZU3g34BGQ5Zo4M0Y7qSp0DQqmynE4g+oA3eHcZBYC3MDzM0kHXutVrrRZyrlQw3IEsrswXiJ7wtpxI9SDcwPQZY+WHyYY9FBJTL1CdDOFxjDMhkZ4rHnE5EmnPBd9hFNK4fkGQy8JLJ2QxqfwvxTaReuQsnTHtbxrbH42RSEjqIs+HPI5Z8NcW0YhjKhzFqIPnU8XjvTvBV37ctzQzi4JBuIlQF3KoO9PtmD39EoMmOpZ/qrV6/OYbTcBE6Ulym2JJK/YRYAv+tp2wz38rpa2gafJiUiLGYRAG3RrDqeuyQidN8pT8MzdNbN00rCVM4OsuM845dwkUFxvpDoz+iORnR/gy/jEAD0m0egrm7pfr+rX+SA7mnUMrrCnRzRb4iAlohCQirctwHFAT3jpj8xJLxHDl9CA0rBt7U1jhXQoqR/WAbpFRWrA0rrJvebvJwofGC4YGUdiLMpui6CdbjiHlqpXvXT4063F2wtVIZctCwze/v7kOLZE8CCKR96FvVWxQmYwcPL7kZNWplbGrhKj8C/Ng0aCVADLcrdyv5lL9/5TFKoesEzZhWhwRXlfF0SqfmvELM+cUHdkZvGOpGPCW+EXgzyr7jrx3XDqHkn4zJQ4eOb8Qmuei+uvyrQWhzRjXUu5axPRQ5FpkCPBvCc3mmUYo99OyXhenV8aVM1vcAjpJEMfJGLGh3ycOQJ6n3JSIeXvindJTN3XA8a95fHNX7sKFX8fDwSLThhh6IsRIhOVRnrdqSa3AGD7djRS/Wl1AROwyV8/eGu7EJnLGGE57mZyyzUaaU9Bc/XDNVHjsXejLSNTCDAw0qNCvFVWPVKkWmLxljjqSxCGa/Cl/AJ7WvF0jBEqqnQX3sq/1F2mIRPMojytwLhBxlKhQC2cZwpY25xN+Bw77od3KHGvg4HvVK/UUqVsfbaN9xyfp+ff6M8vWaYfc+FAf5MMx7yrHub6ELAlHs8FOm6Vt/g/IhfJUPxcBzOWhE3eAzFYZfBbgu66p7nhzgoj1Xss0UrRyGsoi5bki+M8VBWwmjxv2tojA+amn4AKv4VRqEsJKIWYoJsd9kmK11AIOXpKdp2XWcFhD+XBGJjjt5DWsJLXJKFYBzCeDbFtKWp5K7QKQ/NhNN7veo31wsirPQ0pUbCyhWV9HcYi9Ytnx36POoAF+k+OjZK4mXQCqFc57of6RSmY4DIeQU161HPOj9l6izZ1JAzRerpqvH+uiByFlqe+6mrdkHMWl58rhk8lwekPrCMfQ3JMnp3lfQMm70ufdS2xRj/6uy6EIT36RLVQahha8o6tjn5yubysaqAkBMpvKmKA4CRGzWDnPdnzWBcNMnY+Jh6bty469OXV9sXp3WpMpectrc/WAGOo5IF4JmHW9JWKqWEvHGbuNag/3VyvkjGG3KzuOU5QMiRYHqpY95u08RdcU/R63EUrf1gsVo+KcbhZjdnsc6p+PDVFjzlnKj/UN4lsOU7Z8/LoyQc+bedJIdKS9NL+W4Z6neU/AkoMyQvUKDKdzqP6/C0zMWd/0b82WB5IB8gJnSHrlWvjcgg3omjLjvbM+9igg8M1Y5UREwbrnE0q+WI+jdZJKTnPFozzan7PYxIby4M5zjc4UWIn47FmWBKDaGo1wNKarje4R8jFuRp5fFnSgGkQX80b0uPk/b9TWZyIgBoXLfY0+W6F1uT6jjEk/WJ336qB0B9WXZR0E/xImKhyY4ILR/mkXxdoA6tatnwM8EaCWDDwPZJ5PkSufSV2BF+Fh7YPLBoPez7sfSUeCm3fxqkxAniVj36alxhl6LVFMRYBON7/XX6hVsTr/aeoc8qENs8UpZdCwIVzH6uKyz4DV/F+zvfrQ8ciQs8pV7XQPdAZHw33oDdUvDlialpCcjx2M4SYXti7vayaimo25iCXMfwEsIteY0wnbwLw+48Pzbf4J7uSrugAOGtUbB7zYymTU1Rur2N2qnyo1ZEBHzk9cmBPuY9hwKNB3vzcaoOvF7ue06okwGZbCEnVy68X6nFfUCplg2U6AdHmHmspruaWe0CdP2wWmp0F5HePe5zx45laSGZVXGkmuiyaitA06l4rvC40j6v8ntPYuo+64pDuARorw/rQqqglIzR75dBunV/QAYAodbZ7KRtWbmZewhhEsvFOFv8LvKlyKuEe3pTqULCVk75luhYD6MepsISr+lT8eWsT5P3xoTmVjTjcloy2cK7zDzc884ezlq4hSQ/d8Ot9YeXDH7zxH5w80+QQG38wfsOp/L3YVw5cifLQyXxZvRNcmY5ttfLGrA+NOBabisLQ8i4TJNkDmympLBNqB3vQs5w6pBNJFTfr9J1YaqAo9ZhiT38Djs9pZ7vITdAm/QaG5agxbsc175T1X9BWg5+qP6ajbdL1PCXRRs7oPifIxp8RwLooPzM0ay/460Xr3jovfqNokWoQYQOxdbEuCesyC1/pptTIG/5QMwElaB26HQtE61hqSWIfPDX+N6eFw4lO8uRHe5XWcwsiawI93S0o57Rnu5Yy8bisHnvG/gCahAp24tlUKwA/EtEcvbTN/C4MgJ+bQGqwWEMZ+fJuG1Iu55190MYQ73Wyw8/sOrlTSj/QhD2Yz1JZhXEDrKttOVTD3lNh4OyTJgchTZ5WbgOZ4sYKTMbCucRrlmNgPBTL9NEWZRSzy2uqRc3BRVgQxxy1mzRbi5l1bl6XwqaZ7VoaK9GGImbZs4hT3+GH/BR8f26P+zR3FXLizrnXw7luiTznTS8jHk7iqF/hlFX56pRpIn4gLCGX//7hHnq662OAdPd3KCl0Gwo7P7RvIai5DdB9vq/fFBMFrOmloVjYS+lu7yyaRpfnh86MWyqQvXVQ6OJk1bK1nA+inKRyhhCmPDF5qzXCvKEH+9+fDf2UwQzjxo1KrqMo3IbiQkRVQzwhtdppF30ubEJdpmbSqJcd/NzeBImUU1iET3VmNZSs6zMDoyoRe2lqIHVGR42u9Zm/lsgE7yxSj6JzyuBwKi7ef2kavEvCT2bUQ4FA0mOYfH2BBgfVsX4ZjXnXF4KKxUy6jjLolPqBikCM23es/o29saZ3D9Xc1Ma3W9wl6E5YP8vwe4i1+a4+n8WER+61jbxmFo0CGDytzaMFhST0M/4ASMjTIPIPEmKq3ZF11m2Dh5ADPhXeQJ5K2Jg3RU5QnnnKNX3ssGOeax1Hr77AxEPCBMbl5yZIoKCjy9ohTOpgL432XBr5j5cHweslPjSB0Auw7Deo2CLPiGg5yT4pqvxoBy6oMyyaL/c7w9kIBSKmxhzpCi6w7Bn+6Ke1RfStYz7wBn1yvIxDQv6c5DGsVYHkBkjnt7T1FnsoBbb5lqcMooje6LHLvxFbk/0pDUpxJ5AMH/OWpof7iLzithe+9wshFgyQ5O7qVMIN1IQB2TE01eRiIXKVlsT+Nnq9KdhlCHL4WQwvU46DBup3K0a4IgthTgcZjCRwlc9ig5iSsRL+XeXRf5jFGGhTVhK8JzBvXnxJ9ObxSopQDctv/wLqOJG/6Sjb2Drj9gGCdab2hA65Ry0y35W6tZRtCZTxB+PyWOKknXfOdhyZnIO9fCy7c4Dz654jCYS+fo42tKIp/hrUF1F4v5cxCQ901CjUjQcpoKT3h0XvaB0IkX1F6tVCKQDfWN8Yx26gSYY8AWbe2s+BH8p7Zu1rv+AfM59TFDOVwCZB5k/9pLL0kSLz+0+RzGGGZ8JraAI+Of814VEIpfcekwnfcnXwnwpaVRRCebrfSok2lGSSsjSydZ6M7eIBS0w7iVXmNV3VXDbJAA4Ew9xXdhmdV/FPSzkePeo/YnwYbXdb20KiEh1d7/d3AwcIbpoMrRS6bZReFI9QoNmovtoNBx3YcdBvGE5i2aXfuPbaoatsqAjTzIpzsnYw1mjfuKfqtagPyJ8C4xmX6yFaST3WohsNcTIkSGSZkzLrJIF0xpmfbEqPCdDeARPMaXZ7EAHwa1kDTuvQl2Dg7/WTdUumZE2OwfiQQB/xTut3J5ED9jL3a+hPWuCPSK/Uh+E1CzzDp9lz0DIwlGSdDIn+MmPbFiGXHG6a8n22pVLxoXMZFoX/Kf9ed4glfaAnNLj9+99NdcSWm8rLquHxzJOmjzp7mp3qGk9BRV5mk9xYt5gxVBOUM3Tp8xLDgCJc2ECHKIUroQxaaG5eSr6zm9oHjS98ogIrFEHXbycMhY95+0BYEboY3fx3BZxCReXpjUEu3/RzndUbu74R0uG6Zl5BHIB1R7k0lhpJ5V2Rv1qdEz/mEFgUXGOrNkKDi1KB8w3PvEDitNfdPtOGq9MMHa4xpT9+dyecoyfIF1Sr0iVBVEBYUlvSbVEBeRIAGIp6gjP45/svDXSDhTDBc6D9IB54+Yt+VW5wurHjLVBJ/oHoeT88N2QREvowJPUPX+rJgNHbynHtUaftxxx8hTrVlNbnyV+Gc+l4f+2hs2wGWLDhMb8idDRhHubnxlx1DmR5m7hDW0w38mZA8xJwe5UDOPja1E/uNqfxelfhhQFRAVTNVaO7ZFvTh87+93/xmKwOAipt5bK3dCd+64rjfFi1IxTDhmRbiSNsEJcL/oEaY31ZSOMaYh6yQYgSYK6gv2BG8PPN+PqpTYPrmp4/GXHJYloNr+3FcO31S4zPo4BKwMJH1mZNSJNxTusyM5MaYcP3/0uJGl5d3QRpV0LLzLw4atqr6g83K3lyDORwTLHdoeVZFD21MrAyjz+ltmWOtq4EZVyxIiGxZbbqWyTYqfMd9oIB0b/ffYOS6zrglam/kitM1s18lbZ4FIsuRpeAhArw6niu+P21VuC/KfxR6Y/GzFDXqSHA9Kmp1yaeUD7LoQvLK8ATV1y+lyoOSZ9eFy4g86lwnAq1fcdpniEwE4PfFJ+JpLGrTQauZS/zkfAQZgxkvxuXIpmr7Pvf6BrFq53tjl1sEiLM50X03LvR2blR2RVZynPPfgW4zT/HrvVn1Obfp/YEeMxvZlHXif25XXiorSKHjFfizwiS0IUefgohsLSNh74cYht1vfJc0PvOpL6LLm1iwbX6gKP4yRaxU3AJthbM16yG3WIuWOlfFA65znUKquTxzENt4CLdMA4JQppY9eCB7f0hx7VtgDM3fhLReCcmf19JKhEt5dSZ3TIkXH8STrXOZ/yY2ScIY2aYU65Mka1aSvcMz1GRWiup2J5vubFYePutXlBLnZ7ly4ycba5gQa8qPw41YlXLZXbAELIAGG78p3plDWediEpTGqYI/3MbpuC8uqddvzKiLFPf4zjk0VvH7veAARGEOgzylLAlJ1F4so3HY4nujUegC4PlF5UuzGPClZxevuhMObPoxvCAmConNY9mFOAP7VDjFrPkky+qepDcCFSVRVzOB71euf7g75l+3dMCEj33D32mBQHI7t5NyOycLqM2lFToWO+CtNotqRpHmDkvah2lF4yN7acSWDjoSzhiVTRWwnLrluGVfCsisl8qGQVIBIsGGG8Pz16Yw42sJc6wXnSSy/wrrki+FG3GzCVkBlPRKQ1KTFZ0T+72CZovmJwk/eji71G1RyEtp5daCLoUXqaHDqrvD4tz9lCsz1PVDaVm5W+ODnbikHLDmxHnNNTgOPxYyH7i+zZw+8Y+GERhgPXa9vaKQJIc58qBUetGpi3rqOR9mH+O18lVdeivzUZNEInJDBP1tWvbUj+nPJeWbIZWSR6JsK/Qo3W4dOt+rM0sQtscLD8QHikCzV82fNM4mt0CTWOE3TN2gGtBrPKyrezdw2stBaTCwg4B3EFf2KHmO8M6un76HpOZ2rq2wEfmxq5tsFx0JQqBwucbyBq6OAt9+eT9qWxZuhN/TLxMj7o8/hyklB51uWwt1a43hPSjYyH61olkWgZxhbsrvVfWgL5uUPbQmYTJyqM9VA9QBBoA7+YuxtLl8kHlcj3AJKZL9SCI66qPe0OCvQ/JzMJ3gAVk2Gho+paB2M+X5HXK246+LnkhZAa1fLPT6VCP8G2BmOC7nL2HgA/JgG8szzc1ZO/I6V+zvA+ka1juNvIoM6amkwKpIvCA1spky62v6N0ZOtGNC6qNKf8wbl2MsHp2SkDKfSslicU+vVxV6t2Xl4I77djkOBeTtPyURzVEh5fsEOmdYYGGLGEo+9BmjtCwLPmtHT3h9QHrdMRPf2ChbmSx5ZsmBnI6siKhCr/Q+cOAcMQxQQC+buqF+weeR7KzeVy4YiOyYGRwpHfeXITzgEvRX7e7UEm1L98NWvp0gw4QVzWo707MXkPWwhycoAqZSF9P7D83KtPKwnOBW/WpBYiEecUi1QN/PK6SCrCS6i4aCH69u4AElLjSAUgogoVsfUIUjCYgYdtTE3KyNnukERX+6E+CP7Ae56Tz8ZAyEyuvQdf2p7QwvuVWnxJV4NRr6OcoElX6nA/P/K1UT+5HKfz4xXpp5xaaBpzZO317jFX6tvbo34e/Wp0JCutD21+GmqFSJ+msAgV/O5MHKPsMVpbr+9HnXXxHWdEXEGZHX+JZwRGUO4TR/1TTuJKp7DoeWRUseN5BXRJ1RjUljQgzfYYNnqyZ3HefgCMV7HUCSkhYVj1ij4PlLRhGXLHMARoTppq0wDcOBaJAWbltUyE57DTaHgbMCRrJfjRbd1qavsG0lw0mP27mSSCQJa7r5o4MT3kIyct4caxm0bccpq3Tt77kN83X5d9G4wpan26FfHI8Sjtfgj+jn/2JQl8gToPdk3GGO397KayObiJEzPEEjv+dcyMvnArYcn6FKVPwsP3+A31Dah1xqXBF/qXoYrA2JtrRAdPzRM+O5krT/EjpZP9HKp5HJQOXyDEU8x97MleZPGFXbLyq1K5wl89BxT4D7NQ4upax7rtf0G3gAd0x+6H16zVQ2fR3vGNco2ZpBCYuyZM/lBhrJmQVUK+6SIU/nb25+jUu4wpQdOjeYkWy6TwzRRdU+ENli+j78tP6EvPVME/HjQ+l4+oNJ+4Ay3F+zVN5CyrILHamlCFh/KGhiB9waGZ5X0mzevN8quyxiwRjGUV1BNPTdbKibqFwQ3AD3f7MHTgajuhhRqzNAJbOWDVz0b7qRDcrdeVYPIHHEbnjyALeKTK5k9ZxrbkMMd5St41Ir8r74uXnvYEDCv5SFhDbp6RN6lllvxUk2Cp7YRmfeDsCBzwljARoYJqXqODwslIto1qqBQe6pKx6GaDRjwVFkHmsWN4J9o/UImBWpmdkZrc/X2vTY2GUXMs8G4MIC2oxOwdk38yWKIo5Ch6U16ssEPCdBXR46bgM+UXo5SiHSyVV8VPZ91R7hCxbH9fVowtK+zY+NBlXtvuBakRP12wGv1OLp1iO+haSbJvz6KXIFp6weEzcZCbxIdKEZSBsyvzcVyXRRVGQjq01uDc0HnL2NuFvDtgLn/SHpCCZ5l3qhVp0z8YfQH/2HXRBLMLzl7RREfGUVb5u41Hb9xx09lmdokRctsJwyq1GBIQaGax4+EvCNYYAztMTnc8hV8nEJk6EpgUac+1iHsiTqIRct+upsLI6MSuJO92VqdKvNOo8qIngp6fn77ievyLyKXAy2k+xP8KyfCSk3v+4r0JR86rg5ll2DBq8O41mJsEKXCVNVu/XbxiRGa4z5JW5Dopw6fy8PDNAydLlffmEKpXdDuLe23zUdN6p2CAVPve0Jra1hBG7xtwSksrH29HeFXHtjKRrp2PgLR7LL/HdYJvXTdf58uDzPKhORf3rNj1dcShYhl7mM6hFef7CtZ38ZRVmanmvEY0ZK7t8VJhJRjyrw8xBlOz6yvdmXwpBD0daSm6oIkMalQoYcyDFOEV3CCKENhxbH4EnFPETGuxzakc4Xtj5iiKKHtI6nG0G76iMwxuN12+B18+txA1iF2RepRjKIlXWFCn36qJvrwBqJCGBlB+ZIhbXfi+3DZLvHbXDD7IDzYUTLyZayNmypC0mxwUvNeA/KJUWOZ6aM0DjXZyyGHo4tWaUSSA9JUTTpeR5TPrxMDNRt6HQBDGVrDqNYOrpmGR1zOtp/FoqPDvaE6A5afqGMykaaX7zURvlCPbMa3wNarAhkVMOKA5L20JK0TrLi4O11ASA7yu9xgmy8XuOMpRESMwlC389uddFilHLAtmCfHJrRFNoPvn7P/wtvAIyndy7awkUOce3D1SFrVHyqV2rpk8VhVUWGw5KdhZuEwFJ9NUwVPW/OegOuGNert5/bEZGf1ebqF3LQn+Xlxx5vX1XzqgFQJyqR5GgCHEloCL3RNVALhdHBdqEit5Ih9Ih88wD5YNfacRK+cxqFrEijgiBMoQjUpqFMxTEdhqJCQ9tdVmBgY/Kz/HS3OW3YDaKaoxYQ6souiJgkZ4zCna5qlpGCq4ZblaXOYci7QzXV0LWjtllsfta3tFBWzYqnxPJu+78mrjJrjPKfLzyrjHyCpEjhNyavCX2gpwAE+Nh8rf3X0pmu82zDQJjIiDMJLCUpyoYKIhw4wLZfR3VeArJKp1R6pUwuw7/Bqx76iyvqvypBCPvGiBYyuvToTpY8yx8//KghLVuqA6GhHN25PUNV1bFIXaff8Zv3gRzQEP5I5CQA1cBaXsK9W1nM1x6mDJfPfeptSBJyf0nHHPnZER/G972OSf5ZbOpgcJPhczgXkxAeQ0K/ZEAKb+yes79MSfDMMo7xmTbdwuZ7Fwhm6IkGz/4uVfoW5kqZbexV0x18PO/G4wLbXvkZshed4UuOZUjUesXT1TEJZIvwTTjBgEyU0DOVHjzWL6+PkUx7ZnF+gex8DXzE0cQq+tpwLbp38czfoCtNBO+RZToodioaLoMmdb+riGEp7g6QiiDPZUDBNi81g/U2pxZwTeLFVWYE5Tlkl+qSA8F/9nN/gJqpGBEU11if+29inAU3xO25o08FwzvRd+l/GFR15iT42YwQmw626cZbzasOlY+k1ApsLA5/qTBCUcA8cif1H5kMvfF+N6uW+I6z3LuZH5uSVaekjeKHk/LodzC0VMJVqxPxzukZ4hKuM8hlNDa24W4hx8Iwk9i3xMqj8KlR3e797Kot205Wkh3LWqRmT+W+MiVmjMUxxKy95ZSU23EpWuOgcUaeoATITnj0hrjRDCWh2oEmOZrMlx1A4005+KOUAR/PtZQoO6uZHcASfDtM8slaL3sL5dWQM/x1p0swcdSR/geVYSAbqOfXQB2w9VhDI3YMlq8L7iD1PXRL0yWMWey1cm8QDcpC/u5INPeZeoQyz51m4+ukNbFoRjA6FRRoZvlRg2q9qr0/E61r8teOXBo8cJKm9dtW1kk+gHRgiB9Vdk/JiswdGJ+k4L+PTpcqANlIGueSnXCuCWM1mzlamBSEQCka87D9eIHlIlsi1U21l9FFnrMuRcR+0Y7nSvso6ATyfI6CihXqE/+W5x32QuMKXTVqeG+Zt5JGekVda4CD6Qbcd9iJsWH+uXOpjtAHZ/52+H368S/g5YtvUfsvuWXwpLM6nx1dzau5Msf82MZuN77P6LB9CszhvMB6MV6fH/OMiUQr93VZfsMG7xeii1v5gehY/L+jOj3/veH206CGuPPwboyhYX29HREJZnaQAJmYTFm9U6rUIMOJ0Dv7/H/uwGGu0OctAhLnhqe1LoyDaCbiGej3TEOhRhT5N8vkkQBJpF0aLaSxcGed4ltFeXHi3muvAnH8+I8MRD+ojEtXyddNwYZVu/ctqRC3ks19w8cJi9cTSay0gv1zkQv5bMdynt7Nu8GbB786Tm1YOUXoHiuPZemk0KMWfb+mbAB29PNrX9JQQN4CYlV6uqlMQSGJ6mTEKPfE/WNHbP+Svifi4osoWaUlzaTm3S6nOxF5Yd78LGG63EWjjYQHYNvKepOtS+wKL3LefOhkU072NjXqxRDDBZDZPC4SnFPtY+vDuZw7tNXAyDVy/6YwyE8e3OBiPS9SBBG+BJ49xx1+nY0MPWKlX+CmtGjmCKCVeS4oS6De2+WTWnrXcSULJgpeloqMxLzomVa6uISY3aMdTT+PUYiaA0y1O5OkRUZLB/ywGJPzwdEEEkcZWWgg/dfalj2oTiaXvSQD3siEAsraYGOYSSkNkRwW8wRRsiBy/AF89piujIW+H1P1Sp4EmaWO9kanRgk4tPSSwiZI31ykIXYJ0xUVbrDuoOfFTVGIxytuMYUI/Q/oK4b/5FMwX/gp7tBmJi4Rt9S39C/3VwMxvZp/p7p+Iv/qGUZhtYIoRCTDatWwArV/Gg1uGCW9/5TbvJySP4IzpbYqFmwQ83CrBNpSMw/sL/puZW8ehv5RBowW6RcBt5OfpnhAdlimeG7XFDMFZxymrwufYmyB2jt7Nte4U11eXlEMYFTcDC245nxHJ0o6kqkQCm+da+eX4Rje71afkUrU0uYMTwA6HjzDmOHGyX/bFh1D68J8VvuJqr60KkCJV3yiHf+HEC0g63V1sc2X9Au3ZKBqevzF7BMJudnHuUhsjNLUmPvDfGA2tCSkrW+6tN87FKxsEsuTgE+6lgUneUs2pJoisgMcOIa5Z5siwYVLZ/KWTyI+YueIbKtqR4ye87qEhi6WaYZKqz/XptFx0I8zAmVeevpMEpRO3by/v0TInfRgUBDR+XjIntt0i+AnxZx7zF17O41VngorUI7WLD3n8EAOxqff32Qh/D3Z2qDMc2wS44zQi8Yj6EGyueSDf6sHUWZM8hSPtlnjywnjOXfmmbozSpJCisN+knHtu30iJ8/ee7G72L+EjEzbUzhQEU+3pr4jefO5tP4Esk8Gtw9OaxNRlt4EmbFI/aig8+L5FnI4yF5u6B68w+V6Nc3QoZi9q1zDylf5Ap5w6HS06FQUAKW7UDxraaMfOkbAo3eYKUvsQz4iSfitErQlrYqGo+4jslBEB7it3T7Toy8tW9aoVLNfOyvxQ13Nv5w11xb9UJGFmwCfSpQPaNrT8XR+bpUrtFFu4UNs81HCByt8J843he4Hax43VZPLT0jcUsDR6UG6fXZ1kqDtOyIGTKZC4ubszo9lGa2rO1UN4Zam7nQgLNDgk0re0u1g33zWFkAKwPVUP6q42JfXUsCuk8XyFm2geuiK0a6CzIRRc+L3SH27iWVFgZUnQpsw7Sdv//D3lAF3tNRqKc44qy9qlfFv83p7vYyz6xelM9JsMkkKJJsOjqlZn30vb+UK877/m75eCsdf6S8B8mFp+mgWFh9QATJbtaMLSo9tvH4K/U4Yxe9/yEInJHJMoqF7pq9iTbNBEH2uo8L6MZQjCbFal0Sn/mjLJ9eULbV2zb/30CWYXbTEjtTbuBFl/nrYFNMjBKXutIYrKhoSxbXcMwJjsqi1imG0UTUo6OeAG6zaFZaPLqf/ra9AWMRpn2Y6b0j1vb5SzWBd52I4U5F6NSpkXNjBE/lPwu53Zg5pb1HFvMPsw7MmSeOAYoZvP+ehwxQDqbDiRj493QREyAmAhMvzPufoR7je2NPTsCGzwr8+esZ5uCwD/UjM86Qvu4g6SAx2CYLIV+RmPNB6zX9NOXN85x9enV5qK7jAVY8MmSpSAjVlFBvIcgGzyjdkNgAzaKuU1kDv4wx/416KuNyzhETqToae1cKig1Xqa1SyoHjZBY+xHaIl83G0Cu/L2w2NSkFfvHk2NJUOHIqs+eyUL2c0b/8XVnhOSv0Qzyb6/YTu1Di/7AfCm5XewrIN44XQxzaZmsU9kO8ycD0UBkcS6cQOGn0VYEtRgEb3alqXIk48Fu2/75jfAw+nTaspaWAnyKE9D1GQj6AGaXOFmQWNp0e4Avi6pgh9a7NhhriQ8OjnWN1KLktg58CzglYH55+i8Mf50MlL4OncpYzyGUGIW2ZO1Oy7lZX8VfF26l3UD8YsEyQiuQ4ZHtOCoorN2tHi4gMT9/z3HOrenbumTA9z7lLRc0rQVPDYfoUwawpLMQTYh8Fquv8znY+x981nAxoOEHScPIZMAcV5OVeIYzlxeTlxnD+ijX6utGPm73CCOBpc+ghhAGM3KLs1ocat1vYrUAXqK/MR8HK0HjX6Q65ABYgVZlD5RLOmU5OvhuMC+AfmJw/hxmHDTy6MLw7bCXz9Zizb8WUXlcAc9BzugIkM17ZrcPPiyUo4j3ji8/ZH6pENI1HszRh64M2ETOYl4gbA69CHb9EUpRL2O6YakB7tyzbsK3crXgvcxp0MQ9UKwbHqTPxJVCV3kXsvjPB6M4SMRDP5Ol+ftbPi9acXoGu8yjBl1I1xwHaFHQXIC6Twmf9UnzFWGK8NwnEj6P1gT3dIT3HeUgKub4TY+wsgULNyKNmjD+he+sG5Q3GihygGNV9/0ODA/CaOCvOrjoFQwuh3Dd5WLE7x4X2gHWnFNuneLVIW6TjwDwxXAlTf0Ohw9/bf+bzQ33JEDCXMIeiSuypoFwcK3n0CL1GVpx6LmTC2bkjPQkmnKCz/A0nJfX9+sLQDoOPviCVxyh1la6vbcSh6murCwP9Mn9QTxS8I94rsD59vj6WbZNehnAIcGE9lXbEYs0ky+ADU4veUny/C0dhmo7kW0YDbJzXhTs0NBRSIeSV4z8tdXIIaQfvlXr6FjENHmTY/gnIoJ1yrYMWfrcFuPUAn7yGAMPAqjHOXwsxDG1noV3XatL2IhWBgo6CG+GzdzkKUpOS7/9ofGh4UL/7/w6BzL+WI2HiNB8DHBWcxw+QoCAHPDQJNca7MQ/uOU8909zQ11esHTY0lHP8pacH3KYDAe35yhMaOVx3kMu0rRjRa/IyF0jeiTaNES2ovhWzplMJQR3JlaLLKZYk9X+4fvioM6dF7xt36bix54zlhBMowUeVZobDp9w0Tz2fPw2HNObx7rKquGy2ib6oELl6fksCe2tKwdB7LFh5x/HTUbhSZAIlGTPrRSFvRF/xp865iUJvfVt5ROPzoTQJLVDze4kgUn7b7yaqaDHvoz5xm1DE15K2Kf1JQIQYxAjBPRuKt/81A7ugj//FyPDH3iULiDhLm8bha3rG/D7j0nwOM76CSi2nXIceSDGxQaHR6AuNCkOsi6wMxRcT8qzUCwxIYHb0fa04rBAzPsBvF7NRxJrigjKtvWek8tn7EnIV22nt+36kH2ZGC2M5/VJE121I17NMw69VVkfaxaUS4kSLArnjaTxLSLTBaKwxtJAdwSJ46OHWgVpDoZ1wF/vpP0I9DxuEBPtwCrDpi/glzBUWKM4/3E3utEUWJOQLluSc833ERNEUrAxurA5L00sxFwevPQnRmSNeknqICrDP49dEW/ECNMbdFkN3+BJX/bPH/IAWLlcp+NPTn7mktMokBQM6LK1yG0pNRc9Rf34AjquFiRxUjpJl3rGnZpqTTnb4EymjOTQGeN+GcHJhci+nkV2R73PSXZYOQccxNxxZNIPcjwEuawtDwGs4rNpY92t3EidEHS9OZ6i6sLhiWQ7oZoG/14OIwAvYc9bq4LuQr/hDkWW+wnxN1DQNmipKJUwe/H3QbeL+baBrAC9NN4QLH6KQUcnL+N3v6lrJfrwbSo3eFe1xttA4r8PhrQnDfoySmzdRpgIIfAfeaF6zk6ap+TAnmmp/BmfptiE6J5NFFrGxUh44LamKDP61FmdG2DQGxCS7lVLLkCfbB6cWliQ581A2gObn6mq1irb7ntr/Fcc5AbR0y9zrlcpCn2jPQx51dOvaZIl9FEqqJZouxQAq/1gXuGOuE5zfacJj4ts2nfWLINyuehjwCsUKom4RCoR4zoeG2pinBHuqDE4SejYWlkssHE/8XCZqxdkye9mt97mpaoYOb75iwYPUaZwf+miZFL3+Bbi5BO5oEFUK94ZJee2+d1K+evds6QmS8FDNN00SWMq99e3WwktFa96zB6M+9Kj09ox27dH4biF7S44HX+PSghhhxINEdi8ftMFoUk5yuQix/kw4eu6jjselOJhyrrWyp/YvuyAYBdm1PoNo6VtB5grXpfeHntu4huNY+s98IzrHOaBjMs5MGsOdRlrqOCTulDVfU5izEB3b9+ocuvniTZsjJLK4WgQMyBhYrpzFORQuouDnk1sm4bDj4dHB6vmLJhZ4rWSro7f1uH+9RpfRl7T2H3YbuJyLIRgL7tlgNpvjpNLi27Aszqduyw+Bo4/5oSihQuyflQbLDsSAeHTLyHnTcLGibq5Oe240e6F7pILP+5zvSHB92AHAKqDYKHjdvv+ipkwdFdi9Jwqhfc6t+MmHEnNQRIgDIDaymEe3fnmRjZpw3M7FkJl+jFBb2Ka3CHVXjLBh5eUWL1H2IpnfUtn751Mv17Skievom7njMy7gS9aok3b42NIt3sIRMrxlFAdhdetF3Sabknwspjt8ATWp//9dtNwqpdjuE4CFR/+pw8gCC6qQQen5AIMauCUDa4jw45T7Fh1EXlCORZmGKw2BhVGotEWOLvN//FpGTnWJyFI4aAnNIngjLShk7OmxGZhy6fX/4w35+Hf4FMuxGBSmdk06LU0Np+ApxSDZ/IK6UPuQBk3vXVVNoGU0tZk4QeTqMQ1xWwlZAtDCaasbsnX92k5U7qN7GlyinzC97eekTKa28w4RFn1RzQxgBSKkgysld9lxvM9WMv7G45/jJ3QVS/hTx8UokM/OXCz58piMl/qNICKpjKKJZkeSuB5awkvMRAyF/S/HHkX5M02J2sknfcGStGtIGavEx2jVMbdZQDKXHWZplmRGQkhwUYn3f3NcVKk0vqA6XxMP35Q5q6PxpZTxbbZ9a2qasXcLbd8eAdD2qLDnj1XekS3emR3T07YGdxX5v32iDRi5zhhRO7AICc2VHKZCIKLXfATGumsL+fqQuC2liqcTlR7jBuevpgG3uOrP8ljv2RPMG9uC3AJSqVSLPhBnVcHpmddE+3N8Dt7cAkZj6D9AloygR9w5i0s/0vzMn00VKyqN5m5zJMRT3GeCoPA665sQvj/r2KcgU+EoEE17T00L55ZMCFhIAF93lLJdPNxZ8sI1wtTX085vANYnBO8hIJvzhNtrEcBIrjj9oh6ah2rnB4hsraF8JQUU3BQTSSbQwi6WWCKRnPKX/TWj3Cs3HSSotEZz1Hps+tx7i72CGdqBzU/PV1H9uTGvFTzZfXXG0DznYaFSnvofJ8qsQZfkCCZ5KMFaXQ8Rt0rPtH45GKUOh3sxO3BXCuPXMEiYAdaLCcz24b8dZCFV8+ExR1tFWOg5Co78Upu+AFal8ciSxpgahecQp9z/FiFK7OmjD7J6Oa8OISKEfKEiISziAEQosMQsmGe1mNRDc5xUPWQM6bdn4MIpediIdUkZ9Talcdyyp4umKJdVNqp+WvNgFfFwYL3CQnCtr+NCvl4ybn0paqyJY9pNOeC8qE1xz07bpYYylqUQwPcj79B2TBWigcA0VAXQVg28hIpusF9Egwo6BMdWOe9/aAI3psLspq9tdzGyWL4Aj0lpTCzWHd7ou/DctlYGe/oxIbKt2Y+sgQuV07cSrVblOGrqeAxpfjsYkwPdBBMRhMnx3HpNXAwmaseYtXlHKQRfnqMDh+ihajQ2c9gmgcSLU6ThoW0sUagqtqE67blL7fytljA+JZrE3dmntChPStr78vATCFUvk0Ux0UBHlD4TtprLnhIs210WqefyTStFMgzjBR96HcZe6hHli2sWkrqy0P3ddeq+TJwSypZ4RNZJ1HhiFB5SwX6rECiSbFwr2qlMat0g/9q17At16ARbKMpp0/mUcYFTogaOYtgxa4PRHmhYZcuWRe8PfeG3EBiEw/jGmcMD40wWBRMAlovF+4ts29ytVNTvtFqNQZWW2lFrOI0Trt/l5elKNyC0K1XBSsIqW12/OQeXM9xetJ2p0ka/Jr5mmwv2QB+xF5Q0o1CYM1bZgkb00FhuX7b/nh/aeLZwTEq1+/vERekpQjQjbLkBcSqtVbzmgmoPxFLKn32E8LdVWqGuozHKMKTJPSaQYNrx8j3x7Jt/wRFlFZqOv3Ua+Kt+utub0qUZ8UVtBXVS92qdHf8vz94Zr6rwzqvo9rQ1v0FQziFX/WWA99PXQtVMhmeecQEJqsxgu+kelHRLrT3KtXJzT6qyZlyE12BFO/zge8tlC58P1vWn8OrPRzyP7uVnQEZIcsmidIS/Gqn2PTmFzK7VJ2c19j42HI6Hn1MO26qs4nYoK+q1qBCE8dWa/auUo5SGPpceQ59/8pN0C/BazSwIwmQl+0bNFIFsiRhu6CTZ8NOmbQPuIU1k3aFhn76sDhPX1wgIfvqeLUkvv5dSqNimW8xhUH7NaLR/SlmbN9ofAgkUf561h6Y4JnmEoUjnb7Jo/uBE8rysI0w07HhW4HFMSHW4M87xmEOirPUmWDv0HyIcudjB5MBcTcSNqwDCqyMXNAxAtgD1kfriE7H1OxHSGMJzfyoSVLhjCrdU/njmL2boa4/DT8tPpnuPaEgOlTcnSjWiqpHiTT4MZhMU3XwcEXBWa1CVcs2Knj0nzCT45ZkByzNLpD2v0S5yQ6QQnMLYjDKeLvdBoQyXMPIhJErX4KFth74CbnQLCA8h2NccDfcO/IEaDlrzyNHsf+uG8tYVbAS/Ao/asnVAnxfLjikfGLALk3LagwqYzYi8G9CFRkvwFWdlwFRWsBTwMBRSMG6I1580GC0waT+Vxo1b99xzcNQpOmlnNSuBcbeM85WZE7PQJkBypVf4VQOs3Gw7kGHs1mQtQ5NCoNNyj6X0bkvj+86d+AFV+wMJwtByqc1PTQBn39HNrOQSwRd0itz+0ZkrF4dpIDF0UtA8CJlEQJ5VSSyd5al3cNyzoKaP7u+Ajt7DVEE7bYhuoE54euvwhAZ+x2TiPn029RduLcX+TPhUuwA1OUVmvWionvaEnL+egprxoRJukvvV1orKa1kIqIKbeYxbkdbzmsWF0316U9xEi2vsIH1zfhSfiUkEbMB2HsYj9TGPSulU0NSuO8bBG038JcSNLxdo/MJsunzEzvHpwCub+zsr/sJ87OJmc0Zw/lRs3Scan2GRy0KkDBA5B2zf2hIc5srFeOyd1bhBkYcz3upx4O4bDhwYd+0lb7wDOKsLSxFZGj9aQ6yHXRurkpcyn2hN61qAcvA9v2Q4+0RahKpK+oFsW2lWi0U98YfS9CvGDLz1nsj2frOEq/Nbwza7C7W8Wl1QRaJ62IafOzDFAsEXiNm654qqhmLC7j3theAThSb5Zo/qltp1hg+wayuJknn7HAxtZa59gJlp+rloKznzzgRx42VTrhPdUIvK0TalU+oNakI2K4NDaGvRKwnjOqZGk7GPZpv/5IjHPT0xQn7x+ntiMJItKJxUH0/NEx5D8Rj4WfQG9g2v7eYek/bonRQiJNf0mfZEWuHcgEsjsFRZo+zZtNnM5mugcYMvGJ+vx8afiVLOqbvMfPqVuHEZ5JYpggSaNa75+XJIGkPAojqMEYyvAhHJ61cZCXjrWsz8mLwUhJGSIPgXG98pbmFiUhUPCpL/M8VJKoYp31tHtQmO5NguhGwQe8eAHBvrvn6hm1D+QnbK09rhPRHF4HHateJ/aR5FiYWmq+uMwVCbuRTPq5k131J/xzRN5PnA4t3x/KU5U0Y2Sbb0aLYBV9JSBNcWF560BeN+Le5Iw8xzMbJXZntXsuQzxFBy0DFtD3NVyg34QqKNq91kwFYGkz19Ins6l3ombnwvMN01H6wrnB0a8wMY9QdRxk6ICBKHtG+TWLSZm4VMChO+JENnUf1bhEPn5/Ml8F9qaKtqrWEOFfDSJBfaqhZpsW9l/sSzJMzu36SMV0Q11NmH9/2hJ+aHnz+XYmf99EInEOVFNNLSjO/UFgqB6V7STMR0rWU4hvq0IMVxO2guvrIbxXwtYTzZoXY7iR8cSGaj+IHVejKI+2fLgfm7GKcDJok2Nwpd+ks0kceHyudZjv1rwrPp6TEDqkXzwP74iCUfN7c4dwljx2wYF8b0+bbuXiNWLDsuk+HNbK+eV5PXO1Msvf+eq22THNItDTy4dxfsNupUQnhqw7D8G+SwVtp/TAwTMuZYWE12kzmjZ/nbBW+5Aa0lCzP3mdBCdDDXivWnVJAyXOGXoHaX2ePAXOHX/w3nLCkSR5Nn7Iy2pi+XAWjiWCVZz8w/Gkhs3aRZ8u8jcrzomkmVY6/Lz5z3xQX0ItwU0xdj58tExEudYfx+jR9Ywh9Ls1TwyOhVCCSe98USM+MAZct7C8zUKMdjfip9BB3jXV5qZco6+htlIMdhHvKT7uhLerSdKFmKyT7jpwgN7JjQcBSS7l1SQGFxou4y6RlaYO1tWVmzaLQne1DKztZkQDA4F1hoPk1nZ8YzqvAy3Pfm0TUF9EwJy/cYQ0QtzCYQV9g3WX8q1W+y72z3vOdRSq/Z2oDmTpfre7BaPUNtWIkqwaW+lzAo5eSGfMPoKmg6gr8/AaG+a02R0pYC0xSZvdC88aTIiDL7tRqIbOn8+VRM5W0D1K42bZ9kB0WTRyI2qo/ksuXfW2gxS2y1RZTbVxymxo5RMmcSXyCqdBZbG3MSE4Hsyh0r41NmG7bCR82FYDW5duSYd84r90Lni+6UPXtvnYIGy6QlBkemfU+8j56CAf8BRAzVWx27oWKUzUlDEQz+0PqETjvBKrjKfjtUi2njyEUVvezJOWdhh5tbeZjY8dlCJe6ucVC2Flfr0ZjzHeQ/JQ2hKY5Rz4/AOX3NmsXWVF1wU8Z2DOIY9sNpBKMmYPzpJaElzCD7o+7IczqlDnhn5D1/2W9BqNEzvlNmoX0emSoWaQsXQ86xLoSqyOUCtChi0HtrmL3Bqxu+1f17ZwF7xTJoI+jcsJOiFcXwMefb5gw6t3EE2qxB0g9VS0K3ywaKqfZSMNI9hWaghCBlFtZy7ImnmMiHsxfajSJPOuFrbXkr9ExaPcN05tT09lERWV/bYi/LHNH6xbtTkmv1BsEMcUkcyln48TparrzjMWc37NjmItOoUiLXefPQU/jQV8bm9gFn1AxTLoY5WNTwozEAG2/0NBXlutsMXpAm1cZvHXoCZswdJnkw+1Wbtl0VHjTtgXjUC76Ts5gaYf6iaH+AeHpNy1kC9JF1Mrcc4NAOag12SwBfMKLClUJYoB+xR48GK9QnL/mQBtdGB9+/MSnd0XUc15lKxITZuTOFnMIKIX+ooV/95tJ8sdLius+L+71WbvijdIMPYsntMfVAFfgzW0YVUsC+TXmJgj2WifmFSgphxcyFjLqfShidWX7WxFN90FxCEcyBBVl30bMczJ95bQWv6gEO5XXUwwUH+Usm51kVsH/hu8ikdXjqDcNcC/8o75eFiM8MCAXIxUfLdDMlQrFGlNEIKk1BkdSsgEc962JTuL4VMo7JKb9E0Kaw4Jli75vG+97/4f+O3vUd8uCjPJ9MH3v1gd+mTCx3tcgZBkST6pzJCpjptVq0fOy9e7LIQ69AQfhP/VMTlqS321OnHM+sL9HLLXn1PiXRiFFepQd9JeMKKNeVLcGNoXjdE257i2Ya+L6T3daPe23weT2AcDn6jlKDOFgp9Jg3hkdsSwGMW1SqHvo7ad7i31+LEpLpgCR8Et2Hpi42KgLoCnRXKM6/1iSyyjhA8xRvhOokDhDVdMxuQ0DJCOBbL+wciOb1V4TVMCXk0fzssyLGkqNWo1oOl7HxaqJDztxcm9ygkYU++yrDkmto4e/qelHFZLSwTlKfGMz+iphaiXVvCmBX/BzrHwvnDUrHnbjMccY7S9ewSELXLh/wprLStLA1ZieB26ZLFEWJrfbCkto8G+FJzKZkVtIvX/IQTB1Oe+xd19LkOIEd14PvX9OT9BTlMQ88Q2hBPfYsxH2j6TF/Qo0JgriNL4RgaswU2gCCtNDpqxqVvDIheHP6KBPK1MguIbrsYJ+JdjdE6MecC4v1DyjU76Nzy0OvJ6BGLKHQXu8MqNxOrKQ3x4oTn43KjETGoqiFvUnOrfOgZpPlvDCOxU2Ah+zKWNeX43/mLu7ATtDrIhWxTMt7nVjPPdS/0DvnmCdj9cw6FaxdS5albSqpwCwtBqNX4lgJKQcvDIYWJZ/QJTzvgTkpicKJhVuURE3SubrjjTbgUEmdK3Ug3YH7/G++KvWkE43Q6q9sJhietGz4RKMp8nG4dEkwKw8/j4K0JVXg2E/kUCjxIr//WEPvTuIakxGFlmbGyIGF9/9s+KbDLyjCQwDpvspLN3hnQVrQsOg9K/4HrJDJzHyRC2tLRXeUYNRtohB8UQNQVl8U/fbFlLhZ4TEFh5RJ3AKn5I8nbdzxJJCBPZS5tsmWW1LV4KbJFlEMFV9YU446T1Aq1FXYCclRc7lksY6XXx6OORNSUukvhoq+Q2mRspo79akGYrY9TZ0vvh00EdxknSLZIEqcUWGsADgC+fp+MrH0fVSVjFv8JmqIHHtGZXzZtqHWJa4K4FUKNNwlrG8iEUbnAQr/OaWAAc6sohUwF1+IfLb9cMb2bphBchPty3rnMxhouBREd0fQkA4wn02UJxqJ7SM2EVtcUlx2XZuoVEMO1HJ7pk7Nlr2wD3azx/ysigwo9hHUlrRzxjXqL6edUpXM4/PnepO+asgb8ILmdywRu5xscsj8t7Af/47/aby/vz4jQNS0N1Y805VOy7u3eqqCL0l9BIacb8tn5PJJKDD2BZ5rUxGlqIK5OiqwCxXvqzogva7u1KlSRMal8hefte8j8UoaVjg3iyPxdB/OTWJ6KNlYnBcNOSr19Q/Ov8606S614eXlbSp2HJZUPMINwCSq3QFrajT6iiukydNLmg20hWTO+u3csCl7T37vCw327Nn/2W9h6HOTv2olctH3ZC4bPkHiIfLLSkCNIhpiXSWtxb4TFuVei2Rw5Sk+MyZbRtNX7Lfr57F7pAVP/Nm0iXY/e0BKCP1K3a9F+MOQpyq7Vf9Y3qYwu0HjvTFt22doueRG7h0CQu4F8R5rJuMrufBC5275+D+T0bI8vE93n96IG6f+SKTb4C8tirLJSN1ZSudt1cqhUwubTbI1xQl5E8JxGPphpyxhrzqmVrUQBXC6b0flO8Mjev32vVaFace8t04teIymyzKe/9dxSsWul0NR+FNdVZln4ZHlvLrTaRQTyG3o5SFcuA6gz56YKDNPg5rvvkMJczf0FJo/y5K5X5f/HOlb1znr9NOsyDHHMSouK5Cel2U8LJ0m6QW1wnJDOL+gVAHvzyeeMUcFy/m27hdHtqFBCW5FaNejA9km0NI77/9oLWf7mItrsjTe0GrZv+IrgpyyFUY8XwZoNmQsbvLLMwaYZ+CJsFUTmHiMy9u7bLh+5HVBYDoVXO1TRdyypMA7b50EZ4fTKhngtJdw3JzIAv2scPHJdH09xiaH2B2LCQFx9aGSWAK8ewkDETTV1L+ZPXQxdhabYJly44zs1cPeGb6Q/X1mwk3PTEXiemZmbdIKPadrnlKh6K9mMZbRRkMOyxkTXuXNQoVKYKq6+YlnhKi7AFTfUeiELlQ9xsHo8cA5xVvj+IOtzVggew/VYLY4Ne3FxH6f4XOUKsXniAxCw0aNig0054mfSWjRKgd8/9BeMhaGiTnz9HHnYAcENpyz3WVJcnaoYGlJ4VAu9Qa5rhVcaUfFmHAq1EsrVm2meL3enNP18+2ZkRICx8/5xLilofe3qqE3908n3WD76UDI4P86F4WQUCLYVPeY7vko+npyBfr7g588nxNpy5EufQwp1JyR/NWqHtRjTrWF4dZbArwscox1cAOYdsRvL3mNcEIvqOT889ne1eK8EnEbbcWtNfS08FHssqklpkr4w0uEo7gUnu4WJpSimaX0f3zMrdW8ReOQ9HG69rLAQY0PpfG2upl0LjhgaOAoCmxs+Hwqh7tCB2izUHLkcxQY9uREVS8qvxHj95eD3v93d6VJr9u6ci9vAV+JEqlhMXf/23i2bHESRgrUkfPHlZykEtMkQaDR6C5o64i2LNtRsHu0/FYYT5u1TMjBoRaByuzv1UMkYzOTjffWJpFpLpUG91FB8grrIUdu2oV3LuOxgQCo0LriUmwZ/45jYjo2AslflNMQepHuK4fTFVxEZpnNfZNz6wt3ZaXiqOJwzqHQTjBUhzi3KqunTydifPoD3fz2hQFn2VOBi1BbqlBjF3GZ8oKt98Rs/IJUZXNOCI8PBRIc0ss3ssdTxQKmtMOP6hB5FsCQQu1XmaCHEI3fRwb+lWXoLh/PQTJ0D20UAabUG8VesddOrT02ashJo5Lq+pITFR9J3HyMH/WUmgYUVnUTBYJVwqLvk32lAEIIcokL8GiSiQr5Erg8z7Tcv3wOH5QK30QVA4yckBUDZREzgz1pg9cdLJASgIKCQuBGgjl1FTZTGWvrZzvEEXOgmaoyD7sYWl5JyvGr9XRWBmuFh06vna72qe+SOT31ncROZ6ISHWhuvlBdxunQrOlgl+eGmkGYvuQtcvxZqmqihcHhkwu1KvMMYVhvNqPIvukkpIDCiWwD6cmVPX/LypgYQvzErAG4Y08IWhpG4didUQj2bMLK5SJwWQBHMyyf9CESCSxdFr6QCZIozxrJO7gC4u2R/ARLOV3sJg8pNoOoVxDY6hiACUvMQ5whmuCIZsj+S1aLk9rRMTnCsuXjBlZ8hgKhhNg6ZOJI1NzUVuHt3zgQpR75U8Ak0J5pRg7q9QoiyJJcyIwtu+n+b2WuSzYFiMCBt66S6L3nqXLqmWi8oAmiAdtq43jWUJiacTpOh0A6MPyzSYBvtcS4Ygrw/g8vjSrUSlQp+GjfbjvwBXQvs68W2NURx/70snAFm/ed+iigp1QxQdSgKqXpXiZpGMdCSMrzCQj8Yst67L0+E+faMnotIlGkvHZFO5RBzZmmWMEHvIy8kf1r2JCWRFjgtIKS2YKJzgb2TaBYQvaF3UPHNIR053w+Q2HZIzgPGM1/eebvRccDtxXxoOcvlSXlEPZO3RgCv6sigTtgSUul92+HjyBb/TzB8PUu/JuBJiIzkJ0CNKsbCpDAAsd1jGacPl1lC7SqxTQc7QRjZYITqlNrE/Al2flTQaN4ldHfpvWt7PDP6djAsPOoy8vi3GOhONPZo+58fwXgSus9XjxIF9fgK/qGTPVCqbkMinGPqE2udpURMBrQjLyhD9O4PldA7IYETI4A7SANK7iOZo8lTmBIHYRypNRKBRKe3Krqj/r5xIFbMXf9/XxmZbUlX4rh7G3Q9//30RhOP+khcchT2CgiY2NqRJOCjFt8k8Ln3A+zNsVXfwYDWagoBZ7y7A+lDf8tkZCM9ILckHlAQkLroUXdlEAQKKbGFgfU1FqZMoI/1udsTBtpltXHsLMpU5QyAIGmhNDaQLAk/KHMVBe6eVz9rv0OjF30G2qHn9zxV0GerDjogPlCIW4Wj2dduTVujm0NNZmJUwMgLk2rDReVY1IxfCm6lyrhEgEpmDAhF/j7GNUJQyJq3VEopBSjA2UF50G4g+uhZgvw+4hptO0vmILbDb9n8mHQaI5n2Gk/FBjxcZhQphsaLELOihgQ3ae0toueQ2i32OmNUuu/FNd+rx30Wcqo0SLhe8Vn7kf+aAhK9lYgyW8FP9+mSQioF58IcYJ7h69RG2HGLe6dOyH5ZnU7UKmxaoZk6i+t1d7vRIALURvDFCyAetbOnoCW1M9EgEPo5WdioKmpLLkeXqNuC7cAy8t1Urg5Xr8zKEJsmAgTmbdcscmQY0soKNe+REIutD7lzJ46bHUX9Q4om9uHYoAstyYzfusgFgoUIpaeixDa4hF6gCASXaBSkOOWLasC2kqhcBQzMjOgOEP7ygSe29WHwN7etxoOtm/Rr5jwUS1TFzOlfsMtUJIL6bmIzwD0EPmpWMlN9Df3UM6Lgjta2Qr2aZvj8kwyeAx80DUebimGW0+UIy95CuSiklyKHWH5ZCIIWKWTX8wIddt5KDWSRYFDU0NSGiRAWKZm10gnVUTE39cjntnbqYZUOE8MCqUI7IA1WCxpVI+wO2slyoWNV2vFSk6bp5tE3hBVUItRZBAvTN+aDsAITEGulHSYXLssc0AmrpEILFK5aKDAHD+lpaF3aqDDcQWSP4KBCV3JE1IypWX0MF1YJiMw9Cjf/5SaKtiAvunlDSM8H1RKf3wm8PljmG3mrbGlPBlQexfYZTlLzmxPp9KmO4ZVeaoJl/xTw1DZhlyxylRZ8zQDXT4BFGZ9TvDoOwfmJxNCogMTlLZBdVg+Ado3ODpSkZ9NU5bS+E/uFEKGkg8fHaZh7PsmVWaE/1KTomwegUENnm7GAVtWPCnO5jmozFuckdC9BDpfCGRJj6mbRHfZrTuP7vRjGXtoxF9mfGiRSdPzXPR2vnG89J6bMt5wU9Iyxh8x1Ttt/9KGqeqoZiWozlIjqJfvlK8gCViIKLtnywI1ObMuC9J3HWft4loSlTGKo7rTtl2peYB9u/nWzt0fuJIvJ4B1wdJbVw28C521B13uEAlF9owWeYUr78ZKbioEaLp4fF0wX9RcNcCJbixsbi1m2hw0nPpziRfwpIzDwYXpSvJOeRfL2Kp/yfrv6SdyCgdrZDy1nJpDLT0tttdMPJGXvLk6DeNw2KbeJGaffVMPtdi5LVNXviHxzrW2T7K5P7R7zDvFk4mONN2ZE/8nKDsQak+ehDcpUwIWu0AF2z7Ind08sUNS+f0z4LRW4jVpE7e3bhfBAmfpYalaYcI0TpkNrD66uDi+0acrLIDsO9863aCecIUU4DQV3Wzjbj0EOOWxU6OW2J7cbUlwTa3JK5gRwCQvZVRsedWBRJgxpEmWOmUxKDqQnRNMW1GPPJ2zbFuckLXkXLuvBQ/lYiZxObkSONPsr+2YOywmm+Im2pil3gV54Tvk8r8KSy/m7aYJYYquA7sm+rGbGzu0AksoQreK16Oks67TVUO3zx/582yXe2Hq7KnyaZoRY3eSUhc/bsEZLLy2jxBgmM6ghewUEvz9mjpiHWSnkCBJrudSuhx8VA+wG5o6EmZAw+IMVlg+zT5E3KU/il+9X0zZDW6VYAJ6c4UADZMvagyIh7M7XgoVokINrrrlWX9IGKcVTPYVqyUuUz1ScUTEfw6WMcMnIXct6aDjCKJKfpK9iIbIy+QPIsxo+mgUwAvmGNX2+qfV0s1Tj9BZLz/7yCDH57yrh23Img+JvFsoSr74jthUfGhKGgIUXx9/l1vFONsGyT4FpNBIDKlRdPDwEOEca1LNMNA+YmiqREA5og5qCEVLxyhR+sJv6PmupDkfe74p3VlYUcFeeDYfo1XjXMrTsHiYLHQpdaE7z/Plp1gxnzDNeRPLFDUBdcnTxqG2jSdIi085advpDFA39KX8sv5Q877/xlRdo/p6ixht+rFGfhgaAUKVhcm7v7mmRK2LBAV0NgLVHzs9YKe/ZKZItzlytywZF86dBA2IQeK+benxL/7v1Bsna0zjXCc6NrfgG1XS6HPmpXHTAQJDxQOs2KdYj8i5TDLkXldrDdDBlrZYPFm2HkAHYbm+r4xJha8GyaUkcHURjAWVrXH+hwxpQyrY2SNC1pe9IqEWWFaf/6oWyu0GLKQoo0VSP8dBx3JRmnvaJhZgYYqHD3D6Zm88gTUY4Bcav6OAb0C+/vq8/i2zu9yRA/DK5rx0kzbiVgrCtKaNzs72BLKlF1LCt5NdN6D95ArNPg3NTjA/h3qjqsyHwbUKmrzexTFcU/NhB+B82TedJN1PNpUBQn7wRSfKaK+OREY4/MNk08ob9WV5ft5hu4YhoVSXfF3pRwzLqRU17By772W3wUZunGAisyxPKhpKWqJzPiptNzkAKNCCmCJZKmgOJG2YtEAnU5CKcFP8dHt01giaYp8ahtacZLq0RGRT7YweInTzesN8UrGkH0EXT1OFc99qQsKreeyPheMm0Stj6OVAA1bges5L4xM2wG6PNoEeg/IeeirURIpXiV645t6kfrcHcpkh8OUkZ1ub55DaHFU+EN70zBPCBtm1a4w9XyVWUhsHNzQwZDbZbCbz6s4hsJw1IJ2rbGPgkXiaCgN9gyCqgdcBbaPS3d3esg16UzcVi4HnZ15lONhTLItc51Q8RKsW/MqqPIGtitENmGFT3Mtty4FkEl3vf2kEBOcoJHVv/6vZ6Uj7Um/HS20ZxQ41AzSKPbQc4kVWWtL6Bh3X/8BPdavk7TcK0QAJeGvY1/Ek2JID49fb/S6P5xZ91f2DTjk/yqFf7MwM3HfQ8E/2MFUsoQuDW2i83qLea89ojUyCsjR1pLbK/lhB9gru2EPP7qEWnSOJckK+8mltuvLhtZMZ0dGMtu7S/BPIchzxM4oXRjKe8hZTQUN5W0x/JK3oma+HiFjVUYBGwKsSgOr7P1Q4Xyxj7DyWKTNYTakxdYy/+6kbweWdbikbknCPvqS5qm2Cs2yGPSIhffBaOV3sdyzmyq/RWFFtfcyvjHtVIO4CtV/aXVvzZ8T2RNJtu+CZ+wavknGpHmFrMMFyOO4bxY5fxEU3sjRFSTokuvBN2v3A8/is14QhWLstakbd2saqnFEf83NphoRy55I+Q0JI3PtJLH8c8sZfXxXeqvQAKsJ//2vJw9roi1ZzT1Ow/BGayXYBXGULcDaSCDn9gTmgjSsUnU2M0/MPCnStpiiGceeQfY1YPPbXopRest5i9/id0OviJ+siMbwMd0x66kdSFIuijGJWYGk9jWLwqRQ48IG5OM503wpvHzvVzr3PQICOQQbKkXWiPsYHX3plG3LncArEfu8eKl4vvtXtxpBqNkSG/EBUZh2AgK1nHRGjtWsFqaOPQZ3VSKB28EIDC3KxljJdEIVf7XukC0/kzcXBkCGReydTDOvQx0CR5wAtULBj8gx76YZiIXuXvqVArBZBR+DnEzmbb8PVbPfsKDmfrgFR6aslILgEgUnr9kb0/t/UNSGJ/MCd8wOFQSUZJ5Vw69udcoFOajfXxryUJtkl+qPKXMptRoZbbYbiKPMWHH4lMj51Jjsf5i3WiqGMVSw0uGlUeXj/B3C6rK1N0mNOKgwLLp5i3H+IbL9bb95+/HkRkZYsHRYROf7PpioiA2R6mL6ztRQFmkLDWpvWghSpckSvGhwi60STiSAh/EUunHEMcQMm0HfGMJ5eSp1waIecAVkRpTsCWgdd/kEpl7NGMshdzhEj4Z6uAESo8brEB7FVunIEJHIEItVusTGo3Ky3yzFw9ozeR5Ah9yM39fMb1hcVEQ8yvKfZ3i8PjWry4qDg4PaULSweb4aFcenBDkV0sxKwzMiy54Dtb5sUdIWrSpdRQZALLCSbnpYmT0zWCZmPBt+lZh4GBdVDm3danexY4sucC9MHRk5KpVKTE4Z52ZbHxKqWgU+XVYxd5oGNbD6V93sdYqPKMDNjlBD8QweBNW9Ym1dzs/vG9/ayeA97ENisdkweTDrhFqk6xhkgESq3XHqjl/nP39JtzlYyawZaMFhEpfiRmm+2ih8gz7XYQim4rKkhYc8OEEq47tlRgZGlrJUoEiObKV9cQJpXl2GtAepcpa8bHvpOs1S9RgF0qdg/38a8KsFU6Qj7AlGw2v9chQ4cuacI+GSuLe9drv4okfqn2kVckl3da0nUskZCdzeTTUjxTOQaxz2YdKYTQqQ/aGUEWR4MQYrdrwDLgQBXKe01vxKdOY+2drK0QtW9nsnO3uDqlusg9k/NjVfyuhFd5rHQ4dOES9nkC2Qesl+8h5K02Pcy87m6jdpOja0RKSFPZFridKGdU6dzkL9elgjKhWjTh6JVNhVQjaGesEPR0f1NXp55oFml7KVvAggaY5UzQVea+Ww99x418FDaZNvOB/tnQiVfZMXgHa7mqQfYCuTaBR5c6p2Bzy/uKH/93Q1DanWXmaCJ6jLS5wadfcinlnxwq3nMqIQYDL0IHGLYkmV/2jqL3S5aJGtOSa6RIqyjp9VpmSe8KtFHkW3+Ax8VAWbC45X0uOkznxVhXzfLlvr3dcND+7qs9GEGhPeFYLIfS8b3p+AKuupdlkIJwVYwgB3xe+jQsfDW3Dv9sX8+tJ2khFrcVsxI3iY6/FO/3um4jS2/2BWRMopYpoalKuLVEgkJvRApwEbuofuvENRYC5GDPu1Y8CiwNRIIbbCZ6kmwbgEhWAUhuAV/XcpTbUEKBfgH819eMJmpDA+0TNj8o2P0Po93NwEeNRPrV36rqVX6pDk33fPFH+ml0mwn3/bLXXOW5gOOuuYHx199HnFUdDgBXxOb1pL2WM+f4qplGw9A/Bal47S2G8Qi5i0ha31J6XmZOYredxJkE+9ehv0bKw58sTYUpfELt0w2uxVPqE3JkMZ4aELcd80gA6ssJiTtIzuzMwccTiBrZ4Ilcjh1XQjfbNrd4v2c5x7sXLb2XaCP5yvXntpSbfYOnrPt0oK9ev3EjmBSvsOaJJgskfyjkSTkgHci4GxJrsW4jBgA5ly6hfeNvJavQ5eRV4jXOQVqheC9a1rghg3T2dgYEPwEkJ5A7tr+D+niY5kiN9FzHSXdVSOdyQN72aS5CgRE7K5hrcp3AmNybFrmR8gJlAjndBs+hftqNs2oI4+Jn6IOdjcJBZB1+zAIQgRST/c7adTpITvTj2SFVVQbcqsZuwxiOPsVVGlgsyUSlcdTLXOfc8sMM96DYIaXKX0yXkBlovRBKVt1wkuMJ7oAVeWTnT0UHtME80Yl06vWj/PAnQy2TFc4HUxLftcNJ4m+dTruc+BLvyQFwa5eIxTDthAbDrY5TCahdsY2+WltIjZLb/Tm0ujemL3Kmtmo07PsUJmN/UzyXjJIxinaq7Hoh5rmmzgZVog5UBgLT172PkZfw1bvMADWP2X8ZUWMiHd0/2ByhGkuXHJsxBAOkxx8hC0JqIO5LvhcagcOwhCVMzvOwgh6B1eU+5g17tJ9fcwpQAWxEgNTR0l92rNs0fXVbODdsaMxDyVCKvKB0svpprRn/5ylfUHsUz5/4dwYS/UbCff7KyCkWzTBURfKGQ48pGqZabucsSra1t41P6kXW0t1eSp15mojqoMwMBi/Wjy6cLKTWoj9tHQxGuzX+NLaZkd0t4mVHIIXp1BwnuMRNXZY+2IohAtt7XBFExDwmrGChNxBk1cTpRkxcWpcTfUg1MdSXE4l5+iJq6aQlZ1GQhwojZMCJjErSV0s+Qu3xAanffwALlcKkcKpOfgvFZpe2zHJo4YoBVqjVHwMDx0KZmrst0NYyuv6Uwob6pnTH2gkcd5ue9mJt83oaJ/7UQVkUZeaS33enbmptT18kaLh2FUSeYGcthdgGXLwXmsOqosKG8gAmzTngVN0ecoT/kYIvLvIIaKF2IIUvpO+OxBzocx5DAFX5vYJup91vJYTvlyu+Gk05jtwVtAPHRGUNEHdril8PDO245QiTaPH/FoKR8XQXykX1HIjLRWhiNdwgz5mNvs/HWwjOjoruGdpvEgNhbXwwP4WJ2JNWxYDzOHNvlvVNmvVaKAFzxcokJuICzJmsqo+U/srvK2Fm4thx+lqqkjUSGIGaEA8/K5euZNPTeF+wnMkVdU6unXheGFsd+5TsmN2fcLGLnIDpTv3zu+X7FyaGWN9wwqecQhFKoQHE83ut2OubWRhMfW5xJuGms2TvXOUdxvk5yFYoc4RtMiBgqqnwEdN4nQefDPbR49UUbfcPSBjXZLJkHLHWjRAfiVl3b8TmbHeNDlYgdt6FjcCJQHBqV26VDA3oUh6WkfOqH7SBoNjgrU1DJ2VmspkcIIfFBJ7IDgNSztvXSHnAqDez9dW4E5IpehyH3l9LvF0garZ/geKZtwQmSDG9UzOL4MTj4eONMDvIgU8b3//5HAYOrkjSU3uJNzj/QdjopD8TdQV4gGOcAR+rSUfJ7sBlBN4ioMT+QUPNpaOuhARZ/UgPOdwTRXxM4TAUOUfkoJQ7/UY526sH2zQkDz7ni48M2axAnVzFqE6CJKBbaNf6QUzof3fqCpp4OdTKqDBHEIXNCzjCbDDjBe8xU9iulMjN1kgPIssxlm02LgU48u6/sQgW/tYpN+W15W40KTumcIJK0ukus22EZ1/rx6ahfKMlbUJY7ik61Qrhl3n4JN8ji2eilt4yOlKP/NIiOZsyzHr3pbJUHmKhnDl2xRiL8NOTuZEPMzrKZKeB2CSdEjnCu80gnG3IaWTFY4IwCDvRc0RO7Zt17hUX4Ei0tCDfA5Fp4XxRdUSOzSWICjjk1pbhzw3HGEHYfSHen6f2f/zb0a3W8mzsP+linXoCtahreLcAEFocZlBXyQ03eR3b8tlV/lOQgf2wMAbJy8VkuSqEdHwOx9D6NKwPEpiTeCxrIZOS2ZDmRNeqH4cQ5TSPiZNdWrqQ45WOGQ2hgD1IYkpBOxTGzuWDTa2sal6rgx3K04ik+e8TmXGarATk3PguHAKjT8ybEoCdTe5eTp9YDr9Ab0un1T9PYteqGyOIOJ6nguCEkBELv/5Qw0fcC1ISaYNNIx0tf9n2fgE3l6VkbLLyWTUE9kySIpVlDfNv2elpSUHcDhxANMXHbUNO0GyRmzfmkQM1OMiMssjvAQTCmyQ9RhPMw5bpE9rnb7b67GnKvFpAYjStahPZwOi4wlUzIiMUWX5NRUyy8aMFyo246wNFByTz0jt+7b/UxtczNEQ36+Aod8wedvADcDFpOV3wLdLVKum4sewrbUHceSi7p/wrDyCJTRe0XcrP+WFptS7T26IJ73Kt7jhps4J4h3sEGxaZKfWInvMfdUknmOcc72XQOseylhg2R1LX3YHNEImaeHLgDmw87OkxFVjAC2QT6McFc2JWYTI0vLXSs9q6Xin+mp95hmX/3KlQ2DfiVAKjLbwAqumLVao46kpSikHDSjiTb+V3QG9paFAzBRljCD4YWaBcoojlRZVtodjrGV7aWEC1ZhUcE2FSQCt4LHotjDKHGqqrdDu5rmnG37V585EjryLU0/JIcn+6Q9UvN2UqNhn+2dD4XLQBicFIBUNsj6K0LGBbKXLq3MEK/kLbtBgG/4s6QqacYPeJ0V78XwmwZ5p+pbL89s4CO7QOAKoFpRKv9WoEpoEikT8KFTdnHDwObzdS3Wo3eESSxNwg5WV+v6nlHqmz1mVpiRboJpKW1curcckz/x5Tm4AI9Lji5rN4VCouEIspIds9LUP1wbQT+RzwxraGqd7RndKwxTHdoJhp/TLB8AlDp4KG6mv8OhzvaA+Es0A4UzX1biSZ7x2MgoNGNOii0RDfKXx20xcaXR5fkVc7K7G4KPN4dBaWKeoev5U8OnKXNFMizq3IYQyhIdOrwmJ7dnT3KHO/+X6EcrSxgHsPtiqzRUx8Kn+ZI9tPRTPr7SEOz0muhpuyhJB06nnD1cZeR9rHtZjzgZPMnklFFt2j/qLA1eFL55Q6IAZQhlkhWmoNgR2ohUxPTO8shzNxpHghpco29FApidwOd+A8azhqKxGHsWSN98cc96r4243Ejz/Hc/SLWyZih1mwCuo2gQbokRzmQtCJ0KGCAW0rGWIZa8WebkiUVCT/K9H2SpWOFeU84YqHGe8u8CEHdWrJJf0+WQoB0PYC5hYhFoN9zkHazHmOCCvgkokSxpy0rrFyS57Ai0juS44mPhSm7jCrstK3bcDjVKFPTlSjpzRtGr5IMrmEDsdE9iEhK7LslvJeBXFz20oJHsNbFrcANi0lOLi5BmFrx8SYtjz+Q44AewdGmgBUEOI+/9wgK7cD+SprmuaCqppPP6XYqLEOOSsePmssqz8R8aVp00dIMgkBJ7g9dn9sUIcAcOjIkZYiugj9fniUyqSA12agkXH8z4yuv+7o+GeVy9W9uS55A/AJ2C7XER+Rb5ZQB/v827t/1g3ZEaaNZMqH/xrTLzJDalVyD3ELc3GEEfG9JVnz+0klV+dggtyAf2yEzI/2ZzhGNYAMPi1yt5w0ogc0v2f4fljVLEwHiaC1fWzb15jga2mhbSrxQqmV9enPUkTwxumMJah8FgxJj78VxXMb6VYp0So+M0arEeBPLg05ySzAxVMUYlHFGRKAVQLpgjK13Nb/w4qsqUsixsGBl0SWKYhRZ8qtdumPkY0iNVOikq8Wwu1Rn2OsG3pCVVrZfFQUzWrXTLAm1SkyYXiMo8pFKvn7gWRhWKC203k0iqdB0ihazYQ9iZFvwGUiJ/Zw4ovtGEHfc7OUfWHWByGapGPehuXhmRhdYcieGdhCPxsPiZd0J6NcciZd2K+ic7ap4KbBvRak9CjdmlL6rqZKzWxEmg/MrB3Qh/zPmVH0b/f+6Wo0ca55Te7Bj4+lBTICyCP6be6Ze5PPSvHp0rACzTHnL6gv159gT75EWwDt3+Gn2TjvI5BpvDRUTCtkDyUujkaPT9umI7A4I2rA6TfnpYqw7qJmpa5x9N68Hot2Yhf7TQM4aZtt8AVZX+v4hBEbp2aTsWny5XEYznwyJV1xJbJg5UvRKytgpXLghXgpaosWCngAQUNo8uvcRB2+ENsbaMK3bZt66TJ3ctCVXkgD4/YuMK4dTai48DWHU/1E99O0Zlw0f7wDpEsSCOLiLXUtT2pZOVyhyZMT0qo0j00X2J0JlwaPeqkFgQixiRgjMDExAHY/5QCVF17GOA57UQ1NVJUDirEEessN3DdClVDVUOZfnQdYWCOzvKiH6JL68tO0x1TyfYwYtVv2soBRiutclr3zdGaNLJsCDhtIcRwofWdEmRCeLygTbWkaQINt8xb3tFv0zem2CfgkGkDaZI9gFT9MbUbvPGlIwKWfLBZmfR2vUQNaaFg1tha15LDKpOwP4i8a5p5xM3nGtyGpOWjCYpSOT1jvQE/17IhFgcv6prUVS4g0uiWcl4ZH14g71UX7VIspz4Y17KHSuVIXpm3v3avEgTsBnMWUXAg5iTcliMemeriZFaaCHK7grfx32+9hnDkuhOOwMmMMm0S44BKWGIbY5prSmRxFFHnA8vxohbEMuVA4BYjnq2PrKNpHbVG9XXF1vMA3xcc6eaiDRLhGqitgpPJ+Jgdtat6QkCmzkeEMNfqZEYlHcA9dJj4wWUhyrO+UkE6v+cWrolG1sMmC56Oql4fGaSn6aHMw9H90spBs7OJZ0XofNe0wooi1AqY8gggQ/mSriKBF7y/BYQWEFsmCZWvaix74kjZJg0T1Q0w7K7Acq4+3iFx3vJbpQkZkC7zCSaI3/MHPKm52ryCmW8T0tHqFLSdCFdkO4avyMAMv3uofcKhRvIZ6eD3PBzI4y4rYOJo0f6IaIb6uTDLPiiLh0WeBO/kFQ35HYTg7c2oOlTfCIlL7TC1BJHo05edqbtIHFflmV2TxIYxxQK0Pq0IqETyI6472PO6JjLlzC+x2SwC3MVJ0Pmpd1DW+olm2ramRoKZyF94W0nftvv9L/afjhoVQQrR/PN0pyH+hj/qbVO9HFbYVJk2cEk+PWp5pHe6lqeUKA9qM96RFr3CVJ48WLKmUOrqHvYVu9eOHaxzDMJqjRwtdEDP/z42ZtG6mhld+07TnknobgymIbojMoUiFdGYXQu08yYMppCDoPAVUGgoJe6JsQqP+9JPwAj92Uepohmy1BZINMT5U7VMs0wZE+q+XkOelDH7e2T3f2xm6jEMMLbx+b8IDZ4VNxGf25oSDWzQBm2FIDx0K1UcAf607v8GlDC5UkGlB+EVCawBuHG/9iz5nPvaxwQZ+fWaMjJlyjLkLPZufnLxS8rWhMRqUdG4bkUjtUXN4dzgcMSSqqkogoiW/b2g0JkdLLN7WYQbMr1N31IjCHQpFRoTZGHzrIBz8BU4SjXzYcCJLE9pwYaM6mHsLM609GfgRKpTWBpjeLM+oUrucsctt9iBxCjYN7MlxYNezVA0uw30Mo8mN8r8DOzdI6rUz1+KMSI/w1pVV5mRA6TJheMo7U3SCiqcYIk/aw2nBJeg9GMM22qtMdYB1t4XvGi8ATpmGvi52KzwC3nXuDGTYYgPgHpmleZAph4Zpyd2YUyBMokLsfvXB8ADBKVkCJfFw9ZN5Q552FLyWDHjeQdSJXgxr7ElraUdy1phNUCTvmVtfyJV8FMtzoPITB8Bv+zJDsy2CTEn0LJwaNsu6ZgTKKcke6aptYnTkNe7BtNCTZaI+YROg2iFYP2pzLO8/wPx0OvDQzSd8KlGZ5xdxJorKN3kceZv7H0tw9+YJ3KG/BJcumX/z5ZjmRfG4wAN45AQOEM30lwsALb4sKgDoWMYypkxg0lqh2bb+39Qa8Ny/pRIoLtIhbmDyp1Xfs+n87F54TjkbgJ30fnUrLCWV3iNxNVeWh8IjsOvjj70OgONNcojGLu8AZVm6QFwH6ozRXUTS5MDen7h/X1ptz62QBNEr23pM0GUV2VAZPY/wpaimciNfn1Xejz8qeCeahVB0BfcFEsOZK7KChMEVTRPQRSDL3bs41oaJh+8MISVLJgYrq919vdKzH3deimF5V0h4I6Pz09P6F/ObY1lU3NJITwc6jycKp1S5/Ne4WW2qatYJb2Pi48YlrJfTSGree0BU/Kr/AQD5+r7XVsk0gMHmQeBLX8bu9vnErGLvca8peq3Z28mq3sfCu4wlplr7l/fV3Yrxag2FUjdCVimNHWqDk2cDCQ5vM/dW3CFyqA0++NZNhMJOvRl0FaxR8WciKRRMeUVcslVu3nawcHzMlmq8dCrqzwT44CYMHcvKTQSobL7jL/GGTN0sHuO6cY7qcdBPcbqJ3nbIlfbnspMud67AbvcOKClTxffvucQqmWCswsmsrsmHDNwLDv6efFj5mSZKzcffU8/dTqUtMvtB4/kpWJoPFKxUDccT1B/MJJMGvqkROsAs+o1CZGwjonfblzTg6rml1HLq/TaS5lds54uLN6WH89KEkfPmWOD5iu0ZLp0nWhzrAMH7RZ3WqAAP1vjqK2lYuwhzkHs2aKaveJ3kE7LXnntDLY4TDgwTPBkTXOpwgTZSdpqDCQgm2hfnpo58fjNz7fYYZ6eUmrwzkFE4QmRZ0hcijsNf9AjxHPwpXZ0HFj4mOMhetnclre4O+ng58GRZD2AqQiSbbG1zhoFpsxVQGAFwvRtvSwtoWo7ZXXuQ2z4GT/jnFFzrQai3FE5gvOe+hta28EXdnR/b8p2Ubd+X3rI+3b7su/Gj4pzKTTDip/mnf92f/Iscd2QFTsnERefUAYTzw3qefEb9LX//fuiqHy3Rr+ytvQj/XLS0ITcYD0C5Ybl72iRmoMZwCxB4VbRhpOSSwXKqjHSjUpvBLCuUnv1YSMuv4KhIznW/V0wh05zXUcjX8lG3gow9MeISwKqMBAKoQrM/UMFhfhOSRRsrhC/JGufQ7zAUsL2Wr7CdoxPxzA+n2oZpTkYb7JNm39Ug55GUVqyUu3E+WDysnXLp/Ht1MuBQZWSGmusBolFqa0siUyJsWS/ctToestiMNWwPP5vg3YXG/qyxUaOqqJIml3Bci+xiW7JcT50B9DaSEdWl66QqHDH3PLWzr/tyB3xuRq/KRALpNRVkDHmQ4HGFsgFG36lQ2yTd0L7/dz80YUwb7hDI6ppZwI78EihT3BdT82HTwg2Y5A6AZa/8fsKrD6IFcqrnlLl0eyx/C4OHcwd7XXDaMZm/pj0Eg7jGBSPSRHh3Prk4gQRhno5ydqnFgC30cPsVs1Zl2i1FrsusJeHs1zkqd3/PUbMKJeQs/SXh4yhC2WLWRi0sE8JnOxc0o/pZsgGCz8I2fPIOytYXBLsUL+q3MpoIftrjt6Sla39R94Q+YAqtPATATW+giAPs4+CooaaFoclMSF6zvndwSWKHNZeRvgUgnFSLZSKw0WjBxYGpjps8D81NjLpRKtGDaTkSzeFJYYCwsOX1CDVUlPc/DuRfLOsB+VLDeUdPteWNrZPOufZbtbWh8Jcu+oVbrG7MBoiyw52Xo7fkxk9gCt9OXk3xBEvO5eoQ/CGQF4XWQA8rVEwmb34QiTa8l6RUntjQ2rB3SvaSDrjEDL1kJaxi9RDn4y0SwShrEgzfphGwr1lmjTbnGmRoRTwDZSmi36AqaAXbdooAsL+P1NxnaTxhYKajvTU2jab0w+r9dDUOvUifszaLkzPJJKcshY4LGu+gfOWmwnSb1/L9hFuGyORgRG1t2YauFBnNQylbsgM5CCtPmoclF2hvNs05Z5jdh0KWPbtnLnQBalwcSxoEkorWbpDoX0pYocCJI6qBpKunNS3iitMA+jDMyyxk1Z+rC4lXdcdro8baTm+jEMo+2etjHQ8//8c7dW0O0Zf+JHdIb+xf6fAkmCwT9rHdk16QWqzvWs6cZUSI2vuieQLFKtn/suBXksJXGoWaC9XqA55G2ID1GLzweNwxq0pUkJT7TqbrVczU5gN9N5ENmR9iOBCRAm2TYjD8gW3CG5a8qkWy/XjDDhrDIWemYJCLCAcijSATFHWg1diwx/n1X5mlWwT+Xiw4fZtM/Glx/cc5wZgcRlESUAJUi7lDePAwHFsILPzIRdHE8LxqpiDCZ+BIswFbnwoX7QOUtS0Q2av1YcrChADpIUDctH1XDX/18zJk7HVpqIVkb53+4B1a0ybp+MylNmxxYw1OdNxr/TN0Mj6aJe+qZE1qdikstp1nWZW3Jm9XZJazLcPbMX4O9g6IAspS42Q6KJMjuYhUtB00mNEUuyY5Kji2JHLISMIcPJ8tF+x7ZPBwjYGrwG1VRQyOOWKcdaPAZ4V+VZYUBlBophIN/on5AxHuf+CC+LXhkvxhuYlCkyQSCTBoNBCMvV3rQWoq9rXWvGrhYdyWTX+sEOUlOk3rwth/OZCauXbsgype3HXSzk9f3j78wPWpGbXBm9LTXnA7R+f+VvJB5W2nJPVYdAXYM4LxnxPL72g2x72meUITtqN+KZO9HkxAkcJMi0TsQhSRmbMHWY6e/OdjiC9VwjgNp7EGIm6oC1b8bmcr2G24gaYV5xunMrj/rTuhtQ6FKNVpoMKH7odyouUGoix+0hNju1E1vgo24q2DjWjIG2jBN4/13wSau4yRaKS5+EGHeMT2K0sxDTxWBWZ4exzUNh4brOmDRTiDykd6O/emDmSGNraAeO38av+VuJzyhVzMZAeA3AlQ0amgF99iNH7OUol2urEF55CAL/+DqQwpJG3HvUP1bOyqugE5MlB2ZJrk6dPoWmhtu78gtTxWN94GdNgn/1QOTV45BRCNcJlUozRNZ9GMh5GJsdBnEwS77y3SDGy/9vAXMhQSPdqCL+C+Ux0dctDXxuVM6crAIr7ICpqSpI8FJwYj8+14e3UqjPxR25IyKjmJgLX1EkLAyy+K2zJXIgYe2XH7SCCFx4UCloXTAOvaplSUsk8e6gqmlIYon/iMAtJ+9ht0xKWYAn16+/pcPT3//f/\", BinaryEncoding.Base64), Compression.Deflate)),",
                "    Source = Table.FromRows(Rows, {\"gender\", \"SeniorCitizen\", \"Partner\", \"Dependents\", \"tenure\", \"PhoneService\", \"MultipleLines\", \"InternetService\", \"OnlineSecurity\", \"OnlineBackup\", \"DeviceProtection\", \"TechSupport\", \"StreamingTV\", \"StreamingMovies\", \"Contract\", \"PaperlessBilling\", \"PaymentMethod\", \"MonthlyCharges\", \"Churn\", \"service_count\", \"tenure_band\", \"fee_quartile\", \"has_internet\", \"fee_level\", \"service_level\", \"manual_payment\", \"risk_rule\", \"combination\", \"tenure_band_order\"}),",
                "    Typed = Table.TransformColumnTypes(Source, {{\"gender\", type text}, {\"SeniorCitizen\", Int64.Type}, {\"Partner\", type text}, {\"Dependents\", type text}, {\"tenure\", Int64.Type}, {\"PhoneService\", type text}, {\"MultipleLines\", type text}, {\"InternetService\", type text}, {\"OnlineSecurity\", type text}, {\"OnlineBackup\", type text}, {\"DeviceProtection\", type text}, {\"TechSupport\", type text}, {\"StreamingTV\", type text}, {\"StreamingMovies\", type text}, {\"Contract\", type text}, {\"PaperlessBilling\", type text}, {\"PaymentMethod\", type text}, {\"MonthlyCharges\", type number}, {\"Churn\", type text}, {\"service_count\", Int64.Type}, {\"tenure_band\", type text}, {\"fee_quartile\", type text}, {\"has_internet\", type text}, {\"fee_level\", type text}, {\"service_level\", type text}, {\"manual_payment\", type text}, {\"risk_rule\", type text}, {\"combination\", type text}, {\"tenure_band_order\", Int64.Type})",
                "in",
                "    Typed"
              ]
            }
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Customers\"]"
      }
    ]
  }
}
